#!/usr/bin/env bash
# env-known-roads-reminder.sh — UserPromptSubmit hook that surfaces Known Roads
# for environment/secrets/API-key operations BEFORE any tool call.
#
# Detects env/secrets keywords in user prompt and outputs the canonical pipeline.
# Always returns "approve" — never blocks.
#
# Environment:
#   CLAUDE_USER_PROMPT — the user's input text (set by Claude Code)

set -eo pipefail

PROMPT="${CLAUDE_USER_PROMPT:-}"

# Quick exit if no prompt or empty
if [ -z "${PROMPT}" ]; then
    echo '{"decision":"approve"}'
    exit 0
fi

# Check for env/secrets/API-key-related keywords (case-insensitive)
if echo "${PROMPT}" | grep -iqE '(api[_. ]?key|env[_. ]?tier|env[_. ]?shared|add[_. ]*key|secret|credential|minimax[_. ]*key|provider[_. ]*key|openai[_. ]*key|anthropic[_. ]*key|env[_. ]?setup|\.env)'; then
    cat <<'EOF'
{"decision":"approve","message":"<user-prompt-submit-hook>\nKnown Roads — Environment & Secrets:\n\n  NEVER edit env.tier-*, env.shared, or .env files directly.\n  They are in zeroAccessPaths and auto-generated by the secrets pipeline.\n\n  Canonical workflow:\n    gh secret set <KEY_NAME>              # Add to GitHub Secrets\n    make -C pmoves secrets-funnel          # CHIT decode → tier distribution\n    make -C pmoves up-<service>            # Restart with fresh env\n\n  Interactive setup:\n    make -C pmoves env-setup               # Prompts for missing keys\n    make -C pmoves brand-defaults          # Auto-generate weak keys\n\n  Validation:\n    make -C pmoves auth-alignment          # Cross-tier consistency\n    make -C pmoves env-check               # Preflight validation\n\n  Skills:\n    /botz:secrets                          # Manage secrets via CHIT\n    /deploy:secrets-funnel                 # Full pipeline run\n    /deploy:bootstrap-env                  # First-time setup\n\n  See: pmoves/docs/MINIMAX_API_KEY_SETUP.md for provider key example\n</user-prompt-submit-hook>"}
EOF
    exit 0
fi

# No match — silent pass
echo '{"decision":"approve"}'
exit 0
