presign:
  build: ./services/presign
  restart: unless-stopped
  env_file: [.env]
  environment:
    - MINIO_ENDPOINT=${MINIO_ENDPOINT}
    - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
    - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    - MINIO_SECURE=${MINIO_SECURE:-false}
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    - ALLOWED_BUCKETS=${ALLOWED_BUCKETS:-assets,outputs}
    - PRESIGN_SHARED_SECRET=${PRESIGN_SHARED_SECRET}
  ports: ["8088:8080"]
  profiles: ["data","orchestration"]
