version: "3.9"
services:
  tensorzero:
    image: tensorzero/tensorzero:latest
    restart: unless-stopped
    env_file: [.env, .env.tensorzero]
    volumes:
      - ./tensorzero.toml:/app/config/tensorzero.toml:ro
    ports: ["3000:3000"]
    depends_on: [clickhouse]

  clickhouse:
    image: clickhouse/clickhouse-server:24
    restart: unless-stopped
    environment:
      - CLICKHOUSE_DB=${TENSORZERO_OBS_CLICKHOUSE_DB:-tensorzero}
      - CLICKHOUSE_USER=${TENSORZERO_OBS_CLICKHOUSE_USER:-tz}
      - CLICKHOUSE_PASSWORD=${TENSORZERO_OBS_CLICKHOUSE_PASSWORD:-changeme}
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ports: ["8123:8123"]

volumes:
  clickhouse-data:
