#!/bin/bash
# init-a0.sh — Agent Zero Elder-Melchor edition boot init.
#
# Same contract as the stock agent-zero image (copy /git/agent-zero -> /a0 on
# first boot), plus the PMOVES.AI settings integration: the _model_config
# plugin resolves ALL model settings from presets.yaml (the fork has no env
# surface for preset CONTENTS — A0_SET_chat_model_* is dead upstream), and
# without intervention the repo-shipped openrouter fallback wins. Per operator
# directive the presets file is GENERATED from env at every first boot —
# compose/env.tier stays the single source of truth; no models are hardcoded
# here or baked into the image. API keys never enter the yaml (they ride the
# normal env/settings flow, per the plugin's own README).
set -e

A0_ROOT="${AGENT_ZERO_HOME:-/a0}"

# ── 1. first-boot copy (stock contract) ─────────────────────────────
if [ ! -f "$A0_ROOT/run_ui.py" ]; then
  cp -rn --no-preserve=ownership,mode "/git/agent-zero/." "$A0_ROOT"
fi

# ── 2. env-driven model presets (_model_config integration point) ────
# Writes usr/plugins/_model_config/presets.yaml + the selection config.json
# from A0_ELDER_* env ONLY when no presets file exists (fresh /a0). Operator
# UI edits afterwards are preserved (idempotent, never clobbers).
PRESETS_DIR="$A0_ROOT/usr/plugins/_model_config"
PRESETS_FILE="$PRESETS_DIR/presets.yaml"
CONFIG_FILE="$PRESETS_DIR/config.yaml"

if [ ! -f "$PRESETS_FILE" ]; then
  CHAT_MODEL="${A0_ELDER_CHAT_MODEL:-glm-5.3}"
  UTIL_MODEL="${A0_ELDER_UTIL_MODEL:-glm-5.3-flash}"
  EMBED_MODEL="${A0_ELDER_EMBED_MODEL:-sentence-transformers/all-MiniLM-L6-v2}"
  EMBED_PROVIDER="${A0_ELDER_EMBED_PROVIDER:-huggingface}"
  LLM_BASE="${A0_ELDER_LLM_BASE:-https://api.z.ai/api/coding/paas/v4}"
  CHAT_CTX="${A0_ELDER_CHAT_CTX:-200000}"
  UTIL_CTX="${A0_ELDER_UTIL_CTX:-128000}"

  mkdir -p "$PRESETS_DIR"
  cat > "$PRESETS_FILE" <<EOF
# GENERATED by init-a0.sh from A0_ELDER_* env — do not hand-edit committed
# copies; change the env (docker-compose.a0-elder-melchor.yml / env.tier-agent)
# and recreate the container. Deleting this file regenerates it on next boot.
- name: Default
  chat:
    provider: openai
    name: $CHAT_MODEL
    api_base: $LLM_BASE
    ctx_length: $CHAT_CTX
    ctx_history: 0.7
    vision: true
    max_embeds: 10
    rl_requests: 0
    rl_input: 0
    rl_output: 0
    kwargs: {}
  utility:
    provider: openai
    name: $UTIL_MODEL
    api_base: $LLM_BASE
    ctx_length: $UTIL_CTX
    ctx_input: 0.7
    rl_requests: 0
    rl_input: 0
    rl_output: 0
    kwargs: {}
  embedding:
    provider: $EMBED_PROVIDER
    name: $EMBED_MODEL
    api_base: ''
    rl_requests: 0
    rl_input: 0
    kwargs: {}
EOF
  echo "[init-a0] generated $PRESETS_FILE from env (chat=$CHAT_MODEL base=$LLM_BASE)"
fi

# Scoped selection: pin the global plugin config to the generated Default
# preset (selection-only, per the plugin README's scoped-selection contract).
if [ ! -f "$CONFIG_FILE" ]; then
  echo 'model_preset: "Default"' > "$CONFIG_FILE"
fi
