version: "3.8"

services:
  hbbs:
    image: ${RUSTDESK_SERVER_IMAGE:-rustdesk/rustdesk-server:latest}
    container_name: rustdesk-hbbs
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: "exec hbbs ${HBBS_ARGS:-}"
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - ${RUSTDESK_DATA_ROOT:-./data/rustdesk}/hbbs:/root
    ports:
      - ${RUSTDESK_PORT_HBBS_TCP:-21115}:21115
      - ${RUSTDESK_PORT_HBBS_RELAY_TCP:-21116}:21116
      - ${RUSTDESK_PORT_HBBS_RELAY_UDP:-21116}:21116/udp
      - ${RUSTDESK_PORT_HBBS_API:-21118}:21118

  hbbr:
    image: ${RUSTDESK_SERVER_IMAGE:-rustdesk/rustdesk-server:latest}
    container_name: rustdesk-hbbr
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: "exec hbbr ${HBBR_ARGS:-}"
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - ${RUSTDESK_DATA_ROOT:-./data/rustdesk}/hbbr:/root
    ports:
      - ${RUSTDESK_PORT_HBBR_TCP:-21117}:21117
      - ${RUSTDESK_PORT_HBBR_REVERSE:-21119}:21119

volumes: {}
