"""Playwright-based YouTube cookie extraction.

Adapted from pmoves/tools/youtube_po_token_capture.py.
Launches headless Chromium, injects OAuth session, extracts cookies + PO token.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Optional

from playwright.async_api import async_playwright

logger = logging.getLogger("yt-cookie-refresher.extractor")

# Known-good short video for triggering cookie issuance + PO token
TEST_VIDEO_ID = "dQw4w9WgXcQ"
YOUTUBE_BASE = "https://www.youtube.com"


async def extract_cookies_and_po_token(
    access_token: str,
    video_id: str = TEST_VIDEO_ID,
) -> tuple[str, Optional[str]]:
    """Launch Playwright, inject OAuth session, harvest cookies + PO token.

    Args:
        access_token: Fresh Google OAuth2 access token.
        video_id: YouTube video ID to load (triggers cookie issuance).

    Returns:
        (netscape_cookies_str, po_token_or_none)
    """
    po_token: Optional[str] = None

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context()

        # Inject the OAuth session by setting auth cookies
        # Google OAuth access tokens can be injected as SAPISID-like cookies
        # or we navigate to accounts.google.com with the token to establish session
        page = await context.new_page()

        # Set OAuth authorization header for YouTube API requests
        await context.set_extra_http_headers({
            "Authorization": f"Bearer {access_token}",
        })

        # Navigate to YouTube to trigger cookie issuance
        logger.info("Navigating to YouTube to establish session...")
        await page.goto(YOUTUBE_BASE, wait_until="networkidle", timeout=30000)
        await page.wait_for_timeout(3000)

        # Capture PO token by loading a video
        po_tokens = []

        async def _on_response(response):
            nonlocal po_tokens
            if "youtubei/v1/player" in response.url:
                try:
                    body = await response.json()
                    streaming = body.get("streamingData", {})
                    for fmt in streaming.get("adaptiveFormats", []):
                        if "poToken" in fmt:
                            po_tokens.append(fmt["poToken"])
                    if "poToken" in streaming:
                        po_tokens.append(streaming["poToken"])
                except Exception:
                    pass

        page.on("response", _on_response)

        logger.info(f"Loading video {video_id} to capture PO token...")
        await page.goto(
            f"{YOUTUBE_BASE}/watch?v={video_id}",
            wait_until="domcontentloaded",
            timeout=30000,
        )
        await page.wait_for_timeout(15000)  # let player initialize

        # Extract all cookies from the browser context
        all_cookies = await context.cookies()
        await browser.close()

    if po_tokens:
        po_token = po_tokens[0]
        logger.info(f"Captured {len(po_tokens)} PO token(s)")
    else:
        logger.warning("No PO tokens captured from player response")

    # Convert to Netscape format (yt-dlp compatible)
    netscape = _cookies_to_netscape(all_cookies)
    logger.info(f"Extracted {len(all_cookies)} cookies ({len(netscape)} bytes)")

    return netscape, po_token


def _cookies_to_netscape(cookies: list[dict]) -> str:
    """Convert Playwright cookie list to Netscape cookie file format."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by PMOVES yt-cookie-refresher",
        f"# {datetime.now(timezone.utc).isoformat()}",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", "")
        if not domain.startswith("."):
            domain = "." + domain
        flag = "TRUE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = str(int(c.get("expires", 0)))
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


# NOTE: No sync wrapper. do_refresh() is async (called by the FastAPI cron
# scheduler which runs in the event loop). `asyncio.run()` from within an
# active loop raises RuntimeError. Callers should `await` extract_cookies_and_po_token
# directly. This function was removed per CodeRabbit P1 thread on PR #1273.
