#!/usr/bin/env bash
set -euo pipefail

# PMOVES • Landscape of Consciousness Harvester (Bash Edition)
# Mirrors the Landscape of Consciousness taxonomy into the PMOVES knowledge stack.

BASE_URL="${BASE_URL:-https://loc.closertotruth.com}"
REPO_ROOT="${REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")"/../../.. && pwd)}"
TARGET_SUFFIX="${TARGET_SUFFIX:-pmoves/data/consciousness/Constellation-Harvest-Regularization}"
TARGET_PATH="${REPO_ROOT}/${TARGET_SUFFIX}"
UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'

echo "=== PMOVES Consciousness Harvester ==="
echo "Base URL      : ${BASE_URL}"
echo "Repo root     : ${REPO_ROOT}"
echo "Target path   : ${TARGET_PATH}"

mkdir -p "${TARGET_PATH}"

info() { printf '\033[0;36m%s\033[0m\n' "$*"; }
warn() { printf '\033[0;33m%s\033[0m\n' "$*"; }
success() { printf '\033[0;32m%s\033[0m\n' "$*"; }

# 1. Directory structure ------------------------------------------------------
info "Creating directory structure..."
dirs=(
  website-mirror theories categories subcategories research-papers data-exports
  media scripts processed-for-rag processed-for-rag/embeddings-ready
  processed-for-rag/supabase-import
)
for d in "${dirs[@]}"; do
  mkdir -p "${TARGET_PATH}/${d}"
done
success "Directory tree ready."

# 2. Download helper ----------------------------------------------------------
download_with_retry() {
  local url="$1" out="$2" max="${3:-3}" attempt=1
  while (( attempt <= max )); do
    info "Downloading (attempt ${attempt}/${max}): ${url}"
    if curl -fsSL -A "${UA}" "${url}" -o "${out}"; then
      success "Saved to ${out}"
      return 0
    fi
    warn "Attempt ${attempt} failed; retrying..."
    sleep $(( attempt * 2 ))
    (( attempt++ ))
  done
  warn "Failed to download ${url} after ${max} attempts."
  return 1
}

# 3. Download primary + related resources ------------------------------------
info "Fetching primary research references..."
download_with_retry \
  "https://www.sciencedirect.com/science/article/pii/S0079610723001128" \
  "${TARGET_PATH}/research-papers/kuhn-landscape-consciousness-2024.html" || true

declare -A RELATED=(
  ["pubmed-summary.html"]="https://pubmed.ncbi.nlm.nih.gov/38281544/"
  ["researchgate-page.html"]="https://www.researchgate.net/publication/377744305_A_landscape_of_consciousness_Toward_a_taxonomy_of_explanations_and_implications"
  ["closertotruth-article.html"]="https://closertotruth.com/news/a-landscape-of-consciousness-toward-a-taxonomy-of-explanations-and-implications/"
  ["mcgilchrist-review.html"]="https://channelmcgilchrist.com/a-landscape-of-consciousness-toward-a-taxonomy-of-explanations-and-implications-by-robert-lawrence-kuhn-doi-org-10-1016-j-pbiomolbio-2023-12-003/"
)

for filename in "${!RELATED[@]}"; do
  download_with_retry "${RELATED[$filename]}" \
    "${TARGET_PATH}/research-papers/${filename}" || true
done

# 4. Generate Selenium PowerShell helper --------------------------------------
info "Writing Selenium scraper (PowerShell) helper..."
cat > "${TARGET_PATH}/scripts/selenium-scraper.ps1" <<'EOF'
# Auto-generated by consciousness_downloader.sh
if (!(Get-Module -ListAvailable -Name Selenium)) {
    Install-Module -Name Selenium -Force -Scope CurrentUser
}

Import-Module Selenium
$chromeOptions = New-Object OpenQA.Selenium.Chrome.ChromeOptions
$chromeOptions.AddArgument('--headless')
$chromeOptions.AddArgument('--no-sandbox')
$chromeOptions.AddArgument('--disable-dev-shm-usage')

$BaseUrl = "https://loc.closertotruth.com"
$TargetPath = Join-Path (Resolve-Path "$PSScriptRoot/..") ""

try {
    $driver = New-Object OpenQA.Selenium.Chrome.ChromeDriver($chromeOptions)
    $driver.Navigate().GoToUrl("$BaseUrl/all-consciousness-categories-subcategories-and-theories")
    Start-Sleep -Seconds 10
    $mainPageHtml = $driver.PageSource
    $mainPagePath = Join-Path $TargetPath "website-mirror/main-page.html"
    $mainPageHtml | Out-File -FilePath $mainPagePath -Encoding UTF8

    $theoryLinks = $driver.FindElements([OpenQA.Selenium.By]::TagName('a')) |
        Where-Object { $_.GetAttribute('href') -like '*theory*' -or $_.GetAttribute('href') -like '*category*' }

    $links = @()
    foreach ($link in $theoryLinks) {
        $href = $link.GetAttribute('href')
        $text = $link.Text
        if ($href -and $href.StartsWith('http')) {
            $links += @{ Url = $href; Text = $text }
        }
    }

    $linksJson = $links | ConvertTo-Json
    $linksPath = Join-Path $TargetPath "data-exports/discovered-links.json"
    $linksJson | Out-File -FilePath $linksPath -Encoding UTF8
    Write-Host ("Captured {0} links" -f $links.Count)
}
finally {
    if ($driver) { $driver.Quit() }
}
EOF
success "Selenium helper ready at scripts/selenium-scraper.ps1"

# 5. Theory categorisation directories ---------------------------------------
info "Creating theory classification folders..."
declare -A CATEGORIES=(
  ["Materialism-Theories"]="Philosophical Neurobiological Electromagnetic-Field Computational-Informational Homeostatic-Affective Embodied-Enactive Relational Representational Language Phylogenetic-Evolution"
  ["Non-Reductive-Physicalism"]=""
  ["Quantum-Theories"]=""
  ["Integrated-Information-Theory"]=""
  ["Panpsychisms"]=""
  ["Monisms"]=""
  ["Dualisms"]=""
  ["Idealisms"]=""
  ["Anomalous-Altered-States"]=""
  ["Challenge-Theories"]=""
)

for category in "${!CATEGORIES[@]}"; do
  mkdir -p "${TARGET_PATH}/theories/${category}"
  for sub in ${CATEGORIES[$category]}; do
    mkdir -p "${TARGET_PATH}/theories/${category}/${sub}"
  done
done
success "Theory folders ready."

# 6. Data template ------------------------------------------------------------
info "Generating data template JSON..."
cat > "${TARGET_PATH}/data-exports/consciousness-data-template.json" <<EOF
{
  "metadata": {
    "source": "Landscape of Consciousness",
    "author": "Robert Lawrence Kuhn",
    "extracted_date": "$(date +%Y-%m-%d)",
    "base_url": "${BASE_URL}"
  },
  "theories": [],
  "categories": [],
  "subcategories": [],
  "implications": {
    "meaning_purpose_value": [],
    "ai_consciousness": [],
    "virtual_immortality": [],
    "survival_beyond_death": []
  }
}
EOF
success "Data template saved."

# 7. README -------------------------------------------------------------------
info "Writing harvest README..."
cat > "${TARGET_PATH}/README.md" <<'EOF'
# PMOVES • Landscape of Consciousness Dataset

This bundle mirrors Robert Lawrence Kuhn's *Landscape of Consciousness* taxonomy into the PMOVES knowledge stack for downstream CHIT decoding, Geometry Bus constellations, and Evo Swarm curation.

## Directory Layout (`pmoves/data/consciousness/Constellation-Harvest-Regularization/`)
- `website-mirror/` — HTML snapshots of the taxonomy portal
- `theories/` — folders per major category (Materialism, Quantum, Panpsychism, etc.)
- `categories/`, `subcategories/` — supplemental hierarchy exports
- `research-papers/` — source papers + related commentary
- `data-exports/` — JSON/CSV manifests for ingestion
- `processed-for-rag/` — embedding-ready artifacts + Supabase import SQL
- `media/` — referenced imagery/video assets
- `scripts/` — Selenium scraper, RAG processors, helper utilities

## PMOVES Integration Checklist
1. **Harvest dynamic content**
   - PowerShell: `pwsh -File scripts/selenium-scraper.ps1`
2. **Prepare embeddings + JSONL**
   - Populate `processed-for-rag/embeddings-ready/` with chunked JSONL exports.
3. **Load Supabase (CLI runtime)**
   - Ensure `make supa-start && make up` are running.
   - Apply schema from `processed-for-rag/supabase-import/consciousness-schema.sql`.
4. **Push embeddings**
   - Import `processed-for-rag/supabase-import/n8n-workflow.json` into n8n (`make up-n8n`), configure credentials, and process the JSONL export.
5. **Surface in Geometry / Evo Swarm**
   - Publish CGP payloads (`make mesh-handshake FILE=...` or via Agent Zero) and document IDs for CHIT demos.

## Why This Matters
- Anchors authoritative consciousness theory metadata within Supabase + Qdrant for Geometry Bus queries.
- Enables Evo Swarm to leverage curated philosophical corpora when generating pack recommendations.
- Enriches CHIT playback scenarios with vetted cognitive science knowledge.

Log evidence in `pmoves/docs/SESSION_IMPLEMENTATION_PLAN.md` as stages complete.
EOF
success "README generated."

# 8. Summary ------------------------------------------------------------------
echo
success "Consciousness harvest scaffolding complete."
echo "Next steps:"
echo "  1. PowerShell Selenium scrape (for dynamic content)"
echo "  2. Populate processed-for-rag artifacts and import into Supabase/n8n"
echo "  3. Publish CGP packets to Geometry Bus / Evo Swarm"
echo
echo "Artifacts ready under: ${TARGET_PATH}"
