hi-rag-gateway-v2:
  build: ./services/hi-rag-gateway-v2
  restart: unless-stopped
  env_file: [.env]
  environment:
    - QDRANT_URL=${QDRANT_URL:-http://qdrant:6333}
    - QDRANT_COLLECTION=${QDRANT_COLLECTION:-pmoves_chunks}
    - SENTENCE_MODEL=${SENTENCE_MODEL:-all-MiniLM-L6-v2}
    - INDEXER_NAMESPACE=${INDEXER_NAMESPACE:-pmoves}
    - RERANK_ENABLE=${RERANK_ENABLE:-true}
    - RERANK_MODEL=${RERANK_MODEL:-BAAI/bge-reranker-base}
    - RERANK_TOPN=${RERANK_TOPN:-50}
    - RERANK_K=${RERANK_K:-10}
  ports: ["8087:8086"]
  profiles: ["workers"]
