-- Generated by consciousness_build.py
-- Canonical schema: pmoves_core (matches supabase/initdb/13_consciousness_theories.sql)
CREATE TABLE IF NOT EXISTS pmoves_core.consciousness_theories (
    id          text PRIMARY KEY,
    title       text NOT NULL,
    url         text,
    category    text NOT NULL DEFAULT 'research-paper',
    content     text NOT NULL,
    namespace   text NOT NULL DEFAULT 'pmoves.consciousness',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS consciousness_theories_category_idx
  ON pmoves_core.consciousness_theories(category);
CREATE INDEX IF NOT EXISTS consciousness_theories_namespace_idx
  ON pmoves_core.consciousness_theories(namespace);
CREATE INDEX IF NOT EXISTS consciousness_theories_content_trgm
  ON pmoves_core.consciousness_theories USING gin (content gin_trgm_ops);
