render-webhook:
  build: ./services/render-webhook
  restart: unless-stopped
  env_file: [.env]
  environment:
    - SUPA_REST_URL=${SUPA_REST_URL:-http://postgrest:3000}
    - DEFAULT_NAMESPACE=${INDEXER_NAMESPACE:-pmoves}
    - RENDER_WEBHOOK_SHARED_SECRET=${RENDER_WEBHOOK_SHARED_SECRET}
    - RENDER_AUTO_APPROVE=${RENDER_AUTO_APPROVE:-false}
  ports: ["8085:8085"]
  profiles: ["orchestration","workers"]
