// 01_init.cypher
CREATE CONSTRAINT asset_uri IF NOT EXISTS FOR (a:Asset) REQUIRE a.uri IS UNIQUE;
CREATE CONSTRAINT agent_name IF NOT EXISTS FOR (a:Agent) REQUIRE a.name IS UNIQUE;
CREATE CONSTRAINT workflow_name IF NOT EXISTS FOR (w:Workflow) REQUIRE w.name IS UNIQUE;
CREATE CONSTRAINT generation_id IF NOT EXISTS FOR (g:Generation) REQUIRE g.id IS UNIQUE;
CREATE CONSTRAINT topic_label IF NOT EXISTS FOR (t:Topic) REQUIRE t.label IS UNIQUE;
CREATE CONSTRAINT kb_item_id IF NOT EXISTS FOR (k:KBItem) REQUIRE k.id IS UNIQUE;
