#!/usr/bin/env bash
# =============================================================================
# PMOVES Supabase Secret Generation Script
# =============================================================================
# Generates all required cryptographic secrets for the official Supabase stack.
# Run this script to create a production-ready env.tier-supabase file.
#
# Usage:
#   bash scripts/generate-supabase-secrets.sh > env.tier-supabase
#   bash scripts/generate-supabase-secrets.sh | tee env.tier-supabase
#
# Output: Complete env.tier-supabase file with generated secrets
# =============================================================================

set -euo pipefail

# Color output
if [[ -t 1 ]]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    NC='\033[0m' # No Color
else
    RED=''
    GREEN=''
    YELLOW=''
    NC=''
fi

echo -e "${GREEN}Generating Supabase secrets for PMOVES.AI...${NC}"
echo ""

# =============================================================================
# VALIDATE PREREQUISITES
# =============================================================================

# Check for openssl availability
if ! command -v openssl >/dev/null 2>&1; then
    echo -e "${RED}ERROR: openssl is required but not installed${NC}"
    echo "Install with: apt-get install openssl (Ubuntu/Debian)"
    echo "             brew install openssl (macOS)"
    exit 1
fi

# =============================================================================
# GENERATE SECRETS
# =============================================================================

# JWT Secret (≥32 chars) - Used for signing all JWT tokens
JWT_SECRET=$(openssl rand -base64 64 | tr -d '\n')

# PostgreSQL Password (≥16 chars)
# Generate more bytes initially to ensure 32 chars after removing =/
POSTGRES_PASSWORD=$(openssl rand -base64 48 | tr -d '=/' | cut -c1-32)

# SECRET_KEY_BASE (≥32 chars) - Rails/Erlang session secret
SECRET_KEY_BASE=$(openssl rand -base64 64 | tr -d '\n')

# VAULT_ENC_KEY (32 bytes = 64 hex chars) - Supavisor encryption key
VAULT_ENC_KEY=$(openssl rand -hex 32)

# PG_META_CRYPTO_KEY (≥32 chars) - Postgres Meta encryption
PG_META_CRYPTO_KEY=$(openssl rand -base64 48 | tr -d '\n')

# Logflare tokens
LOGFLARE_PUBLIC=$(openssl rand -base64 48 | tr -d '\n')
LOGFLARE_PRIVATE=$(openssl rand -base64 48 | tr -d '\n')

# Kong dashboard password
DASHBOARD_PASSWORD=$(openssl rand -base64 16 | tr -d '\n')

# Pooler tenant ID
POOLER_TENANT_ID=$(openssl rand -hex 16)

# =============================================================================
# GENERATE API KEYS (JWT TOKENS)
# =============================================================================

# Helper function to generate JWT tokens
# Args: payload (e.g., '{"role":"anon"}'), secret
generate_jwt_token() {
    local payload="$1"
    local secret="$2"

    # Header
    local header='{"alg":"HS256","typ":"JWT"}'
    local header_encoded=$(echo -n "$header" | base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n')

    # Payload
    local payload_encoded=$(echo -n "$payload" | base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n')

    # Signature
    local signing_input="${header_encoded}.${payload_encoded}"
    local signature=$(echo -n "$signing_input" | openssl dgst -sha256 -hmac "$secret" -binary | base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n')

    echo "${header_encoded}.${payload_encoded}.${signature}"
}

# Generate ANON_KEY (role: anon)
ANON_KEY=$(generate_jwt_token '{"role":"anon"}' "$JWT_SECRET")

# Generate SERVICE_ROLE_KEY (role: service_role)
SERVICE_KEY=$(generate_jwt_token '{"role":"service_role"}' "$JWT_SECRET")

# =============================================================================
# OUTPUT ENV FILE
# =============================================================================

cat << 'EOF'
# =============================================================================
# PMOVES Supabase Tier Environment Variables
# =============================================================================
# AUTO-GENERATED by scripts/generate-supabase-secrets.sh
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# WARNING: Keep this file secure and never commit it to version control!
# =============================================================================

# -----------------------------------------------------------------------------
# CRITICAL SECURITY SECRETS (AUTO-GENERATED)
# -----------------------------------------------------------------------------

# JWT Secret - Used for signing all Supabase JWT tokens
JWT_SECRET=
EOF

echo "$JWT_SECRET"

cat << 'EOF'

# JWT Expiry - Token lifetime in seconds (3600 = 1 hour)
JWT_EXPIRY=3600

# Anonymous Key - Public key for unauthenticated API access
ANON_KEY=
EOF

echo "$ANON_KEY"

cat << 'EOF'

# Service Role Key - Admin key for backend operations (KEEP SECRET!)
SERVICE_ROLE_KEY=
EOF

echo "$SERVICE_KEY"

cat << 'EOF'

# Rails/Erlang Session Secret for Realtime and Supavisor
SECRET_KEY_BASE=
EOF

echo "$SECRET_KEY_BASE"

cat << 'EOF'

# Vault Encryption Key for Supavisor (connection pooler)
VAULT_ENC_KEY=
EOF

echo "$VAULT_ENC_KEY"

cat << 'EOF'

# Postgres Meta Encryption Key
PG_META_CRYPTO_KEY=
EOF

echo "$PG_META_CRYPTO_KEY"

cat << 'EOF'

# -----------------------------------------------------------------------------
# Analytics (Logflare) Secrets
# -----------------------------------------------------------------------------

LOGFLARE_PUBLIC_ACCESS_TOKEN=
EOF

echo "$LOGFLARE_PUBLIC"

cat << 'EOF'

LOGFLARE_PRIVATE_ACCESS_TOKEN=
EOF

echo "$LOGFLARE_PRIVATE"

cat << 'EOF'

# -----------------------------------------------------------------------------
# Kong API Gateway Authentication
# -----------------------------------------------------------------------------

DASHBOARD_USERNAME=supabase
DASHBOARD_PASSWORD=
EOF

echo "$DASHBOARD_PASSWORD"

cat << 'EOF'

# -----------------------------------------------------------------------------
# Database Configuration
# -----------------------------------------------------------------------------

# IMPORTANT: Update env.tier-data with same POSTGRES_PASSWORD!
POSTGRES_HOST=db
POSTGRES_DB=postgres
POSTGRES_PORT=5432
POSTGRES_PASSWORD=
EOF

echo "$POSTGRES_PASSWORD"

cat << 'EOF'

# -----------------------------------------------------------------------------
# Auth (GoTrue) Configuration
# -----------------------------------------------------------------------------

SITE_URL=http://localhost:3000
ADDITIONAL_REDIRECT_URLS=
API_EXTERNAL_URL=http://localhost:8000
DISABLE_SIGNUP=false

# Email Authentication
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=false
SMTP_ADMIN_EMAIL=admin@example.com
SMTP_HOST=supabase-mail
SMTP_PORT=2500
SMTP_USER=fake_mail_user
SMTP_PASS=fake_mail_password
SMTP_SENDER_NAME=fake_sender

# Phone Authentication
ENABLE_PHONE_SIGNUP=true
ENABLE_PHONE_AUTOCONFIRM=true
ENABLE_ANONYMOUS_USERS=false

# Email Confirmation URL Paths
MAILER_URLPATHS_CONFIRMATION=/auth/v1/verify
MAILER_URLPATHS_INVITE=/auth/v1/verify
MAILER_URLPATHS_RECOVERY=/auth/v1/verify
MAILER_URLPATHS_EMAIL_CHANGE=/auth/v1/verify

# -----------------------------------------------------------------------------
# API (PostgREST) Configuration
# -----------------------------------------------------------------------------

PGRST_DB_SCHEMAS=public,storage,graphql_public,pmoves_core

# -----------------------------------------------------------------------------
# API Gateway (Kong) Configuration
# -----------------------------------------------------------------------------

KONG_HTTP_PORT=8000
KONG_HTTPS_PORT=8443

# -----------------------------------------------------------------------------
# Supavisor Connection Pooler Configuration
# -----------------------------------------------------------------------------

POOLER_PROXY_PORT_TRANSACTION=6543
POOLER_DEFAULT_POOL_SIZE=20
POOLER_MAX_CLIENT_CONN=100
POOLER_TENANT_ID=
EOF

echo "$POOLER_TENANT_ID"

cat << 'EOF'

POOLER_DB_POOL_SIZE=5

# -----------------------------------------------------------------------------
# Studio Dashboard Configuration
# -----------------------------------------------------------------------------

STUDIO_DEFAULT_ORGANIZATION=PMOVES
STUDIO_DEFAULT_PROJECT=PMOVES Core
SUPABASE_PUBLIC_URL=http://localhost:8000
IMGPROXY_ENABLE_WEBP_DETECTION=true
SUPABASE_STUDIO_PORT=54323
OPENAI_API_KEY=

# -----------------------------------------------------------------------------
# Edge Functions Configuration
# -----------------------------------------------------------------------------

FUNCTIONS_VERIFY_JWT=false

# -----------------------------------------------------------------------------
# Docker Configuration
# -----------------------------------------------------------------------------

DOCKER_SOCKET_LOCATION=/var/run/docker.sock

# -----------------------------------------------------------------------------
# PMOVES Integration Overrides
# -----------------------------------------------------------------------------

SUPABASE_REST_URL=http://localhost:8000
SUPA_REST_URL=${SUPABASE_REST_URL}
SUPABASE_URL=${SUPABASE_REST_URL}
SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_KEY=${SERVICE_ROLE_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
PGRST_JWT_SECRET=${JWT_SECRET}
POSTGREST_URL=http://rest:3000
EOF

echo ""
echo -e "${GREEN}✓ Secrets generated successfully!${NC}"
echo -e "${YELLOW}⚠ IMPORTANT NOTES:${NC}"
echo "  1. Keep this file secure and never commit to git"
echo "  2. Update env.tier-data with matching POSTGRES_PASSWORD"
echo "  3. Review all settings before starting services"
echo "  4. Store a backup of these secrets in a secure location"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Save output to env.tier-supabase"
echo "  2. Copy POSTGRES_PASSWORD to env.tier-data"
echo "  3. Run: make up-supabase"
