#!/usr/bin/env bash
# mcp-toolkit-connect-kimi.sh
#
# Connects Kimi Code CLI to the PMOVES Docker MCP Toolkit profile.
# Produces .kimi/mcp.json at repo root. Idempotent — safe to re-run.
#
# Usage:
#   make -C pmoves mcp-spark-connect
#   ./pmoves/scripts/mcp-toolkit-connect-kimi.sh

set -euo pipefail

PROFILE="${PROFILE:-pmoves_5090_web}"

# 1. CLI present?
if ! command -v docker >/dev/null 2>&1 || ! docker mcp version >/dev/null 2>&1; then
  echo "[mcp-connect-kimi] docker mcp CLI not available."
  echo "   Install Docker Desktop with MCP Toolkit enabled."
  exit 1
fi

# 2. Profile imported?
if ! docker mcp profile ls 2>/dev/null | awk 'NR>2 {print $1}' | grep -Fxq "$PROFILE"; then
  echo "[mcp-connect-kimi] Profile '$PROFILE' not imported on this node."
  echo "   Run: make -C pmoves mcp-toolkit-bootstrap"
  exit 2
fi

# 3. Pre-connect backup
if [ -f .kimi/mcp.json ] && [ ! -f .kimi/mcp.json.pre-toolkit-connect.bak ]; then
  cp .kimi/mcp.json .kimi/mcp.json.pre-toolkit-connect.bak
  echo "[mcp-connect-kimi] Backed up .kimi/mcp.json → .kimi/mcp.json.pre-toolkit-connect.bak"
fi

# 4. Write Kimi Code MCP config (Docker gateway stdio mode)
mkdir -p .kimi
cat > .kimi/mcp.json <<KIMI_MCP_EOF
{
  "_note": "Auto-generated by mcp-toolkit-connect-kimi.sh. Profile: ${PROFILE}. Re-run to refresh.",
  "mcpServers": {
    "pmoves-cipher": {
      "type": "sse",
      "url": "http://localhost:8105/mcp/sse"
    },
    "docker": {
      "command": "docker",
      "args": [
        "run", "--rm", "-i",
        "--mount", "type=bind,src=//var/run/docker.sock,dst=/var/run/docker.sock",
        "mcp/docker"
      ]
    },
    "pmoves-docker-gateway": {
      "_note": "Docker MCP Toolkit gateway — exposes the full ${PROFILE} profile via stdio.",
      "command": "docker",
      "args": ["mcp", "gateway", "run", "--profile", "${PROFILE}"]
    },
    "pmoves-nats-fleet": {
      "_purpose": "Cross-node NATS publish/subscribe to the fleet hub on KVM4-2.",
      "command": "uv",
      "args": [
        "--directory", "./pmoves-nats-mcp",
        "run", "python", "-m", "nats_mcp.server"
      ],
      "env": { "NATS_URL": "\${NATS_URL}" }
    }
  }
}
KIMI_MCP_EOF

echo "[mcp-connect-kimi] Connected Kimi Code to profile '$PROFILE'."
echo "   Config: .kimi/mcp.json"
echo "   Servers: pmoves-cipher (sse), docker (stdio), pmoves-docker-gateway (stdio, profile=${PROFILE}), pmoves-nats-fleet (stdio)"
