"""Workflow Templates for Cross-Repository PR Automation

Defines reusable templates for common pull request patterns across
PMOVES.AI repositories.
"""

from typing import Dict, List, Any
from dataclasses import dataclass
from enum import Enum


class PRType(Enum):
    """Types of pull requests."""
    DEPENDENCY_UPDATE = "dependency_update"
    SECURITY_PATCH = "security_patch"
    FEATURE_BACKPORT = "feature_backport"
    RELEASE_AUTOMATION = "release_automation"
    DEPENDABOT = "dependabot"
    VERSION_BUMP = "version_bump"


@dataclass
class PRWorkflowTemplate:
    """Template for automated pull request creation."""
    pr_type: PRType
    title_template: str
    body_template: str
    branch_name_template: str
    labels: List[str]
    reviewers: List[str]
    assignees: List[str]
    auto_merge: bool = False
    merge_method: str = "squash"
    draft: bool = False

    def render_title(self, **kwargs) -> str:
        """Render PR title with variables."""
        return self.title_template.format(**kwargs)

    def render_body(self, **kwargs) -> str:
        """Render PR body with variables."""
        return self.body_template.format(**kwargs)

    def render_branch_name(self, **kwargs) -> str:
        """Render branch name with variables."""
        return self.branch_name_template.format(**kwargs)


# Workflow Templates
WORKFLOW_TEMPLATES: Dict[PRType, PRWorkflowTemplate] = {
    PRType.DEPENDENCY_UPDATE: PRWorkflowTemplate(
        pr_type=PRType.DEPENDENCY_UPDATE,
        title_template="chore(deps): bump {package} from {old_version} to {new_version}",
        body_template="""\
## Dependency Update

Automated update for **{package}**.

**Previous version:** {old_version}
**New version:** {new_version}

**Affected repositories:**
{repos_list}

**Description:**
{description}

**Change summary:**
{changes}

---

🤖 Generated by PMOVES.AI Cross-Repository PR Automation
""",
        branch_name_template="chore/deps/{package}-bump-{new_version}",
        labels=["dependencies", "automated", "chore"],
        reviewers=[],
        assignees=[],
        auto_merge=False,
        merge_method="squash",
        draft=False,
    ),

    PRType.SECURITY_PATCH: PRWorkflowTemplate(
        pr_type=PRType.SECURITY_PATCH,
        title_template="security(severity): {cve_id} - {severity} severity patch for {package}",
        body_template="""\
## Security Patch

**CVE ID:** {cve_id}
**Severity:** {severity}
**CVSS Score:** {cvss_score}
**Affected Package:** {package}
**Vulnerable Versions:** {vulnerable_versions}
**Patched Versions:** {patched_versions}

**Description:**
{description}

**Impact:**
{impact}

**Affected repositories:**
{repos_list}

**Remediation:**
Update to the patched version: {patched_versions}

---

🔒 Generated by PMOVES.AI Security Automation
📅 Published: {published_date}
⚠️ Action required: Review and merge promptly
""",
        branch_name_template="security/{severity}/{cve_id}-{package}-patch",
        labels=["security", "urgent", "automated"],
        reviewers=["security-team"],
        assignees=[],
        auto_merge=False,
        merge_method="squash",
        draft=False,
    ),

    PRType.FEATURE_BACKPORT: PRWorkflowTemplate(
        pr_type=PRType.FEATURE_BACKPORT,
        title_template="feat(backport): {feature_name} backport to {target_branch}",
        body_template="""\
## Feature Backport

Backport feature **{feature_name}** to release branch **{target_branch}**.

**Original PR:** #{original_pr_number}
**Original Branch:** {original_branch}
**Original Commit:** {original_commit}

**Description:**
{description}

**Changes included:**
{changes}

**Testing:**
{testing_instructions}

**Backport checklist:**
- [ ] Code compiles without warnings
- [ ] All tests pass
- [ ] Documentation updated
- [ ] Changelog updated

---

🔄 Generated by PMOVES.AI Backport Automation
""",
        branch_name_template="feat/backport/{target_branch}/{feature_name}",
        labels=["backport", "feature", "automated"],
        reviewers=["release-managers"],
        assignees=[],
        auto_merge=False,
        merge_method="squash",
        draft=False,
    ),

    PRType.RELEASE_AUTOMATION: PRWorkflowTemplate(
        pr_type=PRType.RELEASE_AUTOMATION,
        title_template="chore(release): prepare for release {version}",
        body_template="""\
## Release Preparation

Automated release preparation for version **{version}**.

**Release type:** {release_type}
**Target date:** {release_date}
**Affected repositories:**
{repos_list}

**Changes included:**
{changes_summary}

**Changelog:**
{changelog}

**Pre-release checklist:**
- [ ] All tests pass
- [ ] Documentation updated
- [ ] Version numbers updated
- [ ] CHANGELOG.md updated
- [ ] Release notes prepared

**Post-release actions:**
- [ ] Create GitHub release
- [ ] Publish release notes
- [ ] Update deployment infrastructure
- [ ] Notify stakeholders

---

📦 Generated by PMOVES.AI Release Automation
""",
        branch_name_template="chore/release/{version}-preparation",
        labels=["release", "automated", "chore"],
        reviewers=["release-team"],
        assignees=["release-team"],
        auto_merge=False,
        merge_method="squash",
        draft=False,
    ),

    PRType.DEPENDABOT: PRWorkflowTemplate(
        pr_type=PRType.DEPENDABOT,
        title_template="chore(deps): {package} {dependency_type} update from {old_version} to {new_version}",
        body_template="""\
## Dependabot-style Update

**{package}** ({dependency_type}) update from **{old_version}** to **{new_version}**.

**Release notes:**
{release_notes}

**Changelog:**
{changelog}

**Commits:**
{commits}

**Affected repositories:**
{repos_list}

---

🤖 Generated by PMOVES.AI Dependency Automation
""",
        branch_name_template="chore/deps/{package}-{new_version}-update",
        labels=["dependencies", "automated", "dependabot"],
        reviewers=[],
        assignees=[],
        auto_merge=True,
        merge_method="squash",
        draft=False,
    ),

    PRType.VERSION_BUMP: PRWorkflowTemplate(
        pr_type=PRType.VERSION_BUMP,
        title_template="chore(version): bump {package} to {new_version}",
        body_template="""\
## Version Bump

Automated version bump for **{package}** to **{new_version}**.

**Reason:** {reason}
**Previous version:** {old_version}

**Affected files:**
{affected_files}

**Affected repositories:**
{repos_list}

---

🔢 Generated by PMOVES.AI Version Automation
""",
        branch_name_template="chore/version/{package}-bump-{new_version}",
        labels=["version", "automated", "chore"],
        reviewers=[],
        assignees=[],
        auto_merge=False,
        merge_method="squash",
        draft=False,
    ),
}


def get_template(pr_type: PRType) -> PRWorkflowTemplate:
    """Get workflow template by PR type.

    Args:
        pr_type: Type of pull request

    Returns:
        PRWorkflowTemplate for the specified type
    """
    if pr_type not in WORKFLOW_TEMPLATES:
        raise ValueError(f"Unknown PR type: {pr_type}")
    return WORKFLOW_TEMPLATES[pr_type]


def list_templates() -> List[Dict[str, Any]]:
    """List all available workflow templates.

    Returns:
        List of template metadata
    """
    return [
        {
            "type": template.pr_type.value,
            "title_example": template.render_title(
                package="example",
                old_version="1.0.0",
                new_version="2.0.0"
            ),
            "branch_example": template.render_branch_name(
                package="example",
                new_version="2.0.0"
            ),
            "labels": template.labels,
            "auto_merge": template.auto_merge,
        }
        for template in WORKFLOW_TEMPLATES.values()
    ]
