#!/usr/bin/env python3
"""Known Roads provenance checker — matrix-backed.

Replaces the wild-string `reason` check in
`.claude/hooks/damage-control/known_roads.py` with a deterministic
service-matrix lookup. The matrix lives at
`pmoves/configs/topology/docker_matrix.yaml` (regenerated by
`build_docker_matrix.py`).

Provenance rule:
  The grant reason for any Edit/Write to a protected path MUST be a
  known-road reference, not a free-text handoff name. The reference
  shape is `pr:N`, `issue:N`, `handoff:NAME.md`, `lifecycle:NAME`, or
  `session:ID`, and the matrix must list the service in the overlay
  that owns the path being edited.

Examples of passing reasons:
  - pr:3050                          (PR reference; the matrix has pr: refs)
  - issue:2974                       (issue reference)
  - handoff:notebook-mcp-build-2026-09-02.md  (handoff reference)

Examples of failing reasons:
  - free-text "I want to add a port"
  - wild strings not in any matrix reference

Usage:
    python pmoves/tools/topology/check_known_roads.py --path PATH --reason REASON --domain DOMAIN
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

MATRIX_PATH = (
    Path(__file__).resolve().parents[2] / "configs" / "topology" / "docker_matrix.yaml"
)

REFERENCE_PATTERNS = [
    re.compile(r"^pr:\d+$"),
    re.compile(r"^issue:\d+$"),
    re.compile(r"^handoff:[a-z0-9_.-]+\.md$"),
    re.compile(r"^lifecycle:[a-z0-9_.-]+$"),
    re.compile(r"^session:[a-z0-9_-]{8,}$"),
]


def _load_matrix() -> dict:
    if not MATRIX_PATH.exists():
        return {}
    import yaml
    with MATRIX_PATH.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def _matrix_owns_path(matrix: dict, path: str) -> list:
    """Match a path to the services that own it.

    Single lookup rule: each service has a `paths` set under each of
    its overlays (Source A) or under its declared `guard_paths` list
    (Source C, submodule-resident services). The gate passes iff the
    lookup path is a member of one of those sets (after path normalization).

    No fuzzy substring matches, no directory-shape inference, no
    overlay-file-prefix checks. Exact-set membership only — the
    operator's design rule: matrix is the canonical source, gate is
    exact. If the gate refuses a path the operator expects to pass,
    the right fix is to add the path to the matrix's `guard_paths`,
    not to soften the gate.
    """
    path = path.replace("\\", "/")
    if path.startswith("./"):
        path = path[2:]

    owners: list = []
    for svc in matrix.get("services", []):
        # Source A: paths under each overlay
        for _ov_name, ov_path in svc.get("paths", {}).items():
            normalized = ov_path.replace("\\", "/")
            if normalized == path or path.startswith(normalized):
                owners.append(svc["name"])
                break
        else:
            # Source C: explicit guard_paths set (added by Source C in build)
            if path in svc.get("guard_paths", set()):
                owners.append(svc["name"])
    return owners


def _reason_has_valid_reference(reason: str) -> bool:
    for tok in reason.split():
        for pat in REFERENCE_PATTERNS:
            if pat.match(tok):
                return True
    for pat in REFERENCE_PATTERNS:
        if pat.match(reason.strip()):
            return True
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--path", required=True)
    parser.add_argument("--reason", required=True)
    parser.add_argument("--domain", required=True,
                        help="compose|dockerfile|schema|topic|secrets")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    matrix = _load_matrix()
    if not matrix:
        if args.json:
            print(json.dumps({"ok": False, "reason": "matrix not loaded"}))
        else:
            print(f"known-roads: FAIL - matrix not loaded at {MATRIX_PATH}")
        return 2

    owners = _matrix_owns_path(matrix, args.path)
    if not owners:
        if args.json:
            print(json.dumps({"ok": False, "reason": "no matrix owner for path",
                               "path": args.path}))
        else:
            print(f"known-roads: FAIL - no matrix owner for {args.path}")
        return 1

    if args.domain not in ("compose", "dockerfile", "schema", "topic", "secrets"):
        if args.json:
            print(json.dumps({"ok": False, "reason": "unknown domain"}))
        else:
            print(f"known-roads: FAIL - unknown domain {args.domain!r}")
        return 1

    if not _reason_has_valid_reference(args.reason):
        if args.json:
            print(json.dumps({"ok": False, "reason": "no valid reference token in reason",
                               "got": args.reason}))
        else:
            print(f"known-roads: FAIL - no valid reference token in reason {args.reason!r}")
        return 1

    if args.json:
        print(json.dumps({"ok": True, "owners": owners, "domain": args.domain,
                           "reason": args.reason}))
    else:
        print(f"known-roads: PASS - owners={owners} domain={args.domain} reason={args.reason!r}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
