REM AUTO-GENERATED by pmoves/tools/pmoves_launcher_generator.py v1.0.0
REM Source of truth: pmoves/configs/cli_tools.yaml + pmoves/config/agent_registry.yaml
REM Regenerate:    python pmoves/tools/pmoves_launcher_generator.py --out deploy/provision
REM Drift check:   python pmoves/tools/pmoves_launcher_generator.py --check
REM DO NOT EDIT BY HAND -- your changes will be overwritten by the next regen.
REM If you need a per-CLI customisation, add it to launcher_overrides.yaml
REM (pmoves/configs/launcher_overrides.yaml), not to this file.
REM crush-pmoves-crush.cmd -- per-node identity pin (Windows wrapper).
REM Sets PMOVES_NODE_ID=z890 via the .ps1 then delegates to it.
@echo off
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0crush-pmoves-crush.ps1" %*
