# AUTO-GENERATED by pmoves/tools/pmoves_launcher_generator.py v1.0.0
# Source of truth: pmoves/configs/cli_tools.yaml + pmoves/config/agent_registry.yaml
# Regenerate:    python pmoves/tools/pmoves_launcher_generator.py --out deploy/provision
# Drift check:   python pmoves/tools/pmoves_launcher_generator.py --check
# DO NOT EDIT BY HAND -- your changes will be overwritten by the next regen.
# If you need a per-CLI customisation, add it to launcher_overrides.yaml
# (pmoves/configs/launcher_overrides.yaml), not to this file.
# crush-pmoves-glm52.ps1 -- per-node identity pin
# ===========================================================================
# Sets $env:PMOVES_NODE_ID='pmoves-b850' and calls crush-pmoves.ps1
# so the session binds to the `crush_glm52` identity from
# pmoves/config/agent_registry.yaml.
#
# Source of truth: agent_registry.yaml entry `crush_glm52`
#   signature: crush
#   node_affinity: [pmoves-b850, ...]
# ===========================================================================
$ErrorActionPreference = 'Stop'
$env:PMOVES_NODE_ID = 'pmoves-b850'
$ps1 = Join-Path (Split-Path -Parent $PSScriptRoot) 'crush-pmoves.ps1'
& $ps1 @args
