# AUTO-GENERATED by pmoves/tools/pmoves_launcher_generator.py v1.0.0
# Source of truth: pmoves/configs/cli_tools.yaml + pmoves/config/agent_registry.yaml
# Regenerate:    python pmoves/tools/pmoves_launcher_generator.py --out deploy/provision
# Drift check:   python pmoves/tools/pmoves_launcher_generator.py --check
# DO NOT EDIT BY HAND -- your changes will be overwritten by the next regen.
# If you need a per-CLI customisation, add it to launcher_overrides.yaml
# (pmoves/configs/launcher_overrides.yaml), not to this file.
# install-kimi-pmoves.ps1
# ---------------------------------------------------------------------------
# Makes `kimi-pmoves` a bare command in PowerShell on THIS node,
# so you can type `kimi-pmoves` from any directory instead of the
# full launcher path.  Mirrors install-claude-pmoves-command.ps1 exactly.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File deploy\provision\install-kimi-pmoves.ps1
#
# Per-node pin functions (set $env:PMOVES_NODE_ID before calling the launcher):
#   kimi-pmoves-knuckles ($env:PMOVES_NODE_ID=pmoves-b850)
# ---------------------------------------------------------------------------
param([switch]$Force)

$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$cmd = Join-Path $repoRoot "deploy\provision\kimi-pmoves.cmd"
if (-not (Test-Path $cmd)) { throw "launcher not found: $cmd (is this the pmoves repo?)" }

# Refuse linked worktrees (mirror install-claude-pmoves-command.ps1:32-51).
$gitPath = Join-Path $repoRoot ".git"
if ((Test-Path $gitPath) -and -not (Test-Path $gitPath -PathType Container)) {
    Write-Host ""
    Write-Host "REFUSING: this is a linked git worktree, not the canonical checkout." -ForegroundColor Red
    if (-not $Force) { exit 2 }
    Write-Host "  -Force given: installing from a worktree anyway." -ForegroundColor Yellow
}
Write-Host "  resolved repo root: $repoRoot"

$begin = "# >>> pmoves kimi-pmoves >>>"
$end   = "# <<< pmoves kimi-pmoves <<<"
$block = @"
$begin
# Auto-generated by install-kimi-pmoves.ps1.
# Purpose: Kimi Code with PMOVES context files + Cipher/Agent Zero MCP
function kimi-pmoves { & "$cmd" @args }
function kimi-pmoves-knuckles {
    $env:PMOVES_NODE_ID = 'pmoves-b850'
    & kimi-pmoves @args
    Remove-Item Env:PMOVES_NODE_ID -ErrorAction SilentlyContinue
}
$end
"@

$docs = [Environment]::GetFolderPath('MyDocuments')
$targets = @(
    (Join-Path $docs "WindowsPowerShell\profile.ps1"),
    (Join-Path $docs "PowerShell\profile.ps1")
) | Select-Object -Unique

foreach ($profilePath in $targets) {
    $dir = Split-Path -Parent $profilePath
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    $content = ""
    if (Test-Path $profilePath) { $content = Get-Content -Raw -Path $profilePath -ErrorAction SilentlyContinue }
    if ($null -eq $content) { $content = "" }
    $pattern = [regex]::Escape($begin) + "[\s\S]*?" + [regex]::Escape($end)
    $content = [regex]::Replace($content, $pattern, "").TrimEnd()
    if ($content.Length -gt 0) { $content += "`r`n`r`n" }
    $content += $block + "`r`n"
    Set-Content -Path $profilePath -Value $content -Encoding UTF8
    Write-Host "  profile: $profilePath"
}

# PATH shim (mirrors install-claude-pmoves-command.ps1:88-101).
$shimDir = Join-Path $env:LOCALAPPDATA 'Microsoft\WindowsApps'
if (Test-Path $shimDir) {
    $shim = Join-Path $shimDir 'kimi-pmoves.cmd'
    $q = [char]34
    $lines = @('@echo off', ('call ' + $q + $cmd + $q + ' %*'))
    Set-Content -Path $shim -Value $lines -Encoding ASCII
    Write-Host "  path shim: $shim"
} else {
    Write-Warning "  $shimDir not present - PATH shim skipped (profile function still installed)."
}

Write-Host ''
Write-Host "Installed 'kimi-pmoves' -> $cmd"
Write-Host "Also installed: 'kimi-pmoves-knuckles'"

Write-Host 'Works in any NEW shell (PATH shim). In an existing session, open a new shell.'
