#!/usr/bin/env pwsh
# install-claude-pmoves-command.ps1
# ---------------------------------------------------------------------------
# Makes `claude-pmoves` a bare command in PowerShell on THIS node, so you can
# type `claude-pmoves` from any directory instead of the full launcher path.
#
# Portable: run once per node with the pmoves repo installed:
#   powershell -ExecutionPolicy Bypass -File deploy\provision\install-claude-pmoves-command.ps1
# It resolves the repo root from its own location (no hard-coded paths) and
# writes an idempotent function block into BOTH the Windows PowerShell (5.1) and
# PowerShell 7 CurrentUserAllHosts profiles, so the command works whichever
# edition you launch. Re-run after moving the repo to update the path.
# ---------------------------------------------------------------------------
param([switch]$Force)

$ErrorActionPreference = "Stop"

# Repo root = two levels up from deploy/provision/
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$cmd = Join-Path $repoRoot "deploy\provision\claude-pmoves.cmd"
if (-not (Test-Path $cmd)) { throw "launcher not found: $cmd (is this the pmoves repo?)" }

# The root is resolved from THIS SCRIPT'S location, so running the copy inside a
# linked worktree binds `claude-pmoves` to a checkout that gets deleted. That is
# not hypothetical: it happened on 2026-08-30, and the shim pointed at a
# throwaway worktree until it was re-run from the canonical root. The command
# would still have resolved and the launcher would still have started -- env
# loading from a tree that no longer exists.
#
# In a linked worktree `.git` is a FILE (a gitdir pointer); in the canonical
# checkout it is a directory. That is the whole test.
$gitPath = Join-Path $repoRoot ".git"
if ((Test-Path $gitPath) -and -not (Test-Path $gitPath -PathType Container)) {
    # Write-Host, not Write-Error: $ErrorActionPreference is "Stop" above, which
    # makes Write-Error TERMINATING -- it throws before reaching `exit 2`, so the
    # refusal returned 1 and -Force could never be honoured. Diagnosed by running
    # both paths and reading the real exit code, which needs the call NOT to be
    # piped: `$?` after `| head` is head's status, not PowerShell's.
    Write-Host ""
    Write-Host "REFUSING: this is a linked git worktree, not the canonical checkout." -ForegroundColor Red
    Write-Host "  resolved root : $repoRoot"
    Write-Host "  .git          : a file (gitdir pointer), so this tree is disposable"
    Write-Host ""
    Write-Host "Installing from here would point ``claude-pmoves`` at a checkout that may"
    Write-Host "be removed, and the failure would be SILENT -- the command resolves, the"
    Write-Host "launcher runs, and env loads from a tree that is gone."
    Write-Host ""
    Write-Host "Run it from the canonical repo instead, or pass -Force to override."
    if (-not $Force) { exit 2 }
    Write-Host "  -Force given: installing from a worktree anyway." -ForegroundColor Yellow
}

Write-Host "  resolved repo root: $repoRoot"

$begin = "# >>> pmoves claude-pmoves >>>"
$end   = "# <<< pmoves claude-pmoves <<<"
$block = @"
$begin
# Auto-generated by deploy/provision/install-claude-pmoves-command.ps1.
# Launches Claude Code with pmoves/env.shared loaded so every MCP tool resolves.
# Re-run the installer to update the path after moving the repo.
function claude-pmoves { & "$cmd" @args }
$end
"@

# Target both editions' all-hosts profiles so the command works in WinPS 5.1 and pwsh 7.
$docs = [Environment]::GetFolderPath('MyDocuments')
$targets = @(
    (Join-Path $docs "WindowsPowerShell\profile.ps1"),
    (Join-Path $docs "PowerShell\profile.ps1")
) | Select-Object -Unique

foreach ($profilePath in $targets) {
    $dir = Split-Path -Parent $profilePath
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    $content = ""
    if (Test-Path $profilePath) { $content = Get-Content -Raw -Path $profilePath -ErrorAction SilentlyContinue }
    if ($null -eq $content) { $content = "" }
    # Strip any prior managed block, then append the fresh one.
    $pattern = [regex]::Escape($begin) + "[\s\S]*?" + [regex]::Escape($end)
    $content = [regex]::Replace($content, $pattern, "").TrimEnd()
    if ($content.Length -gt 0) { $content += "`r`n`r`n" }
    $content += $block + "`r`n"
    Set-Content -Path $profilePath -Value $content -Encoding UTF8
    Write-Host "  profile: $profilePath"
}

# PATH shim - bulletproof across every shell. A profile function does NOT load in
# Windows PowerShell 5.1 when the execution policy is Restricted/AllSigned, so the
# primary mechanism is a .cmd on PATH. %LOCALAPPDATA%\Microsoft\WindowsApps is
# user-writable and on PATH by default on Win10/11.
$shimDir = Join-Path $env:LOCALAPPDATA 'Microsoft\WindowsApps'
if (Test-Path $shimDir) {
    $shim = Join-Path $shimDir 'claude-pmoves.cmd'
    $q = [char]34
    $lines = @('@echo off', ('call ' + $q + $cmd + $q + ' %*'))
    Set-Content -Path $shim -Value $lines -Encoding ASCII
    Write-Host "  path shim: $shim"
} else {
    Write-Warning "  $shimDir not present - PATH shim skipped (profile function still installed)."
}

Write-Host ''
Write-Host "Installed 'claude-pmoves' -> $cmd"
Write-Host 'Works in any NEW shell (PATH shim). In an existing session, open a new shell.'
