<#
install-pmoves-cipher-command.ps1
# ---------------------------------------------------------------------------
# Makes `pmoves-cipher` a bare command in PowerShell on THIS node, so you can
# type `pmoves-cipher <subcommand>` from any directory instead of the full
# launcher path.  Also installs the per-subcommand alias functions the
# registry describes (none yet).
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File deploy\provision\install-pmoves-cipher-command.ps1
#   powershell -ExecutionPolicy Bypass -File deploy\provision\install-pmoves-cipher-command.ps1 -Force
#
# Mirror of install-claude-pmoves-command.ps1 / install-crush-pmoves-command.ps1.
# ---------------------------------------------------------------------------
param([switch]$Force)

$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$cmd = Join-Path $repoRoot "deploy\provision\pmoves-cipher.cmd"
if (-not (Test-Path $cmd)) { throw "launcher not found: $cmd (is this the pmoves repo?)" }

# Refuse linked worktrees (mirror install-claude-pmoves-command.ps1:32-51).
$gitPath = Join-Path $repoRoot ".git"
if ((Test-Path $gitPath) -and -not (Test-Path $gitPath -PathType Container)) {
    Write-Host ""
    Write-Host "REFUSING: this is a linked git worktree, not the canonical checkout." -ForegroundColor Red
    if (-not $Force) { exit 2 }
    Write-Host "  -Force given: installing from a worktree anyway." -ForegroundColor Yellow
}
Write-Host "  resolved repo root: $repoRoot"

$begin = "# >>> pmoves cipher >>>"
$end   = "# <<< pmoves cipher <<<"
$block = @"
$begin
# Auto-generated by install-pmoves-cipher-command.ps1.
# Purpose: surface pmoves-cipher (wraps chit_* tools + cipher API /health).
function pmoves-cipher { & "$cmd" @args }
$end
"@

$docs = [Environment]::GetFolderPath('MyDocuments')
$targets = @(
    (Join-Path $docs "WindowsPowerShell\profile.ps1"),
    (Join-Path $docs "PowerShell\profile.ps1")
) | Select-Object -Unique

foreach ($profilePath in $targets) {
    $dir = Split-Path -Parent $profilePath
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    $content = ""
    if (Test-Path $profilePath) { $content = Get-Content -Raw -Path $profilePath -ErrorAction SilentlyContinue }
    if ($null -eq $content) { $content = "" }
    $pattern = [regex]::Escape($begin) + "[\s\S]*?" + [regex]::Escape($end)
    $content = [regex]::Replace($content, $pattern, "").TrimEnd()
    if ($content.Length -gt 0) { $content += "`r`n`r`n" }
    $content += $block + "`r`n"
    Set-Content -Path $profilePath -Value $content -Encoding UTF8
    Write-Host "  profile: $profilePath"
}

# PATH shim (mirror install-claude-pmoves-command.ps1:88-101).
$shimDir = Join-Path $env:LOCALAPPDATA 'Microsoft\WindowsApps'
if (Test-Path $shimDir) {
    $shim = Join-Path $shimDir 'pmoves-cipher.cmd'
    $q = [char]34
    $lines = @('@echo off', ('call ' + $q + $cmd + $q + ' %*'))
    Set-Content -Path $shim -Value $lines -Encoding ASCII
    Write-Host "  path shim: $shim"
} else {
    Write-Warning "  $shimDir not present - PATH shim skipped (profile function still installed)."
}

Write-Host ''
Write-Host "Installed 'pmoves-cipher' -> $cmd"
Write-Host 'Works in any NEW shell (PATH shim). In an existing session, open a new shell.'
