#!/usr/bin/env bash
# install-claude-pmoves-command.sh
# ---------------------------------------------------------------------------
# Makes `claude-pmoves` a bare command in bash/zsh on THIS node, so you can type
# `claude-pmoves` from any directory instead of the full launcher path.
#
# Portable: run once per node with the pmoves repo installed —
#   bash deploy/provision/install-claude-pmoves-command.sh
# It resolves the repo root from its own location (no hard-coded paths) and
# writes an idempotent function into ~/.bashrc AND ~/.zshrc (whichever exist /
# apply), so the command works in either shell. Re-run after moving the repo.
# ---------------------------------------------------------------------------
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
launcher="$repo_root/deploy/provision/claude-pmoves.sh"
[ -f "$launcher" ] || { echo "launcher not found: $launcher (is this the pmoves repo?)" >&2; exit 1; }

begin="# >>> pmoves claude-pmoves >>>"
end="# <<< pmoves claude-pmoves <<<"

install_into() {
  local rc="$1"
  touch "$rc"
  # Strip any prior managed block (inclusive of the markers).
  local tmp; tmp="$(mktemp)"
  awk -v b="$begin" -v e="$end" '
    $0==b {skip=1}
    skip!=1 {print}
    $0==e {skip=0}
  ' "$rc" > "$tmp" && mv "$tmp" "$rc"
  {
    printf '\n%s\n' "$begin"
    printf '%s\n' "# Auto-generated by deploy/provision/install-claude-pmoves-command.sh."
    printf '%s\n' "# Launches Claude Code with pmoves/env.shared loaded so every MCP tool resolves."
    printf 'claude-pmoves() { "%s" "$@"; }\n' "$launcher"
    printf '%s\n' "$end"
  } >> "$rc"
  echo "  updated: $rc"
}

# Resolve the rc file for the user's LOGIN shell so a fresh (rc-less) shell of
# that shell still gets the function — e.g. a zsh account with a legacy ~/.bashrc
# but no ~/.zshrc, where updating only the existing file would leave zsh sessions
# unable to run claude-pmoves despite the installer reporting success (Codex #1991 P2).
case "$(basename "${SHELL:-bash}")" in
  zsh) active_rc="$HOME/.zshrc" ;;
  *)   active_rc="$HOME/.bashrc" ;;
esac

# Update every rc file that already exists (so both shells stay in sync)...
installed=0
for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
  if [ -f "$rc" ]; then install_into "$rc"; installed=1; fi
done
# ...then guarantee the login shell's rc gets it. The -f guard skips this when the
# loop already updated an existing rc, and only fires to CREATE the login shell's
# rc when it is absent — which is exactly the gap the old code missed.
if [ ! -f "$active_rc" ]; then install_into "$active_rc"; installed=1; fi

echo ""
echo "Installed 'claude-pmoves' -> $launcher"
echo "Run:  source ~/.bashrc   (or open a new shell)   then just type:  claude-pmoves"
