#!/usr/bin/env bash
# install-pmoves-cipher-command.sh
# ---------------------------------------------------------------------------
# Makes `pmoves-cipher` a bare command in bash/zsh on THIS node, so you can
# type `pmoves-cipher <subcommand>` from any directory instead of the full
# launcher path.  Also installs any per-subcommand alias functions the
# registry describes (none yet -- the wrapper is intentionally thin).
#
# Usage:
#   bash deploy/provision/install-pmoves-cipher-command.sh
#   bash deploy/provision/install-pmoves-cipher-command.sh --force   # from a worktree
#
# The launcher trio (deploy/provision/pmoves-cipher.{sh,ps1,cmd}) stays
# hand-written in this repo -- it is small, stable, and the existence of
# an installer lets the operator audit the .sh changes without diffing a
# generated file.  Mirror of install-claude-pmoves-command.sh / install-
# crush-pmoves-command.sh.
#
# NOTE: this file was originally emitted through a Python f-string/str.format
# template, which doubled every literal brace (install_into() {{, ${1:-},
# ...). PR #3093 review caught it: bash -n failed at the install_into()
# definition. All braces are single again; keep it that way -- if this file
# is ever regenerated from a template, un-double the braces before commit.
# ---------------------------------------------------------------------------
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
launcher="$repo_root/deploy/provision/pmoves-cipher.sh"
[ -f "$launcher" ] || { echo "launcher not found: $launcher" >&2; exit 1; }

# Refuse linked worktrees (mirror install-claude-pmoves-command.sh:30-42):
# a worktree .git is a FILE (gitdir pointer); the canonical checkout has a
# DIRECTORY.  Installing from a worktree points the command at a checkout
# that may be deleted.
if [ -e "$repo_root/.git" ] && [ ! -d "$repo_root/.git" ]; then
  if [ "${1:-}" != "--force" ]; then
    echo "REFUSING: $repo_root is a linked git worktree, not the canonical checkout." >&2
    echo "  pass --force to override." >&2
    exit 2
  fi
  echo "  --force given: installing from a worktree anyway." >&2
fi
echo "  resolved repo root: $repo_root"

begin="# >>> pmoves cipher >>>"
end="# <<< pmoves cipher <<<"

fn_body=$(cat <<EOF
$begin
# Auto-generated by install-pmoves-cipher-command.sh.
# Purpose: surface pmoves-cipher (wraps chit_* tools + cipher API /health).
pmoves-cipher() { "$launcher" "\$@"; }
$end
EOF
)

install_into() {
  local rc="$1"
  touch "$rc"
  local tmp; tmp="$(mktemp)"
  awk -v b="$begin" -v e="$end" '
    $0==b {skip=1}
    skip!=1 {print}
    $0==e {skip=0}
  ' "$rc" > "$tmp" && mv "$tmp" "$rc"
  printf '\n%s\n' "$fn_body" >> "$rc"
  echo "  updated: $rc"
}

case "$(basename "${SHELL:-bash}")" in
  zsh) active_rc="$HOME/.zshrc" ;;
  *)   active_rc="$HOME/.bashrc" ;;
esac

installed=0
for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
  if [ -f "$rc" ]; then install_into "$rc"; installed=1; fi
done
if [ ! -f "$active_rc" ]; then install_into "$active_rc"; installed=1; fi

# PATH symlink (mirror install-claude-pmoves-command.sh:88-96)
bindir="$HOME/.local/bin"
mkdir -p "$bindir"
ln -sf "$launcher" "$bindir/pmoves-cipher"
echo "  path symlink: $bindir/pmoves-cipher"
case ":${PATH}:" in
  *":$bindir:"*) : ;;
  *) echo "  NOTE: $bindir is not on PATH -- add it, or use the rc function above." ;;
esac

echo ""
echo "Installed 'pmoves-cipher' -> $launcher"
echo "Run:  source ~/.bashrc   (or open a new shell)   then just type:  pmoves-cipher health"
