# AUTO-GENERATED by pmoves/tools/pmoves_launcher_generator.py v1.0.0
# Source of truth: pmoves/configs/cli_tools.yaml + pmoves/config/agent_registry.yaml
# Regenerate:    python pmoves/tools/pmoves_launcher_generator.py --out deploy/provision
# Drift check:   python pmoves/tools/pmoves_launcher_generator.py --check
# DO NOT EDIT BY HAND -- your changes will be overwritten by the next regen.
# If you need a per-CLI customisation, add it to launcher_overrides.yaml
# (pmoves/configs/launcher_overrides.yaml), not to this file.
# install-pmoves-mini-pmoves-command.sh
# ---------------------------------------------------------------------------
# Makes `pmoves-mini` a bare command in bash/zsh on THIS node, so
# you can type `pmoves-mini` from any directory instead of the full
# launcher path.  Also installs any per-node pin functions the registry
# describes for the `pmoves-mini` family.
#
# Usage:
#   bash deploy/provision/install-pmoves-mini.sh
#
# Per-node pin functions (set PMOVES_NODE_ID before calling the launcher):
#   (none -- this CLI is not bound to per-node identities in agent_registry.yaml)
# ---------------------------------------------------------------------------
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
launcher="$repo_root/deploy/provision/pmoves-mini.sh"
[ -f "$launcher" ] || { echo "launcher not found: $launcher" >&2; exit 1; }

# Refuse linked worktrees (same guard as install-claude-pmoves-command.sh:30-42):
# a worktree .git is a FILE (gitdir pointer); the canonical checkout has a
# DIRECTORY.  Installing from a worktree points the command at a checkout
# that may be deleted.
if [ -e "$repo_root/.git" ] && [ ! -d "$repo_root/.git" ]; then
  if [ "${1:-}" != "--force" ]; then
    echo "REFUSING: $repo_root is a linked git worktree, not the canonical checkout." >&2
    echo "  pass --force to override." >&2
    exit 2
  fi
  echo "  --force given: installing from a worktree anyway." >&2
fi
echo "  resolved repo root: $repo_root"

begin="# >>> pmoves pmoves-mini >>>"
end="# <<< pmoves pmoves-mini <<<"

# Function body emitted into the user's rc file.  The per-node pin entries
# follow it (they each call the canonical function).
fn_body=$(cat <<EOF
$begin
# Auto-generated by install-pmoves-mini.sh.
# Purpose: PMOVES mini CLI — profiles, models, automations, crush setup
pmoves-mini() { "$launcher" "$@"; }

$end
EOF
)

install_into() {
  local rc="$1"
  touch "$rc"
  local tmp; tmp="$(mktemp)"
  awk -v b="$begin" -v e="$end" '
    $0==b {skip=1}
    skip!=1 {print}
    $0==e {skip=0}
  ' "$rc" > "$tmp" && mv "$tmp" "$rc"
  printf '\n%s\n' "$fn_body" >> "$rc"
  echo "  updated: $rc"
}

# Resolve the login shell's rc first (zsh vs bash) so a fresh rc-less shell
# of the active shell still gets the function.
case "$(basename "${SHELL:-bash}")" in
  zsh) active_rc="$HOME/.zshrc" ;;
  *)   active_rc="$HOME/.bashrc" ;;
esac

installed=0
for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
  if [ -f "$rc" ]; then install_into "$rc"; installed=1; fi
done
if [ ! -f "$active_rc" ]; then install_into "$active_rc"; installed=1; fi

# PATH symlink (mirrors install-claude-pmoves-command.sh:88-96)
bindir="$HOME/.local/bin"
mkdir -p "$bindir"
ln -sf "$launcher" "$bindir/pmoves-mini"
echo "  path symlink: $bindir/pmoves-mini"
case ":${PATH}:" in
  *":$bindir:"*) : ;;
  *) echo "  NOTE: $bindir is not on PATH -- add it, or use the rc function above." ;;
esac

echo ""
echo "Installed 'pmoves-mini' -> $launcher"
echo "Run:  source ~/.bashrc   (or open a new shell)   then just type:  pmoves-mini"
