#!/usr/bin/env pwsh
# install-claude-pmoves-command.ps1
# ---------------------------------------------------------------------------
# Makes `claude-pmoves` a bare command in PowerShell on THIS node, so you can
# type `claude-pmoves` from any directory instead of the full launcher path.
#
# Portable: run once per node with the pmoves repo installed:
#   powershell -ExecutionPolicy Bypass -File deploy\provision\install-claude-pmoves-command.ps1
# It resolves the repo root from its own location (no hard-coded paths) and
# writes an idempotent function block into BOTH the Windows PowerShell (5.1) and
# PowerShell 7 CurrentUserAllHosts profiles, so the command works whichever
# edition you launch. Re-run after moving the repo to update the path.
# ---------------------------------------------------------------------------
$ErrorActionPreference = "Stop"

# Repo root = two levels up from deploy/provision/
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$cmd = Join-Path $repoRoot "deploy\provision\claude-pmoves.cmd"
if (-not (Test-Path $cmd)) { throw "launcher not found: $cmd (is this the pmoves repo?)" }

$begin = "# >>> pmoves claude-pmoves >>>"
$end   = "# <<< pmoves claude-pmoves <<<"
$block = @"
$begin
# Auto-generated by deploy/provision/install-claude-pmoves-command.ps1.
# Launches Claude Code with pmoves/env.shared loaded so every MCP tool resolves.
# Re-run the installer to update the path after moving the repo.
function claude-pmoves { & "$cmd" @args }
$end
"@

# Target both editions' all-hosts profiles so the command works in WinPS 5.1 and pwsh 7.
$docs = [Environment]::GetFolderPath('MyDocuments')
$targets = @(
    (Join-Path $docs "WindowsPowerShell\profile.ps1"),
    (Join-Path $docs "PowerShell\profile.ps1")
) | Select-Object -Unique

foreach ($profilePath in $targets) {
    $dir = Split-Path -Parent $profilePath
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    $content = ""
    if (Test-Path $profilePath) { $content = Get-Content -Raw -Path $profilePath -ErrorAction SilentlyContinue }
    if ($null -eq $content) { $content = "" }
    # Strip any prior managed block, then append the fresh one.
    $pattern = [regex]::Escape($begin) + "[\s\S]*?" + [regex]::Escape($end)
    $content = [regex]::Replace($content, $pattern, "").TrimEnd()
    if ($content.Length -gt 0) { $content += "`r`n`r`n" }
    $content += $block + "`r`n"
    Set-Content -Path $profilePath -Value $content -Encoding UTF8
    Write-Host "  profile: $profilePath"
}

# PATH shim - bulletproof across every shell. A profile function does NOT load in
# Windows PowerShell 5.1 when the execution policy is Restricted/AllSigned, so the
# primary mechanism is a .cmd on PATH. %LOCALAPPDATA%\Microsoft\WindowsApps is
# user-writable and on PATH by default on Win10/11.
$shimDir = Join-Path $env:LOCALAPPDATA 'Microsoft\WindowsApps'
if (Test-Path $shimDir) {
    $shim = Join-Path $shimDir 'claude-pmoves.cmd'
    $q = [char]34
    $lines = @('@echo off', ('call ' + $q + $cmd + $q + ' %*'))
    Set-Content -Path $shim -Value $lines -Encoding ASCII
    Write-Host "  path shim: $shim"
} else {
    Write-Warning "  $shimDir not present - PATH shim skipped (profile function still installed)."
}

Write-Host ''
Write-Host "Installed 'claude-pmoves' -> $cmd"
Write-Host 'Works in any NEW shell (PATH shim). In an existing session, open a new shell.'
