# AUTO-GENERATED by pmoves/tools/pmoves_launcher_generator.py v1.0.0
# Source of truth: pmoves/configs/cli_tools.yaml + pmoves/config/agent_registry.yaml
# Regenerate:    python pmoves/tools/pmoves_launcher_generator.py --out deploy/provision
# Drift check:   python pmoves/tools/pmoves_launcher_generator.py --check
# DO NOT EDIT BY HAND -- your changes will be overwritten by the next regen.
# If you need a per-CLI customisation, add it to launcher_overrides.yaml
# (pmoves/configs/launcher_overrides.yaml), not to this file.
# kilo-pmoves.ps1 -- launch `kilo-pmoves` with pmoves/env.shared loaded
# ===========================================================================
# Auto-generated PowerShell twin of kilo-pmoves.sh. Same shell
# pattern as the hand-written claude-pmoves.ps1 / crush-pmoves.ps1:
#   1. Resolve repo root from $PSScriptRoot
#   2. Source env.shared via two-pass assign-then-expand
#   3. Apply per-CLI blocklist + name bridges
#   4. Hand off to the binary with any passed args
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File deploy\provision\kilo-pmoves.ps1 [args]
#   .\kilo-pmoves.cmd                     # Windows Explorer double-click
#   install-kilo-pmoves-pmoves-command.ps1 ; kilo-pmoves     # profile function
#
# Purpose: KiloCode/OpenCode with per-node configs (pmoves/configs/claws/opencode-<node>.json)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$envf = if ($env:PMOVES_ENV_SHARED) { $env:PMOVES_ENV_SHARED } else { Join-Path $root 'pmoves\env.shared' }

if (Test-Path $envf) {
    # Per-CLI blocklist (mirrors DEFAULT_BLOCKLIST_BY_TOOL in pmoves_launcher_generator.py).
    # These control the kilo-pmoves SDK itself, not MCP creds -- sourcing them would
    # clobber session state or force API billing.
    $blocklist = @(
        # (no blocklist entries -- this CLI sources every var from env.shared)
    ) -replace '\*', '.*'

    # Pass 1: read KEY=VALUE verbatim into an ordered map, skipping blocklisted keys.
    $vars = [ordered]@{}
    foreach ($line in Get-Content -LiteralPath $envf) {
        if ($line -match '^\s*#') { continue }
        if ($line -match '^\s*$') { continue }
        $eq = $line.IndexOf('=')
        if ($eq -lt 1) { continue }
        $key = $line.Substring(0, $eq).Trim()
        $blocked = $false
        foreach ($pat in $blocklist) { if ($key -match "^$pat$") { $blocked = $true; break } }
        if ($blocked) { continue }
        $val = ($line.Substring($eq + 1) -replace '\r$', '')
        if ($key) { $vars[$key] = $val }
    }
    # Pass 2: expand ${VAR} and ${VAR:-default} against the map (bounded iteration).
    for ($pass = 0; $pass -lt 5; $pass++) {
        $changed = $false
        foreach ($k in @($vars.Keys)) {
            $curKey = $k
            $resolved = [regex]::Replace($vars[$k], '\\$\\{([A-Za-z_][A-Za-z0-9_]*)(?::-([^}]*))?\\}', {
                param($m)
                $name = $m.Groups[1].Value
                $repl = $null
                if ($name -ne $curKey) {
                    if ($vars.Contains($name) -and $vars[$name] -ne '' -and $vars[$name] -notmatch '\\$\\{') {
                        $repl = $vars[$name]
                    } else {
                        $envv = [Environment]::GetEnvironmentVariable($name)
                        if ($envv) { $repl = $envv }
                    }
                }
                if ($null -ne $repl) { $repl }
                elseif ($m.Groups[2].Success) { $m.Groups[2].Value }
                else { '' }
            })
            if ($resolved -ne $vars[$k]) { $vars[$k] = $resolved; $changed = $true }
        }
        if (-not $changed) { break }
    }
    $n = 0
    foreach ($k in $vars.Keys) { [Environment]::SetEnvironmentVariable($k, $vars[$k], 'Process'); $n++ }
    Write-Host "[kilo-pmoves] loaded $n vars from $envf"
    $script:launcherSession = "kilo-pmoves.ps1 ($n vars)"
} else {
    Write-Warning "[kilo-pmoves] $envf not found -- MCP creds may be missing."
    $script:launcherSession = "kilo-pmoves.ps1 (env file NOT FOUND)"
}

[Environment]::SetEnvironmentVariable('PMOVES_LAUNCHER_SESSION', $script:launcherSession, 'Process')

# --- NAME BRIDGES (mirror bash twin) ----------------------------------------
# (no name bridges for this CLI)

# --- LAUNCH ---------------------------------------------------------------
& kilo-pmoves @args
