# AUTO-GENERATED by pmoves/tools/pmoves_launcher_generator.py v1.0.0
# Source of truth: pmoves/configs/cli_tools.yaml + pmoves/config/agent_registry.yaml
# Regenerate:    python pmoves/tools/pmoves_launcher_generator.py --out deploy/provision
# Drift check:   python pmoves/tools/pmoves_launcher_generator.py --check
# DO NOT EDIT BY HAND -- your changes will be overwritten by the next regen.
# If you need a per-CLI customisation, add it to launcher_overrides.yaml
# (pmoves/configs/launcher_overrides.yaml), not to this file.
# kilo-pmoves-kilocode_glm.ps1 -- per-node identity pin
# ===========================================================================
# Sets $env:PMOVES_NODE_ID='5090' and calls kilo-pmoves.ps1
# so the session binds to the `kilocode_glm` identity from
# pmoves/config/agent_registry.yaml.
#
# Source of truth: agent_registry.yaml entry `kilocode_glm`
#   signature: kilocode
#   node_affinity: [5090, ...]
# ===========================================================================
$ErrorActionPreference = 'Stop'
$env:PMOVES_NODE_ID = '5090'
$ps1 = Join-Path (Split-Path -Parent $PSScriptRoot) 'kilo-pmoves.ps1'
& $ps1 @args
