# AUTO-GENERATED by pmoves/tools/pmoves_launcher_generator.py v1.0.0
# Source of truth: pmoves/configs/cli_tools.yaml + pmoves/config/agent_registry.yaml
# Regenerate:    python pmoves/tools/pmoves_launcher_generator.py --out deploy/provision
# Drift check:   python pmoves/tools/pmoves_launcher_generator.py --check
# DO NOT EDIT BY HAND -- your changes will be overwritten by the next regen.
# If you need a per-CLI customisation, add it to launcher_overrides.yaml
# (pmoves/configs/launcher_overrides.yaml), not to this file.
# kilo-pmoves-kilocode_glm.sh -- per-node identity pin
# ===========================================================================
# Sets PMOVES_NODE_ID=5090 and execs kilo-pmoves.sh so the
# session binds to the `kilocode_glm` identity from
# pmoves/config/agent_registry.yaml.
#
# Source of truth: agent_registry.yaml entry `kilocode_glm`
#   signature: kilocode
#   node_affinity: [5090, ...]
#   description: VS Code-native GLM-5-Turbo delivery agent via KiloCode. Blueprint-first implementation, MCP-integrated, DARKXSIDE witness.
#
# Wezterm sets per-pane env via `set-pane-environment-variables`; this is
# the PMOVES equivalent for a CLI surface.  The identity pin is the LAST
# thing set before exec, so a parent env that already exports
# PMOVES_NODE_ID is overridden -- the registry is the canonical binding.
# ===========================================================================
set -u
export PMOVES_NODE_ID="5090"
exec "$(dirname "${BASH_SOURCE[0]:-$0}")/kilo-pmoves.sh" "$@"
