# AUTO-GENERATED by pmoves/tools/pmoves_launcher_generator.py v1.0.0
# Source of truth: pmoves/configs/cli_tools.yaml + pmoves/config/agent_registry.yaml
# Regenerate:    python pmoves/tools/pmoves_launcher_generator.py --out deploy/provision
# Drift check:   python pmoves/tools/pmoves_launcher_generator.py --check
# DO NOT EDIT BY HAND -- your changes will be overwritten by the next regen.
# If you need a per-CLI customisation, add it to launcher_overrides.yaml
# (pmoves/configs/launcher_overrides.yaml), not to this file.
# kimi-pmoves-knuckles.sh -- per-node identity pin
# ===========================================================================
# Sets PMOVES_NODE_ID=pmoves-b850 and execs kimi-pmoves.sh so the
# session binds to the `kimi_knuckles` identity from
# pmoves/config/agent_registry.yaml.
#
# Source of truth: agent_registry.yaml entry `kimi_knuckles`
#   signature: knuckles-kimi
#   node_affinity: [pmoves-b850, ...]
#   description: B850/Knuckles node Kimi Code CLI identity (PMOVES-KIMI-KNUCKLES-B850). Same affinity posture as claude_b850 -- a preference, not an exclusive claim. First harness wired to a per-node cipher_agent_id.
#
# Wezterm sets per-pane env via `set-pane-environment-variables`; this is
# the PMOVES equivalent for a CLI surface.  The identity pin is the LAST
# thing set before exec, so a parent env that already exports
# PMOVES_NODE_ID is overridden -- the registry is the canonical binding.
# ===========================================================================
set -u
export PMOVES_NODE_ID="pmoves-b850"
exec "$(dirname "${BASH_SOURCE[0]:-$0}")/kimi-pmoves.sh" "$@"
