# AUTO-GENERATED by pmoves/tools/pmoves_launcher_generator.py v1.0.0
# Source of truth: pmoves/configs/cli_tools.yaml + pmoves/config/agent_registry.yaml
# Regenerate:    python pmoves/tools/pmoves_launcher_generator.py --out deploy/provision
# Drift check:   python pmoves/tools/pmoves_launcher_generator.py --check
# DO NOT EDIT BY HAND -- your changes will be overwritten by the next regen.
# If you need a per-CLI customisation, add it to launcher_overrides.yaml
# (pmoves/configs/launcher_overrides.yaml), not to this file.
# kimi-pmoves.sh -- launch `kimi` with pmoves/env.shared loaded
# ===========================================================================
# Auto-generated wrapper for kimi-pmoves. Mirrors the hand-written
# claude-pmoves.sh / crush-pmoves.sh SHELL pattern (resolve repo root via
# symlink-walk, source env.shared, exec the binary) so every pmoves_wrapper
# has the same Windows + POSIX entry surface and the same env-loaded
# preconditions.  The hand-written launchers carry SDK-fixed FAIL-CLOSED
# MCP roster logic this template does not reproduce -- that is by design.
#
# Usage:
#   bash deploy/provision/kimi-pmoves.sh        [args...]
#   install-kimi-pmoves-pmoves-command.sh && kimi-pmoves         # rc function
#   kimi-pmoves.cmd                              # Windows Explorer double-click
#
# Purpose: Kimi Code with PMOVES context files + Cipher/Agent Zero MCP
#
# Override env.shared path with PMOVES_ENV_SHARED.
set -u

# --- REPO-ROOT RESOLUTION (mirror claude-pmoves.sh) -------------------------
# See test-launcher-root-resolution.sh for why this walk must stay byte-
# identical across every launcher that carries it: an installer symlink at
# ~/.local/bin/<name> would otherwise make ROOT=$HOME and env.shared miss.
SELF="${BASH_SOURCE[0]:-$0}"
while [ -L "$SELF" ]; do
  link_dir="$(CDPATH='' cd -P -- "$(dirname -- "$SELF")" && pwd)"
  SELF="$(readlink -- "$SELF")"
  case "$SELF" in /*) ;; *) SELF="$link_dir/$SELF" ;; esac
done
SELF_DIR="$(CDPATH='' cd -P -- "$(dirname -- "$SELF")" && pwd)"
if [ -n "${PMOVES_LAUNCHER_ROOT:-}" ]; then
  ROOT="$PMOVES_LAUNCHER_ROOT"
else
  ROOT="$(CDPATH='' cd -P -- "$SELF_DIR/../.." && pwd)" || ROOT=""
fi
if [ ! -f "${ROOT:-/nonexistent}/pmoves/Makefile" ]; then
  if [ -n "${PMOVES_ENV_SHARED:-}" ] && [ -f "$PMOVES_ENV_SHARED" ]; then
    echo "[kimi-pmoves] WARN: repo root not found (${ROOT:-<unresolved>}); using PMOVES_ENV_SHARED." >&2
  else
    echo "[kimi-pmoves] ERROR: no pmoves/Makefile under repo root: ${ROOT:-<unresolved>}" >&2
    echo "[kimi-pmoves]        (resolved from: $SELF)" >&2
    exit 1
  fi
fi

# --- MAVIS SDK ENV STRIP ---------------------------------------------------
# The Mavis SDK's `env` block in `~/.claude/settings.json` injects
# ANTHROPIC_BASE_URL, ANTHROPIC_AUTH_TOKEN, ANTHROPIC_MODEL, MCP_TIMEOUT,
# API_TIMEOUT_MS, CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC, ... into every
# Claude Code session's process env.  That env block is inherited by the
# shell that runs this launcher, and would otherwise be inherited by the
# launched `kimi` -- overriding the operator's own CLI settings
# (their API endpoint, their model picker).
#
# The strip checks each Mavis SDK var against `kimi`'s NEEDS list
# (defined in pmoves/scripts/mavis_sdk_env.sh alongside this comment):
#   * keeps the ones `kimi` consumes
#   * preserves the others under PMOVES_MAVIS_SDK_<NAME> for inspection
#   * unsets the originals
#   * emits one WARN line summarizing what was caught
#
# Sourced AFTER repo-root resolution (helper file is repo-relative) and
# BEFORE env.shared loading (the env.shared reader below has a parallel
# blocklist for env.shared itself; the two layers cover the SHELL env and
# env.shared independently).
# ---------------------------------------------------------------------------
if [ -f "$ROOT/pmoves/scripts/mavis_sdk_env.sh" ]; then
  # shellcheck source=../../pmoves/scripts/mavis_sdk_env.sh
  . "$ROOT/pmoves/scripts/mavis_sdk_env.sh"
  mavis_sdk_strip_env_for "kimi"
else
  echo "[kimi-pmoves] WARN: mavis_sdk_env.sh not found at $ROOT/pmoves/scripts/ -- Mavis SDK env may bleed into the launched session." >&2
fi

# --- ENV.SHARED LOADING (mirror claude-pmoves.sh :: lines 72-127) -----------
# env.shared is Docker Compose env_file format: unquoted values + ALIAS lines
# like `SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}`.  Two hazards:
#   1. We can't `source` it raw -- unquoted values break `. file`.
#   2. We must NOT export values verbatim -- that leaks the literal string
#      "${SERVICE_ROLE_KEY}" into MCP headers and starts them unauthorized.
# Build a sanitized assignment file (single-quote plain values; pass ${...}-
# bearing lines through for shell expansion), then source it auto-export.
ENVF="${PMOVES_ENV_SHARED:-$ROOT/pmoves/env.shared}"
if [ -f "$ENVF" ]; then
  blocklist='^$NEVER_MATCH$'
  set +H 2>/dev/null || true
  tmpf=$(mktemp)
  n=0
  while IFS= read -r line || [ -n "$line" ]; do
    line="${line%$'\r'}"
    case "$line" in ''|\#*) continue;; esac
    case "$line" in *=*) : ;; *) continue;; esac
    key=${line%%=*}
    val=${line#*=}
    key=$(printf '%s' "$key" | tr -d '[:space:]')
    [ -z "$key" ] && continue
    if [[ "$key" =~ $blocklist ]]; then continue; fi
    val="${val#"${val%%[![:space:]]*}"}"
    # Two-pass expansion: pass literal `${...}` lines through verbatim
    # so the shell expands them on `. "$tmpf"`.  Otherwise single-quote
    # so the literal value lands in the env (avoid the placeholder leak
    # Codex #1987 P2 caught).  Mirror pmoves/scripts/with-env.sh.
    #
    # Single-quote escape routes through awk octal (\047) -- never nest
    # `\''` literals (loses count in f-string backslash escapes; see
    # PR conversation 2026-09-16 + pmoves_launcher_generator_LEARNINGS.md).
    if printf '%s' "$val" | grep -qE '[$]{'; then
      printf '%s=%s\n' "$key" "$val" >> "$tmpf"
    else
      esc=$(printf '%s' "$val" | awk '{ gsub(/\047/, "\047\\\047\047"); print }')
      printf "%s='%s'\n" "$key" "$esc" >> "$tmpf"
    fi
    n=$((n+1))
  done < "$ENVF"
  set -a; set +u
  . "$tmpf"
  set +a; set -u
  rm -f "$tmpf"
  set -H 2>/dev/null || true
  echo "[kimi-pmoves] loaded $n vars from $ENVF" >&2
else
  echo "[kimi-pmoves] WARN: $ENVF not found -- MCP creds may be missing." >&2
  echo "[kimi-pmoves]       run: make -C pmoves ensure-env-shared" >&2
fi

# --- NAME BRIDGES (operator-facing alias to upstream SDK name) -------------
# (no name bridges for this CLI)

# --- LAUNCH ---------------------------------------------------------------
export PMOVES_LAUNCHER_SESSION="kimi-pmoves.sh"
exec kimi "$@"
