# pmoves/design/generate.py
"""DL-1 design token generator. Reads pmoves/config/agent_signatures.yaml
(registry owned by the W1 theme lane — 4090-claude PRs #1065/#1101; do NOT
modify the registry schema here) + base/theme JSON, emits CSS + TS tokens."""
from __future__ import annotations
import json, pathlib, re
DESIGN = pathlib.Path(__file__).resolve().parent
REPO = DESIGN.parents[1]
REGISTRY = REPO / "pmoves" / "config" / "agent_signatures.yaml"

# Reject values that would break out of a CSS declaration or the generated TS
# string map. The registry is trusted, but a typo (stray ; } " or newline) would
# otherwise produce broken build/ output that still commits clean — a silent
# failure. Single quotes/commas/parens are allowed (font stacks, rgba()).
_UNSAFE = re.compile(r'[;{}"\n\r]')

def load_registry() -> dict:
    import yaml
    data = yaml.safe_load(REGISTRY.read_text(encoding="utf-8")) or {}
    return data.get("signatures", {})

def _agent(reg: dict, agent_id: str) -> dict:
    if agent_id not in reg:
        raise KeyError(f"theme references unknown agent id: {agent_id!r}")
    return reg[agent_id]

def _field(agent: dict, field: str, agent_id: str) -> str:
    if field not in agent:
        raise KeyError(f"agent {agent_id!r} missing required theme field {field!r}")
    return agent[field]

def _safe(key: str, val: str) -> str:
    if not isinstance(val, str) or _UNSAFE.search(val):
        raise ValueError(f"unsafe/invalid token value for {key!r}: {val!r}")
    return val

def resolve_theme(theme: dict, reg: dict) -> dict:
    base = json.loads((DESIGN / "tokens.base.json").read_text(encoding="utf-8"))
    v: dict[str, str] = {}
    # structural base
    for k, val in base["color"].items():
        v[f"--pm-{k}"] = val
    v["--pm-radius"] = base["radius"]["lg"]
    for k, val in base["space"].items():
        v[f"--pm-space-{k}"] = val
    v["--pm-font-display"] = base["font"]["display"]
    v["--pm-font-body"] = base["font"]["body"]
    v["--pm-font-mono"] = base["font"]["mono"]
    # registry-sourced accents
    acc = theme["accents"]
    primary = _agent(reg, acc["primary"]); secondary = _agent(reg, acc["secondary"]); sig = _agent(reg, acc["signature"])
    v["--pm-accent"] = _field(primary, "color", acc["primary"])
    v["--pm-accent-soft"] = _field(primary, "accent", acc["primary"])
    v["--pm-accent-2"] = _field(secondary, "color", acc["secondary"])
    v["--pm-accent-2-soft"] = _field(secondary, "accent", acc["secondary"])
    v["--pm-signature"] = _field(sig, "color", acc["signature"])
    v["--pm-signature-soft"] = _field(sig, "accent", acc["signature"])  # AA-safe small-text crimson
    # theme overrides last
    for k, val in theme.get("overrides", {}).get("color", {}).items():
        v[f"--pm-{k}"] = val
    # guard every emitted value against CSS/TS injection (silent-failure trap)
    return {k: _safe(k, val) for k, val in v.items()}

DEFAULT_THEME = "pmoves-armor"

def emit_css(theme: dict, vars_: dict) -> str:
    name = theme["name"]
    sel = f'[data-theme="{name}"]'
    if name == DEFAULT_THEME:
        sel += ", :root:not([data-theme])"
    lines = [f"/* generated by pmoves/design/generate.py — do not edit */",
             f":root{sel} {{"]
    for k in sorted(vars_):
        lines.append(f"  {k}: {vars_[k]};")
    lines.append("}")
    return "\n".join(lines) + "\n"

def emit_ts(themes: dict) -> str:
    body = json.dumps(themes, indent=2, sort_keys=True)
    return ("// generated by pmoves/design/generate.py — do not edit\n"
            f"export const themes = {body} as const;\n"
            "export type ThemeName = keyof typeof themes;\n")

def main() -> int:
    reg = load_registry()
    out = DESIGN / "build"; out.mkdir(exist_ok=True)
    resolved = {}
    for tf in sorted((DESIGN / "themes").glob("*.json")):
        theme = json.loads(tf.read_text(encoding="utf-8"))
        vars_ = resolve_theme(theme, reg)
        resolved[theme["name"]] = vars_
        (out / f"tokens.{theme['name']}.css").write_text(emit_css(theme, vars_), encoding="utf-8")
    (out / "tokens.ts").write_text(emit_ts(resolved), encoding="utf-8")

    # Consumer copies: docker build contexts that cannot reach pmoves/design
    # (e.g. pmoves/ui builds with context ./ui) get a generated, committed
    # copy of every theme. Single source stays the registry + themes/.
    ui_out = DESIGN.parent / "ui" / "app" / "pm-tokens.generated.css"
    if ui_out.parent.is_dir():
        blocks = ["/* generated by pmoves/design/generate.py — do not edit.\n"
                  "   Regenerate: make -C pmoves design-tokens */\n"]
        for tf in sorted((DESIGN / "themes").glob("*.json")):
            theme = json.loads(tf.read_text(encoding="utf-8"))
            blocks.append(emit_css(theme, resolved[theme["name"]]))
        ui_out.write_text("\n".join(blocks), encoding="utf-8")
        print(f"emitted consumer copy -> {ui_out}")

    print(f"generated {len(resolved)} themes -> {out}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
