-- PMOVES.YT docs catalog persistence for yt-dlp metadata.
-- Stores docs snapshots used by UI tiles and agent tooling.

create schema if not exists pmoves_core;

create table if not exists pmoves_core.tool_docs (
  tool_doc_id bigint generated by default as identity primary key,
  tool text not null,
  version text not null default 'unknown',
  doc_type text not null,
  content jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tool_docs_tool_version_type_key unique (tool, version, doc_type)
);

create index if not exists idx_tool_docs_tool on pmoves_core.tool_docs (tool);
create index if not exists idx_tool_docs_updated_at on pmoves_core.tool_docs (updated_at desc);

create or replace function pmoves_core.set_tool_docs_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_tool_docs_updated_at on pmoves_core.tool_docs;
create trigger trg_tool_docs_updated_at
before update on pmoves_core.tool_docs
for each row
execute function pmoves_core.set_tool_docs_updated_at();

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    grant usage on schema pmoves_core to anon;
    grant select on pmoves_core.tool_docs to anon;
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    grant usage on schema pmoves_core to authenticated;
    grant select on pmoves_core.tool_docs to authenticated;
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    grant usage on schema pmoves_core to service_role;
    grant select, insert, update, delete on pmoves_core.tool_docs to service_role;
  end if;
  if exists (select 1 from pg_roles where rolname = 'postgrest_anon') then
    grant usage on schema pmoves_core to postgrest_anon;
    grant select on pmoves_core.tool_docs to postgrest_anon;
  end if;
  if exists (select 1 from pg_roles where rolname = 'postgrest_auth_user') then
    grant usage on schema pmoves_core to postgrest_auth_user;
    grant select on pmoves_core.tool_docs to postgrest_auth_user;
  end if;
end;
$$;

