#!/usr/bin/env python3
import argparse
import base64
import platform
import re
import secrets
import string
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
_REPO_ROOT = str(ROOT.parent)
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from pmoves.tools._secrets_common import (
    PLACEHOLDER_VALUES,
    is_placeholder as _is_blank_or_placeholder,
    normalize_env_value as _normalize_env_value,
)

ENV_DEFAULT = ROOT / "env.shared"
ENV_GEN_DEFAULT = ROOT / ".env.generated"

DEFAULTS = {
    # Storage / presign (auto-generated by _ensure_minio_credentials)
    "MINIO_ACCESS_KEY": "",
    "MINIO_SECRET_KEY": "",
    # Search (will be strengthened below if too short)
    "MEILI_MASTER_KEY": "master_key",
    # Vector search (Qdrant API key for inter-service authentication)
    "QDRANT__API_KEY": "",
    # Geometry graph (compose reads NEO4J_AUTH; we set URL, user, and generate password if missing)
    "NEO4J_URL": "bolt://neo4j:7687",
    "NEO4J_USER": "neo4j",
    # Invidious companion (keys will be strengthened below)
    "INVIDIOUS_HMAC_KEY": "localhack",
    "INVIDIOUS_COMPANION_KEY": "localhack",
    # Vector search (Qwen3-4b 2560d embeddings)
    "QDRANT_COLLECTION": "pmoves_chunks_qwen3",
    # TensorZero embedding model (direct model name, not prefixed)
    "TENSORZERO_EMBED_MODEL": "qwen3_embedding_4b_local",
    "EMBEDDING_BACKEND": "tensorzero",
    # REST bases
    "SUPA_REST_URL": "http://host.docker.internal:54321/rest/v1",
    "SUPA_REST_INTERNAL_URL": "http://host.docker.internal:54321/rest/v1",
    # Presign/Render webhook secrets (demo defaults; replace in production)
    "PRESIGN_SHARED_SECRET": "change_me",
    "RENDER_WEBHOOK_SHARED_SECRET": "change_me",
    # RustDesk self-hosted relay (KVM2) — fetched from server, not generated
    "RUSTDESK_RELAY_HOST": "",
    "RUSTDESK_PUBLIC_KEY": "",
}

# Values that have been superseded by newer defaults.
# When brand-defaults sees an existing value matching a superseded entry,
# it replaces it with the new default from DEFAULTS or the registry.
# This enables config migrations without manual env file edits.
SUPERSEDED_VALUES: dict[str, str] = {
    # Qwen3-4b embedding migration: 384d → 2560d collection
    "pmoves_chunks": "pmoves_chunks_qwen3",
    # Legacy sentence-transformer model (replaced by TensorZero routing)
    "all-MiniLM-L6-v2": "all-MiniLM-L6-v2",  # keep as-is, TZ overrides at runtime
    # TZ embed model: prefixed format → direct model name
    "tensorzero::embedding_model_name::embed_default": "qwen3_embedding_4b_local",
    "tensorzero::embedding_model_name::qwen3_embedding_4b_local": "qwen3_embedding_4b_local",
}


def _strong_random(n_bytes: int) -> str:
    return secrets.token_urlsafe(n_bytes)


def _rand_exact_len(n_chars: int) -> str:
    s = _strong_random(max(12, n_chars))
    if len(s) < n_chars:
        s = (s * ((n_chars // len(s)) + 1))[:n_chars]
    return s[:n_chars]


def _rand_alnum(n_chars: int) -> str:
    alphabet = string.ascii_lowercase + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(n_chars))


def _get_kv(text: str, key: str) -> str:
    m = re.search(rf"^\s*{re.escape(key)}\s*=(.*)$", text, re.M)
    raw = (m.group(1).strip() if m else "").strip()
    return _normalize_env_value(raw)


def _set_kv(text: str, key: str, value: str) -> str:
    # Dotenv-safety guard: env.shared is Docker Compose env_file format. Values
    # containing embedded newlines or carriage returns break parsing on the
    # NEXT line (the parser reads the next line as a new KEY=value where the
    # wrapped content has invalid chars in the "key" position). Reject at
    # write-time rather than letting a corrupted value reach compose.
    # See feedback_env_shared_not_bash_extract_pattern.md for the line-513
    # incident that motivated this guard.
    if "\n" in value or "\r" in value:
        raise ValueError(
            f"Refusing to write {key} with embedded newline/CR: "
            f"breaks Docker Compose env_file parsing. "
            f"Strip newlines from the generator or use a single-line "
            f"alternative (e.g., secrets.token_urlsafe instead of "
            f"base64.b64encode with MIME-style wrapping)."
        )
    pat = rf"^(\s*{re.escape(key)}\s*=).*$"
    if re.search(pat, text, re.M):
        return re.sub(pat, lambda m: m.group(1) + value, text, flags=re.M)
    return text + f"\n{key}={value}\n"


def _first_real(text: str, keys: list[str]) -> str:
    for key in keys:
        value = _get_kv(text, key)
        if not _is_blank_or_placeholder(value):
            return value
    return ""


def _ensure_notebook_and_surreal_credentials(text: str) -> str:
    notebook_secret = _first_real(text, ["OPEN_NOTEBOOK_PASSWORD", "OPEN_NOTEBOOK_API_TOKEN"])
    if not notebook_secret:
        notebook_secret = "pm_nb_" + _strong_random(16)
    text = _set_kv(text, "OPEN_NOTEBOOK_PASSWORD", notebook_secret)
    text = _set_kv(text, "OPEN_NOTEBOOK_API_TOKEN", notebook_secret)

    surreal_user = _first_real(text, ["OPEN_NOTEBOOK_SURREAL_USER", "SURREAL_USER"])
    if not surreal_user:
        surreal_user = "pm_surreal_" + _rand_alnum(8)
    surreal_pass = _first_real(text, ["OPEN_NOTEBOOK_SURREAL_PASS", "SURREAL_PASS"])
    if not surreal_pass:
        surreal_pass = "pm_sr_" + _strong_random(16)

    text = _set_kv(text, "SURREAL_USER", surreal_user)
    text = _set_kv(text, "SURREAL_PASS", surreal_pass)
    text = _set_kv(text, "OPEN_NOTEBOOK_SURREAL_USER", surreal_user)
    text = _set_kv(text, "OPEN_NOTEBOOK_SURREAL_PASS", surreal_pass)
    return text


def _ensure_channel_monitor_google_alias(text: str) -> str:
    """Mirror GOOGLE_CLIENT_ID/SECRET into the CHANNEL_MONITOR_GOOGLE_* namespace.

    The sync-secrets-local workflow exports GH secrets under generic names
    (GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET) but the channel-monitor service
    and the Phase 9Q.2 yt-cookies pipeline both consume the same OAuth client
    via the prefixed CHANNEL_MONITOR_GOOGLE_CLIENT_ID/SECRET names. This
    function copies values across when:
      * the prefixed key is missing or still a placeholder
      * the generic key has a real value

    Direction is one-way (generic → prefixed). If the operator has set the
    prefixed key explicitly, it is left alone.
    """
    pairs = (
        ("GOOGLE_CLIENT_ID", "CHANNEL_MONITOR_GOOGLE_CLIENT_ID"),
        ("GOOGLE_CLIENT_SECRET", "CHANNEL_MONITOR_GOOGLE_CLIENT_SECRET"),
    )
    for source, target in pairs:
        target_val = _get_kv(text, target)
        if not _is_blank_or_placeholder(target_val):
            continue
        source_val = _get_kv(text, source)
        if _is_blank_or_placeholder(source_val):
            continue
        text = _set_kv(text, target, source_val)
    return text


# NOTE: SUPABASE_SERVICE_KEY (Archon's alias for SERVICE_ROLE_KEY) is intentionally
# NOT seeded here. This function runs in `ensure-env-shared`, BEFORE
# `secrets-runtime-hydrate`. Writing the standardized key here — while it may still
# be the template demo JWT or a stale local value — produces a non-placeholder that
# hydration then refuses to overwrite (without FORCE=1), so Archon boots on a stale
# key and 401s (Codex #1984 P1). Ownership belongs to runtime_secrets_hydrate.py,
# which selects the freshest canonical source (the live Supabase container's
# SERVICE_ROLE_KEY). SUPABASE_URL is likewise not seeded globally — the Makefile
# injects it scoped to the Archon-native compose (see up-archon-native).


def _ensure_integration_credentials(text: str) -> str:
    """Auto-generate credentials for Firefly III, n8n, and Wger if missing."""
    # Firefly III APP_KEY: Laravel requires 'base64:' + 32 random bytes base64-encoded
    firefly_key = _get_kv(text, "FIREFLY_APP_KEY")
    if _is_blank_or_placeholder(firefly_key) or firefly_key == "base64:CHANGE_ME":
        raw = secrets.token_bytes(32)
        firefly_key = "base64:" + base64.b64encode(raw).decode("ascii")
        text = _set_kv(text, "FIREFLY_APP_KEY", firefly_key)

    # n8n encryption key: 32-byte urlsafe token for workflow credential encryption.
    n8n_enc = _get_kv(text, "N8N_ENCRYPTION_KEY")
    if _is_blank_or_placeholder(n8n_enc):
        text = _set_kv(text, "N8N_ENCRYPTION_KEY", _strong_random(32))

    # n8n runners auth token: shared secret for the runners container
    n8n_runners = _get_kv(text, "N8N_RUNNERS_AUTH_TOKEN")
    if _is_blank_or_placeholder(n8n_runners):
        text = _set_kv(text, "N8N_RUNNERS_AUTH_TOKEN", _strong_random(24))

    # n8n owner password: auto-generate and persist in env.shared so it survives
    # env file regeneration. This is the password for the n8n owner account created
    # by `make n8n-bootstrap`. Previously only written to .env.local which was
    # easily lost, causing 401 mismatches on subsequent bootstraps.
    # N8N_API_KEY is NOT generated here (requires a live n8n instance) — it's
    # minted by bootstrap_n8n_api.py and written back to env.shared after creation.
    n8n_owner_pw = _get_kv(text, "N8N_OWNER_PASSWORD")
    if _is_blank_or_placeholder(n8n_owner_pw):
        text = _set_kv(text, "N8N_OWNER_PASSWORD", _strong_random(24))

    # Wger database password: PostgreSQL password for the wger database
    wger_db_pass = _get_kv(text, "WGER_DB_PASSWORD")
    if _is_blank_or_placeholder(wger_db_pass):
        try:
            # Use URL-safe base64 to avoid '/' characters that break DATABASE_URL DSN parsing
            wger_db_pass = secrets.token_urlsafe(24)
            text = _set_kv(text, "WGER_DB_PASSWORD", wger_db_pass)
        except Exception as e:
            print(f"ERROR: Failed to generate WGER_DB_PASSWORD: {e}", file=sys.stderr)
            print("Generate manually: python -c 'import secrets; print(secrets.token_urlsafe(24))'", file=sys.stderr)
            sys.exit(1)

    # Wger Django secret key: Django SECRET_KEY for cryptographic signing.
    # Django docs accept any random string; their default get_random_secret_key()
    # uses [a-zA-Z0-9!@#$%^&*(-_=+)] but `+` and `=` break dotenv parsing when
    # the file is consumed via Docker Compose env_file. Use url-safe base64 to
    # match the rest of brand_defaults (PMOVES dotenv-safety principle — see
    # feedback_env_shared_not_bash_extract_pattern.md).
    # token_urlsafe(48) ≈ 64 chars from [A-Za-z0-9_-], safe for env.shared.
    wger_secret = _get_kv(text, "WGER_SECRET_KEY")
    if _is_blank_or_placeholder(wger_secret):
        try:
            wger_secret = secrets.token_urlsafe(48)
            text = _set_kv(text, "WGER_SECRET_KEY", wger_secret)
        except Exception as e:
            print(f"ERROR: Failed to generate WGER_SECRET_KEY: {e}", file=sys.stderr)
            print("Generate manually: python -c 'import secrets; print(secrets.token_urlsafe(48))'", file=sys.stderr)
            sys.exit(1)

    # Wger admin password: Admin account password for the wger web interface.
    # Django accepts any string; url-safe base64 keeps the value safe for both
    # dotenv parsing and Django admin login (no special-char escaping needed
    # at the browser login form).
    wger_admin_pass = _get_kv(text, "WGER_ADMIN_PASSWORD")
    if _is_blank_or_placeholder(wger_admin_pass):
        try:
            wger_admin_pass = secrets.token_urlsafe(16)
            text = _set_kv(text, "WGER_ADMIN_PASSWORD", wger_admin_pass)
        except Exception as e:
            print(f"ERROR: Failed to generate WGER_ADMIN_PASSWORD: {e}", file=sys.stderr)
            print("Generate manually: python -c 'import secrets; print(secrets.token_urlsafe(16))'", file=sys.stderr)
            sys.exit(1)

    # Wger API token: Django REST Framework tokens must be created via the
    # admin UI — random tokens are rejected.  Set a sentinel so operators
    # know to generate one from http://localhost:8000/api/v2/token.
    wger_token = _get_kv(text, "WGER_API_TOKEN")
    if _is_blank_or_placeholder(wger_token):
        text = _set_kv(text, "WGER_API_TOKEN", "GENERATE_FROM_WGER_UI")

    # Supabase DB password alignment: POSTGRES_PASSWORD and SUPABASE_DB_PASSWORD
    # must always match — the DB container reads SUPABASE_DB_PASSWORD, but GoTrue
    # falls back through POSTGRES_PASSWORD. Divergence causes auth failures.
    supa_db_pass = _get_kv(text, "SUPABASE_DB_PASSWORD")
    pg_pass = _get_kv(text, "POSTGRES_PASSWORD")
    if supa_db_pass and not pg_pass:
        text = _set_kv(text, "POSTGRES_PASSWORD", supa_db_pass)
    elif pg_pass and not supa_db_pass:
        text = _set_kv(text, "SUPABASE_DB_PASSWORD", pg_pass)
    elif supa_db_pass and pg_pass and supa_db_pass != pg_pass:
        # SUPABASE_DB_PASSWORD is canonical (DB container reads it directly)
        text = _set_kv(text, "POSTGRES_PASSWORD", supa_db_pass)

    return text


def _ensure_identity_defaults(text: str) -> str:
    """Seed operator identity and branding. Safe defaults for new deployers;
    DARKXSIDE values are set via env.shared, not hardcoded here."""
    # OPERATOR_EMAIL: top-level identity cascading to Supabase + n8n
    op_email = _get_kv(text, "OPERATOR_EMAIL")
    if not op_email:
        text = _set_kv(text, "OPERATOR_EMAIL", "")

    # BRAND_NAME: display name for UI surfaces and notifications
    brand = _get_kv(text, "BRAND_NAME")
    if not brand:
        text = _set_kv(text, "BRAND_NAME", "PMOVES.AI")

    # SUPPORT_EMAIL: user-facing support contact (optional)
    support = _get_kv(text, "SUPPORT_EMAIL")
    if not support:
        text = _set_kv(text, "SUPPORT_EMAIL", "")

    # Cascade: if OPERATOR_EMAIL is set, seed downstream services that still
    # have placeholder emails.  This avoids requiring the operator to set each
    # service email individually.
    op_email = _get_kv(text, "OPERATOR_EMAIL")
    if op_email and op_email not in PLACEHOLDER_VALUES and "${" not in op_email:
        boot_email = _get_kv(text, "SUPABASE_BOOT_USER_EMAIL")
        if not boot_email or boot_email in PLACEHOLDER_VALUES or boot_email == "you@example.com" or "${" in boot_email:
            text = _set_kv(text, "SUPABASE_BOOT_USER_EMAIL", op_email)

        n8n_email = _get_kv(text, "N8N_OWNER_EMAIL")
        if not n8n_email or n8n_email in PLACEHOLDER_VALUES or "${" in n8n_email:
            text = _set_kv(text, "N8N_OWNER_EMAIL", op_email)

        wger_email = _get_kv(text, "WGER_BRAND_ADMIN_EMAIL")
        if not wger_email or wger_email in PLACEHOLDER_VALUES or wger_email == "admin@example.com" or "${" in wger_email:
            text = _set_kv(text, "WGER_BRAND_ADMIN_EMAIL", op_email)

    return text



def _ensure_tailscale_defaults(text: str) -> str:
    """Auto-populate Tailscale hostname and tags. Auth key is manual (console-only)."""
    # Hostname: derive from machine hostname if not set
    ts_hostname = _get_kv(text, "TAILSCALE_HOSTNAME")
    if not ts_hostname:
        node = platform.node().lower().replace(" ", "-")
        text = _set_kv(text, "TAILSCALE_HOSTNAME", f"pmoves-{node}")

    # Tags: default to tag:pmoves for mesh ACLs
    ts_tags = _get_kv(text, "TAILSCALE_TAGS")
    if not ts_tags:
        text = _set_kv(text, "TAILSCALE_TAGS", "tag:pmoves")

    # SSH: enable by default
    ts_ssh = _get_kv(text, "TAILSCALE_SSH")
    if not ts_ssh:
        text = _set_kv(text, "TAILSCALE_SSH", "true")

    # Validate auth key format if present (warn, don't overwrite)
    ts_authkey = _get_kv(text, "TAILSCALE_AUTHKEY")
    if ts_authkey and not ts_authkey.startswith("tskey-auth-"):
        print(
            "WARNING: TAILSCALE_AUTHKEY does not start with 'tskey-auth-' — "
            "may be invalid. Get a key from https://login.tailscale.com/admin/settings/keys",
            file=sys.stderr,
        )

    return text


def _ensure_agent_zero_defaults(text: str) -> str:
    """Seed Agent Zero orchestrator defaults: MCP secret, JetStream, model routing."""
    # MCP_CLIENT_SECRET: auto-generate if missing (32-byte urlsafe)
    mcp_secret = _get_kv(text, "MCP_CLIENT_SECRET")
    if _is_blank_or_placeholder(mcp_secret):
        text = _set_kv(text, "MCP_CLIENT_SECRET", _strong_random(32))

    # AGENTZERO_JETSTREAM: default to true for reliable NATS delivery
    jetstream = _get_kv(text, "AGENTZERO_JETSTREAM")
    if not jetstream:
        text = _set_kv(text, "AGENTZERO_JETSTREAM", "true")

    # A0_SET_chat_model: default to TensorZero chat route
    chat_model = _get_kv(text, "A0_SET_chat_model")
    if not chat_model:
        text = _set_kv(text, "A0_SET_chat_model", "tensorzero::model_name::chat_default")

    # A0_SET_utility_model: default to TensorZero utility route
    util_model = _get_kv(text, "A0_SET_utility_model")
    if not util_model:
        text = _set_kv(text, "A0_SET_utility_model", "tensorzero::model_name::util_default")

    # A0_SET_embedding_model: default to TensorZero embedding route
    embed_model = _get_kv(text, "A0_SET_embedding_model")
    if not embed_model:
        text = _set_kv(text, "A0_SET_embedding_model", "tensorzero::embedding_model_name::embed_default")

    # AGENT_ZERO_EVENTS_TOKEN: shared token for n8n approval-poller x-agent-token header.
    # Auto-generate if blank so n8n flows can authenticate to Agent Zero out-of-the-box.
    events_token = _get_kv(text, "AGENT_ZERO_EVENTS_TOKEN")
    if _is_blank_or_placeholder(events_token):
        text = _set_kv(text, "AGENT_ZERO_EVENTS_TOKEN", _strong_random(32))

    # A0_SELF_UPDATE_REMOTE_URL: pin the in-app self-updater at the PMOVES fork.
    # Without this, Agent Zero's webUI "Update" button defaults to upstream
    # agent0ai/agent-zero and its post-fetch `git clean -ffd` wipes the PMOVES
    # custom modules. Upserting here (not just env.shared.example) is what reaches
    # EXISTING installs — ensure_env_shared only copies the example when env.shared
    # is missing, so the example default alone never lands on already-provisioned
    # nodes (Codex P1 #1906). See pmoves/docs/security/AGENT_ZERO_SELF_UPDATER.md.
    self_update_remote = _get_kv(text, "A0_SELF_UPDATE_REMOTE_URL")
    if not self_update_remote:
        text = _set_kv(
            text,
            "A0_SELF_UPDATE_REMOTE_URL",
            "https://github.com/POWERFULMOVES/PMOVES-Agent-Zero.git",
        )

    return text


def _ensure_minio_credentials(text: str) -> str:
    """Auto-generate MinIO credentials if missing or using default minioadmin."""
    minio_user = _first_real(text, ["MINIO_USER", "MINIO_ACCESS_KEY", "MINIO_ROOT_USER"])
    if not minio_user or minio_user == "minioadmin":
        minio_user = "pm_minio_" + _rand_alnum(8)
    for k in ("MINIO_USER", "MINIO_ROOT_USER", "MINIO_ACCESS_KEY"):
        text = _set_kv(text, k, minio_user)

    minio_pass = _first_real(text, ["MINIO_PASSWORD", "MINIO_SECRET_KEY", "MINIO_ROOT_PASSWORD"])
    if not minio_pass or minio_pass == "minioadmin":
        minio_pass = "pm_" + _strong_random(24)
    for k in ("MINIO_PASSWORD", "MINIO_ROOT_PASSWORD", "MINIO_SECRET_KEY"):
        text = _set_kv(text, k, minio_pass)
    return text



def upsert_env(path: Path, env_gen_path: Path, pairs: dict[str, str]) -> None:
    """Apply branded defaults to env file, strengthen weak keys, and write back."""
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    for key, value in pairs.items():
        current = _get_kv(text, key)
        if current and current not in PLACEHOLDER_VALUES:
            # Check if current value has been superseded by a migration
            if current in SUPERSEDED_VALUES:
                new_val = SUPERSEDED_VALUES[current]
                if new_val != current:
                    text = _set_kv(text, key, new_val)
            continue
        text = _set_kv(text, key, value)

    # Strengthen keys if weak/short
    meili_key = _get_kv(text, "MEILI_MASTER_KEY")
    if len(meili_key) < 16:
        text = _set_kv(text, "MEILI_MASTER_KEY", _strong_random(24))

    companion_key = _get_kv(text, "INVIDIOUS_COMPANION_KEY")
    if len(companion_key) != 16:
        text = _set_kv(text, "INVIDIOUS_COMPANION_KEY", _rand_exact_len(16))

    # Qdrant API key for inter-service authentication
    qdrant_key = _get_kv(text, "QDRANT__API_KEY")
    if len(qdrant_key) < 32:
        text = _set_kv(text, "QDRANT__API_KEY", _strong_random(32))

    hmac_key = _get_kv(text, "INVIDIOUS_HMAC_KEY")
    if len(hmac_key) < 32:
        text = _set_kv(text, "INVIDIOUS_HMAC_KEY", _strong_random(24))

    neo4j_password = _get_kv(text, "NEO4J_PASSWORD")
    if _is_blank_or_placeholder(neo4j_password):
        neo4j_password = "pm_" + _strong_random(16)
        text = _set_kv(text, "NEO4J_PASSWORD", neo4j_password)
    text = _set_kv(text, "NEO4J_AUTH", f"neo4j/{neo4j_password}")

    # Generate Open Notebook + Surreal credentials per install if missing.
    text = _ensure_notebook_and_surreal_credentials(text)

    # Generate integration credentials (Firefly III, n8n, Wger) if missing.
    text = _ensure_integration_credentials(text)

    # Alias generic Google OAuth credentials into the channel-monitor / yt-cookies
    # namespace. Phase 9C: yt-cookies pipeline + channel-monitor both look for
    # CHANNEL_MONITOR_GOOGLE_CLIENT_ID/SECRET, but the canonical secrets pipeline
    # exports them under the shorter GOOGLE_CLIENT_ID/SECRET names. Without this
    # alias, the placeholder lingers in env.shared even after a successful sync
    # and the OAuth flow refuses to start.
    text = _ensure_channel_monitor_google_alias(text)

    # Archon (native compose) SUPABASE_SERVICE_KEY is hydrated post-funnel by
    # secrets-runtime-hydrate (freshest canonical source), NOT aliased here —
    # a pre-hydration copy would block that fresh key (Codex #1984 P1).

    # Identity defaults: operator email cascades to Supabase, n8n, Wger.
    text = _ensure_identity_defaults(text)

    # Tailscale defaults: auto-populate hostname and tags (auth key is manual).
    text = _ensure_tailscale_defaults(text)

    # Agent Zero defaults: MCP secret, JetStream, model routing.
    text = _ensure_agent_zero_defaults(text)

    # MinIO credentials: replace default minioadmin, sync all 6 variables.
    text = _ensure_minio_credentials(text)

    # CHIT passphrase: auto-generate if blank (HMAC signing + anchor encryption key).
    chit_pass = _get_kv(text, "CHIT_PASSPHRASE")
    if _is_blank_or_placeholder(chit_pass):
        text = _set_kv(text, "CHIT_PASSPHRASE", _strong_random(48))


    path.write_text(text, encoding="utf-8")

    # Mirror NEO4J_AUTH into .env.generated for compose-only consumers.
    env_gen_path.parent.mkdir(parents=True, exist_ok=True)
    gen = env_gen_path.read_text(encoding="utf-8") if env_gen_path.exists() else ""
    gen = _set_kv(gen, "NEO4J_AUTH", f"neo4j/{neo4j_password}")
    env_gen_path.write_text(gen, encoding="utf-8")


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments for env file paths."""
    parser = argparse.ArgumentParser(description="Apply branded env defaults.")
    parser.add_argument("--env-file", type=Path, default=ENV_DEFAULT, help="Path to env file.")
    parser.add_argument(
        "--generated-env-file",
        type=Path,
        default=ENV_GEN_DEFAULT,
        help="Path to generated env file for compose mirrors.",
    )
    return parser.parse_args()


def main() -> int:
    """Entry point: load env file, apply all branded defaults, write back."""
    args = parse_args()
    env_path = args.env_file
    env_gen_path = args.generated_env_file
    try:
        env_path.parent.mkdir(parents=True, exist_ok=True)
        if not env_path.exists():
            env_path.write_text("", encoding="utf-8")
        upsert_env(env_path, env_gen_path, DEFAULTS)
    except OSError as e:
        print(f"Error writing env files: {e}", file=sys.stderr)
        return 1
    print(f"Branded defaults applied to {env_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
