#!/usr/bin/env python3
"""Emit an OpenSSH ``allowed_signers`` file from the signing identity cards.

Why
---
`SIGNING_IDENTITY_CARDS.md` describes CI verify as "branch protection runs
``git verify-commit`` against ``allowed_signers``" — but no such file existed, so
that half of the design was never runnable. The cards already carry
``ml.ssh_allowed_signers_line``; this turns them into the keyring.

Deriving it rather than hand-maintaining it is the point. A hand-written keyring
drifts from the cards, and a keyring that disagrees with the registry it is
supposed to represent is worse than none: verification keeps succeeding, against
the wrong set.

Bootstrap note
--------------
The first commit that establishes trust roots cannot itself be verified against
them — that is what a bootstrap is. It is attested by the operator's
authenticated merge. Every card change *after* the keyring exists can be
verified properly, which is the property this unlocks.

Usage
-----
    python pmoves/tools/build_allowed_signers.py            # write the file
    python pmoves/tools/build_allowed_signers.py --check    # drift gate
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CARDS = REPO_ROOT / "pmoves" / "config" / "signing_identity_cards.yaml"
OUT = REPO_ROOT / "pmoves" / "config" / "allowed_signers"

HEADER = """\
# GENERATED by pmoves/tools/build_allowed_signers.py — do not hand-edit.
# Source of truth: pmoves/config/signing_identity_cards.yaml (ml.ssh_allowed_signers_line)
#
# Regenerate:  make -C pmoves allowed-signers
# Drift gate:  make -C pmoves allowed-signers-check
#
# Point git at it to verify commit signatures:
#   git config gpg.ssh.allowedSignersFile pmoves/config/allowed_signers
#   git verify-commit <rev>
#
# Only ACTIVE cards carrying an ssh_allowed_signers_line appear here. A card
# without one is not a defect — most identities authenticate via github-app —
# it simply has no SSH key to trust.
"""


def _load_cards() -> list[dict]:
    try:
        import yaml
    except ImportError:  # pragma: no cover - environment guard
        print("ERROR: PyYAML is required", file=sys.stderr)
        raise SystemExit(2)
    data = yaml.safe_load(CARDS.read_text(encoding="utf-8"))
    cards = data["cards"] if isinstance(data, dict) and "cards" in data else data
    if not isinstance(cards, list):
        print(f"ERROR: {CARDS} did not parse to a list of cards", file=sys.stderr)
        raise SystemExit(2)
    return cards


def render(cards: list[dict]) -> tuple[str, list[str]]:
    """Return (file_text, warnings)."""
    rows: list[tuple[str, str]] = []
    warnings: list[str] = []
    for card in cards:
        ml = card.get("ml") or {}
        line = (ml.get("ssh_allowed_signers_line") or "").strip()
        if not line:
            continue
        agent = ((card.get("h") or {}).get("agent_id")) or "<no agent_id>"
        if not card.get("active", False):
            warnings.append(f"{agent}: card is inactive, key NOT trusted")
            continue
        principal = line.split(None, 1)[0]
        # git matches the allowed-signers principal against the signer IDENTITY,
        # which for commit signing is the committer email. An agent_id principal
        # parses fine and then never matches anything -- verification would fail
        # closed but for a reason nobody could see from the file. Surface it.
        if "@" not in principal:
            warnings.append(
                f"{agent}: principal {principal!r} is not an email, so "
                f"`git verify-commit` will not match it against a committer identity"
            )
        rows.append((agent, line))

    rows.sort(key=lambda r: r[0])
    body = "".join(f"{line}\n" for _, line in rows)
    return HEADER + "\n" + body, warnings


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed file differs from a fresh render")
    args = ap.parse_args(argv)

    text, warnings = render(_load_cards())
    n = sum(1 for ln in text.splitlines() if ln and not ln.startswith("#"))

    for w in warnings:
        print(f"WARN: {w}", file=sys.stderr)

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(
                f"ERROR: {OUT.relative_to(REPO_ROOT)} is out of sync with the cards — "
                f"run `make -C pmoves allowed-signers` and commit.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: allowed_signers in sync ({n} trusted keys).")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO_ROOT)} ({n} trusted keys).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
