#!/usr/bin/env python3
"""URL-encode passwords for safe interpolation in connection strings.

Reads env tier files for passwords that may contain URL-unsafe characters
(/ + = @ : ? #) and writes URL-encoded variants to a companion file.

This is needed because Docker Compose interpolates raw env values into
postgres://user:PASSWORD@host/db connection strings. A password containing
'/' breaks URL parsing (e.g. zode0dl7/JgAaNoVqjzHQ0S5Iq1vi7Tt becomes
a path segment). URL-encoding (%2F) prevents this.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from urllib.parse import quote

PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Keys whose values get embedded in URLs and need encoding
URL_EMBEDDED_KEYS = [
    "POSTGRES_PASSWORD",
    "SUPABASE_DB_PASSWORD",
    "KONG_PG_PASSWORD",
]

# Characters that are unsafe inside the password part of a URL
URL_UNSAFE_CHARS = set("/:@?#=+&")


def _parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if key:
            values[key] = value
    return values


def _needs_encoding(value: str) -> bool:
    return bool(URL_UNSAFE_CHARS & set(value))


def generate_urlencoded(
    source_files: list[Path],
    output_file: Path,
) -> dict[str, str]:
    """Read source env files and produce URL-encoded variants.

    Returns dict of key -> encoded_value for keys that needed encoding.
    """
    merged: dict[str, str] = {}
    for src in source_files:
        merged.update(_parse_env_file(src))

    encoded: dict[str, str] = {}
    for key in URL_EMBEDDED_KEYS:
        raw = merged.get(key, "").strip()
        if not raw:
            continue
        if _needs_encoding(raw):
            encoded[f"{key}_URLENCODED"] = quote(raw, safe="")
        else:
            # Even if safe, emit the encoded key so compose fallback always resolves
            encoded[f"{key}_URLENCODED"] = raw

    if not encoded:
        print("No URL-unsafe passwords found — no encoding needed.")
        return encoded

    lines = [
        "# Auto-generated by credential_urlencoder.py",
        "# These values are URL-encoded for safe interpolation in connection strings.",
        "# DO NOT EDIT — regenerate via: make -C pmoves secrets-funnel",
        "",
    ]
    for k, v in sorted(encoded.items()):
        lines.append(f"{k}={v}")
    lines.append("")

    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {len(encoded)} URL-encoded credential(s) to {output_file}:")
    for k in sorted(encoded):
        raw_key = k.replace("_URLENCODED", "")
        raw_val = merged.get(raw_key, "")
        if raw_val != encoded[k]:
            print(f"  {k}: encoded (raw contained URL-unsafe chars)")
        else:
            print(f"  {k}: passthrough (already URL-safe)")

    return encoded


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        nargs="+",
        default=[
            PROJECT_ROOT / "env.shared",
            PROJECT_ROOT / "env.tier-supabase",
        ],
        help="Source env files to read passwords from",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=PROJECT_ROOT / "env.tier-supabase.urlencoded",
        help="Output file for URL-encoded values",
    )
    args = parser.parse_args(argv)

    sources = [s.expanduser().resolve() for s in args.source]
    existing = [s for s in sources if s.exists()]
    if not existing:
        print(f"No source files found: {[str(s) for s in sources]}")
        return 0

    generate_urlencoded(existing, args.output.expanduser().resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
