#!/usr/bin/env python3
"""Install PMOVES fleet CLI wrappers, cross-platform.

BOTH platforms install a DELEGATE, never a copy. A copy cannot be fixed: the
tracked wrapper is where every launcher bug gets fixed, and a frozen copy in
~/.local/bin keeps running the version that was current on install day.

Unix:    exec-delegates pointing at the in-repo wrappers, so each wrapper still
         resolves the repository root from its real location (a plain copy
         resolves it to $HOME).
Windows: .bat delegates that bake PMOVES_LAUNCHER_ROOT and `call` the tracked
         template in pmoves/scripts/windows/. This used to be a baked COPY, and
         the failure was measured on Z890 (2026-09-17): the installed
         claude-pmoves.bat dated 2026-08-15 and still ran
         `claude --agent delivery-agent` directly -- no env.shared, no
         --mcp-config roster, no node identity -- while the tracked template had
         gained all three. Sessions launched, looked normal, and were credless
         and identity-less for a month.

Wrappers: pmoves-mini, crush-pmoves, hermes-pmoves, claude-pmoves,
          codex-pmoves, kilo-pmoves, kimi-pmoves.

Usage:
    python pmoves/tools/install_tools.py [--bin DIR] [--dry-run]
    python pmoves/tools/install_tools.py --check-shims   # drift doctor

Run via make:
    make -C pmoves install-tools
    make -C pmoves cli-check      # host CLIs + installed-shim drift
"""

from __future__ import annotations

import argparse
import os
import stat
import sys
from pathlib import Path

PMOVES_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = PMOVES_ROOT.parent
SCRIPTS_DIR = PMOVES_ROOT / "scripts"
WINDOWS_DIR = SCRIPTS_DIR / "windows"

# (bash source under pmoves/scripts/, installed command name, windows template)
WRAPPERS = [
    ("pmoves-mini", "pmoves-mini", "pmoves-mini.bat"),
    ("crush-pmoves", "crush-pmoves", "crush-pmoves.bat"),
    ("hermes-pmoves", "hermes-pmoves", "hermes-pmoves.bat"),
    ("claude-pmoves.sh", "claude-pmoves", "claude-pmoves.bat"),
    ("codex-pmoves.sh", "codex-pmoves", "codex-pmoves.bat"),
    ("kilo-pmoves.sh", "kilo-pmoves", "kilo-pmoves.bat"),
    ("kimi-pmoves.sh", "kimi-pmoves", "kimi-pmoves.bat"),
]

REPO_ROOT_PLACEHOLDER = "__PMOVES_REPO_ROOT__"
CLI_MANIFEST = PMOVES_ROOT / "configs" / "cli_tools.yaml"


def default_bin_dir() -> Path:
    override = os.environ.get("PMOVES_BIN")
    if override:
        return Path(override).expanduser()
    return Path.home() / ".local" / "bin"


UNIX_DELEGATE = """#!/usr/bin/env bash
# Generated by pmoves/tools/install_tools.py -- do not edit.
# A DELEGATE, not a copy. Two reasons, both load-bearing:
#
#  1. Repo root. Every bash wrapper derives the repository root from its own
#     location (dirname "$0"/.. or /../..). Copied into ~/.local/bin that
#     resolves to $HOME, so the wrapper cannot find the repo and silently
#     degrades -- claude-pmoves falls back to a raw `claude` with no
#     env.shared and no MCP roster, which looks like it worked.
#  2. Symlink clobber. install-claude-pmoves-command.sh installs
#     ~/.local/bin/claude-pmoves as `ln -sf` to the TRACKED launcher. A plain
#     write follows that symlink and overwrites the repo file with this
#     wrapper, which then execs itself. The installer unlinks first.
#
# `exec bash`, not `exec` on the target: the target is a TRACKED repo file, and
# its exec bit is a property of the git index, not of this installer. Every
# *-pmoves source except pmoves-mini and crush-pmoves shipped 100644, so a bare
# exec died with "Permission denied" on every fresh clone. `make -C pmoves
# claude-pmoves` already invokes them as `bash <script>`, which is why the Make
# path worked while the PATH command did not -- and why the breakage stayed
# invisible. All seven sources are #!/usr/bin/env bash, so this is exact.
exec bash "{target}" "$@"
"""

# The Windows half of the same idea, and it did not exist until 2026-09-17.
#
# Windows baked the repo root into a COPY of the tracked template. That works on
# install day and rots silently afterwards, because the tracked template is
# where launcher bugs get fixed and the copy never hears about it. Measured on
# Z890: ~/.local/bin/claude-pmoves.bat dated 2026-08-15, 429 bytes, running
# `claude --agent delivery-agent` with no env.shared, no --mcp-config roster and
# no node identity, while the tracked template was 5.3 KB and did all three. The
# template's own comment already warned that an identity wired into only one
# launcher would be "correct, tested, and unreachable on the one machine that
# needed it" -- this is that failure one layer down, in the install step.
#
# `call`, not `start`/direct invocation: `call` returns control so %ERRORLEVEL%
# propagates, and it keeps %* quoting intact (measured: the identity's
# --append-system-prompt survives cmd -> powershell -File -> @args as ONE arg).
#
# `goto missing` rather than a parenthesised if: the baked root may contain
# `)` -- C:\Program Files (x86) -- and cmd.exe expands %VAR% while PARSING a
# block, closing it early. Same trap the templates document inline.
WINDOWS_DELEGATE = """@echo off
rem Generated by pmoves/tools/install_tools.py -- do not edit.
rem A DELEGATE, not a copy: it only bakes the repo root and hands off to the
rem TRACKED template, so fixing the template fixes every node with no re-install.
rem Re-run `make -C pmoves install-tools` only after MOVING the repo.
setlocal
set "PMOVES_LAUNCHER_ROOT={root}"
if not exist "{target}" goto missing
call "{target}" %*
exit /b %ERRORLEVEL%
:missing
echo [{command}] launcher template missing: {target} 1>&2
echo [{command}] the repo moved or the checkout is incomplete. Re-run: 1>&2
echo [{command}]   make -C pmoves install-tools 1>&2
exit /b 1
"""


def expected_wrappers(bin_dir: Path) -> dict[Path, tuple[str, str]]:
    """dest -> (expected content, source label), for install AND drift checking.

    One function so the doctor cannot drift from the installer: if `--check-shims`
    computed expectations its own way, it would eventually bless a shim the
    installer would have rewritten.
    """
    out: dict[Path, tuple[str, str]] = {}
    for source_name, command, template_name in WRAPPERS:
        if os.name == "nt":
            template = WINDOWS_DIR / template_name
            if not template.is_file():
                continue
            dest = bin_dir / f"{command}.bat"
            content = WINDOWS_DELEGATE.format(
                root=str(REPO_ROOT), target=str(template), command=command
            )
            out[dest] = (content, template_name)
        else:
            source = SCRIPTS_DIR / source_name
            if not source.is_file():
                continue
            out[bin_dir / command] = (
                UNIX_DELEGATE.format(target=source),
                source_name,
            )
    return out


def install_unix(bin_dir: Path, dry_run: bool) -> list[Path]:
    installed: list[Path] = []
    for source_name, command, _ in WRAPPERS:
        source = SCRIPTS_DIR / source_name
        if not source.is_file():
            print(f"WARN: bash wrapper missing, skipping: {source}")
            continue
        dest = bin_dir / command
        print(f"[install] {source_name} -> {dest} (delegate, repo root baked)")
        if dry_run:
            installed.append(dest)
            continue
        # Unlink first: os.path.lexists sees a symlink whose target is gone, and
        # write_bytes/write_text on a live symlink writes THROUGH it.
        if dest.is_symlink() or dest.exists():
            dest.unlink()
        dest.write_text(UNIX_DELEGATE.format(target=source), encoding="utf-8")
        mode = dest.stat().st_mode
        dest.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        installed.append(dest)
    return installed


def install_windows(bin_dir: Path, dry_run: bool) -> list[Path]:
    installed: list[Path] = []
    for _, command, template_name in WRAPPERS:
        if not (WINDOWS_DIR / template_name).is_file():
            print(f"WARN: windows shim template missing, skipping: {template_name}")
    for dest, (content, label) in expected_wrappers(bin_dir).items():
        print(f"[install] {label} -> {dest} (delegate, repo root baked)")
        if dry_run:
            installed.append(dest)
            continue
        dest.write_text(content, encoding="utf-8", newline="\r\n")
        installed.append(dest)
    return installed


def check_installed_wrappers(bin_dir: Path) -> int:
    """Report installed shims that are absent or stale. Returns 1 if any are.

    THE BLIND SPOT THIS CLOSES: `--check` validated host CLIs only, so a shim
    that was months out of date -- pointing at a raw `claude`, with no
    env.shared, no MCP roster and no node identity -- reported nothing at all.
    Z890 ran exactly that from 2026-08-15 to 2026-09-17. The sessions launched,
    which is why nobody looked.

    Content equality against what the installer would write NOW, not a version
    stamp: the delegate has no version to stamp, and "does it match" is the only
    question that catches a hand-edit as well as a stale install.
    """
    expected = expected_wrappers(bin_dir)
    if not expected:
        print(f"ERROR: no wrapper sources found under {SCRIPTS_DIR}")
        return 1
    stale: list[str] = []
    absent: list[str] = []
    print(f"Installed wrapper check ({bin_dir}):")
    for dest, (content, label) in sorted(expected.items()):
        name = dest.name
        if not dest.exists():
            print(f"  ABSENT   {name}  (would install from {label})")
            absent.append(name)
            continue
        try:
            actual = dest.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"  UNREADABLE {name}: {exc}")
            stale.append(name)
            continue
        # Compare newline-normalized: the installer writes CRLF on Windows, and a
        # git-checkout or editor round-trip may have changed only the endings.
        # That is not the drift we are hunting.
        if actual.replace("\r\n", "\n") == content.replace("\r\n", "\n"):
            print(f"  OK       {name} -> delegate for {label}")
        else:
            print(f"  STALE    {name}  (differs from {label}; it will NOT get fixes)")
            stale.append(name)
    if stale or absent:
        print("")
        if stale:
            print(f"ERROR: {len(stale)} installed wrapper(s) stale: {', '.join(stale)}")
        if absent:
            print(f"note: {len(absent)} wrapper(s) not installed: {', '.join(absent)}")
        print("Fix: make -C pmoves install-tools")
        return 1 if stale else 0
    return 0


def warn_if_not_on_path(bin_dir: Path) -> None:
    path_env = os.environ.get("PATH", "")
    sep = os.pathsep
    candidates = {str(bin_dir), str(bin_dir.resolve())}
    parts = path_env.split(sep)
    if os.name == "nt":
        normalized = {part.strip('"').rstrip("\\/").lower() for part in parts if part}
        found = any(candidate.lower().rstrip("\\/") in normalized for candidate in candidates)
    else:
        found = bool(candidates & set(parts))
    if not found:
        print(f"WARN: {bin_dir} is not on PATH - add it to your shell profile.")


def _cli_version(check_cmd: str) -> str:
    """Best-effort version capture: run the manifest's check command, keep line 1."""
    import shlex
    import subprocess

    try:
        completed = subprocess.run(
            shlex.split(check_cmd),
            check=False,
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (OSError, ValueError, subprocess.TimeoutExpired):
        return ""
    stream = completed.stdout or completed.stderr
    for line in stream.splitlines():
        line = line.strip()
        if line:
            return line[:120]
    return ""


def check_host_clis(strict: bool, report_versions: bool = False) -> int:
    """Doctor mode: validate host CLIs against configs/cli_tools.yaml."""
    import shutil

    try:
        import yaml
    except ImportError:
        print("ERROR: --check needs PyYAML (run: make -C pmoves env-bootstrap-lite)")
        return 1
    if not CLI_MANIFEST.is_file():
        print(f"ERROR: manifest missing: {CLI_MANIFEST}")
        return 1

    manifest = yaml.safe_load(CLI_MANIFEST.read_text(encoding="utf-8")) or {}
    host_clis = manifest.get("host_clis", {}) or {}
    platform_key = "windows" if os.name == "nt" else "linux"
    missing_required: list[str] = []
    missing_optional = 0

    print("Host CLI check (configs/cli_tools.yaml):")
    for name, spec in host_clis.items():
        spec = spec or {}
        binary = shutil.which(name)
        required = bool(spec.get("required", False))
        if binary:
            version = f"  {_cli_version(spec.get('check', ''))}" if report_versions and spec.get("check") else ""
            print(f"  OK       {name}: {binary}{version}")
            continue
        hint = (spec.get("install", {}) or {}).get(platform_key, "")
        marker = "REQUIRED" if required else "optional"
        print(f"  MISSING  {name} ({marker}) - {spec.get('purpose', '')}")
        if hint:
            print(f"           install: {hint}")
        if required:
            missing_required.append(name)
        else:
            missing_optional += 1

    if missing_required:
        print(f"ERROR: required host CLIs missing: {', '.join(missing_required)}")
        return 1
    if strict and missing_optional:
        print(f"ERROR: strict mode - {missing_optional} optional CLI(s) missing")
        return 1
    if missing_optional:
        print(f"note: {missing_optional} optional CLI(s) missing - fine unless a lane needs them")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--bin",
        default=None,
        help="Install directory (default: $PMOVES_BIN or ~/.local/bin).",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print actions only.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Doctor mode: validate host CLIs against configs/cli_tools.yaml (no install).",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="With --check: also fail on missing optional CLIs.",
    )
    parser.add_argument(
        "--no-report-versions",
        action="store_true",
        help="With --check: skip the per-CLI version capture line.",
    )
    parser.add_argument(
        "--check-shims",
        action="store_true",
        help="Doctor mode: report installed wrappers that are stale or absent "
             "(no install). Implied by --check.",
    )
    args = parser.parse_args(argv)

    if args.check or args.check_shims:
        bin_dir = Path(args.bin).expanduser() if args.bin else default_bin_dir()
        # Shim drift runs on BOTH --check and --check-shims. Folding it into
        # --check is the point: `make -C pmoves cli-check` is the doctor the
        # fleet already runs, and it was the one place a stale launcher could
        # have been caught and was not.
        shim_rc = check_installed_wrappers(bin_dir)
        if args.check_shims and not args.check:
            return shim_rc
        print("")
        # Doctor mode reports versions by default -- the version capture is the
        # point of the check output; --no-report-versions opts out for
        # deterministic-script consumers.
        host_rc = check_host_clis(
            strict=args.strict, report_versions=not args.no_report_versions
        )
        return host_rc or shim_rc

    bin_dir = Path(args.bin).expanduser() if args.bin else default_bin_dir()
    if args.dry_run:
        print(f"[dry-run] target dir: {bin_dir}")
    else:
        bin_dir.mkdir(parents=True, exist_ok=True)

    if os.name == "nt":
        installed = install_windows(bin_dir, args.dry_run)
    else:
        installed = install_unix(bin_dir, args.dry_run)

    if not installed:
        print("ERROR: nothing installed")
        return 1
    warn_if_not_on_path(bin_dir)
    print(f"Installed {len(installed)} wrapper(s) to {bin_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
