#!/usr/bin/env python3
"""Install PMOVES fleet CLI wrappers, cross-platform.

Unix:    writes exec-delegates in ~/.local/bin pointing at the in-repo
         wrappers, so each wrapper still resolves the repository root from its
         real location (a plain copy resolves it to $HOME).
Windows: writes .bat shims (from pmoves/scripts/windows/) with the absolute
         repo root baked in, so PowerShell/cmd can execute them.

Wrappers: pmoves-mini, crush-pmoves, hermes-pmoves, claude-pmoves.

Usage:
    python pmoves/tools/install_tools.py [--bin DIR] [--dry-run]

Run via make:
    make -C pmoves install-tools
"""

from __future__ import annotations

import argparse
import os
import stat
import sys
from pathlib import Path

PMOVES_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = PMOVES_ROOT.parent
SCRIPTS_DIR = PMOVES_ROOT / "scripts"
WINDOWS_DIR = SCRIPTS_DIR / "windows"

# (bash source under pmoves/scripts/, installed command name, windows template)
WRAPPERS = [
    ("pmoves-mini", "pmoves-mini", "pmoves-mini.bat"),
    ("crush-pmoves", "crush-pmoves", "crush-pmoves.bat"),
    ("hermes-pmoves", "hermes-pmoves", "hermes-pmoves.bat"),
    ("claude-pmoves.sh", "claude-pmoves", "claude-pmoves.bat"),
    ("codex-pmoves.sh", "codex-pmoves", "codex-pmoves.bat"),
    ("kilo-pmoves.sh", "kilo-pmoves", "kilo-pmoves.bat"),
    ("kimi-pmoves.sh", "kimi-pmoves", "kimi-pmoves.bat"),
]

REPO_ROOT_PLACEHOLDER = "__PMOVES_REPO_ROOT__"
CLI_MANIFEST = PMOVES_ROOT / "configs" / "cli_tools.yaml"


def default_bin_dir() -> Path:
    override = os.environ.get("PMOVES_BIN")
    if override:
        return Path(override).expanduser()
    return Path.home() / ".local" / "bin"


UNIX_DELEGATE = """#!/usr/bin/env bash
# Generated by pmoves/tools/install_tools.py -- do not edit.
# A DELEGATE, not a copy. Two reasons, both load-bearing:
#
#  1. Repo root. Every bash wrapper derives the repository root from its own
#     location (dirname "$0"/.. or /../..). Copied into ~/.local/bin that
#     resolves to $HOME, so the wrapper cannot find the repo and silently
#     degrades -- claude-pmoves falls back to a raw `claude` with no
#     env.shared and no MCP roster, which looks like it worked.
#  2. Symlink clobber. install-claude-pmoves-command.sh installs
#     ~/.local/bin/claude-pmoves as `ln -sf` to the TRACKED launcher. A plain
#     write follows that symlink and overwrites the repo file with this
#     wrapper, which then execs itself. The installer unlinks first.
exec "{target}" "$@"
"""


def install_unix(bin_dir: Path, dry_run: bool) -> list[Path]:
    installed: list[Path] = []
    for source_name, command, _ in WRAPPERS:
        source = SCRIPTS_DIR / source_name
        if not source.is_file():
            print(f"WARN: bash wrapper missing, skipping: {source}")
            continue
        dest = bin_dir / command
        print(f"[install] {source_name} -> {dest} (delegate, repo root baked)")
        if dry_run:
            installed.append(dest)
            continue
        # Unlink first: os.path.lexists sees a symlink whose target is gone, and
        # write_bytes/write_text on a live symlink writes THROUGH it.
        if dest.is_symlink() or dest.exists():
            dest.unlink()
        dest.write_text(UNIX_DELEGATE.format(target=source), encoding="utf-8")
        mode = dest.stat().st_mode
        dest.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        installed.append(dest)
    return installed


def install_windows(bin_dir: Path, dry_run: bool) -> list[Path]:
    installed: list[Path] = []
    baked_root = str(REPO_ROOT)
    for _, command, template_name in WRAPPERS:
        template = WINDOWS_DIR / template_name
        if not template.is_file():
            print(f"WARN: windows shim template missing, skipping: {template}")
            continue
        dest = bin_dir / f"{command}.bat"
        print(f"[install] {template_name} -> {dest} (repo root baked)")
        if dry_run:
            installed.append(dest)
            continue
        content = template.read_text(encoding="utf-8").replace(
            REPO_ROOT_PLACEHOLDER, baked_root
        )
        dest.write_text(content, encoding="utf-8", newline="\r\n")
        installed.append(dest)
    return installed


def warn_if_not_on_path(bin_dir: Path) -> None:
    path_env = os.environ.get("PATH", "")
    sep = os.pathsep
    candidates = {str(bin_dir), str(bin_dir.resolve())}
    parts = path_env.split(sep)
    if os.name == "nt":
        normalized = {part.strip('"').rstrip("\\/").lower() for part in parts if part}
        found = any(candidate.lower().rstrip("\\/") in normalized for candidate in candidates)
    else:
        found = bool(candidates & set(parts))
    if not found:
        print(f"WARN: {bin_dir} is not on PATH - add it to your shell profile.")


def check_host_clis(strict: bool) -> int:
    """Doctor mode: validate host CLIs against configs/cli_tools.yaml."""
    import shutil

    try:
        import yaml
    except ImportError:
        print("ERROR: --check needs PyYAML (run: make -C pmoves env-bootstrap-lite)")
        return 1
    if not CLI_MANIFEST.is_file():
        print(f"ERROR: manifest missing: {CLI_MANIFEST}")
        return 1

    manifest = yaml.safe_load(CLI_MANIFEST.read_text(encoding="utf-8")) or {}
    host_clis = manifest.get("host_clis", {}) or {}
    platform_key = "windows" if os.name == "nt" else "linux"
    missing_required: list[str] = []
    missing_optional = 0

    print("Host CLI check (configs/cli_tools.yaml):")
    for name, spec in host_clis.items():
        spec = spec or {}
        binary = shutil.which(name)
        required = bool(spec.get("required", False))
        if binary:
            print(f"  OK       {name}: {binary}")
            continue
        hint = (spec.get("install", {}) or {}).get(platform_key, "")
        marker = "REQUIRED" if required else "optional"
        print(f"  MISSING  {name} ({marker}) - {spec.get('purpose', '')}")
        if hint:
            print(f"           install: {hint}")
        if required:
            missing_required.append(name)
        else:
            missing_optional += 1

    if missing_required:
        print(f"ERROR: required host CLIs missing: {', '.join(missing_required)}")
        return 1
    if strict and missing_optional:
        print(f"ERROR: strict mode - {missing_optional} optional CLI(s) missing")
        return 1
    if missing_optional:
        print(f"note: {missing_optional} optional CLI(s) missing - fine unless a lane needs them")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--bin",
        default=None,
        help="Install directory (default: $PMOVES_BIN or ~/.local/bin).",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print actions only.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Doctor mode: validate host CLIs against configs/cli_tools.yaml (no install).",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="With --check: also fail on missing optional CLIs.",
    )
    args = parser.parse_args(argv)

    if args.check:
        return check_host_clis(strict=args.strict)

    bin_dir = Path(args.bin).expanduser() if args.bin else default_bin_dir()
    if args.dry_run:
        print(f"[dry-run] target dir: {bin_dir}")
    else:
        bin_dir.mkdir(parents=True, exist_ok=True)

    if os.name == "nt":
        installed = install_windows(bin_dir, args.dry_run)
    else:
        installed = install_unix(bin_dir, args.dry_run)

    if not installed:
        print("ERROR: nothing installed")
        return 1
    warn_if_not_on_path(bin_dir)
    print(f"Installed {len(installed)} wrapper(s) to {bin_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
