#!/usr/bin/env python3
"""Merge env.shared values into tier env files.

This script synchronizes environment variables from env.shared into all tier
environment files (env.tier-llm, env.tier-agent, env.tier-worker, env.tier-media).

Usage:
    python3 pmoves/tools/merge_shared_to_tiers.py
"""

import sys
from pathlib import Path

# Exit codes
EXIT_SUCCESS = 0
EXIT_FILE_NOT_FOUND = 1
EXIT_PERMISSION_ERROR = 2
EXIT_IO_ERROR = 3


def error_exit(msg: str, code: int = EXIT_IO_ERROR) -> None:
    """Print error message to stderr and exit with code."""
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(code)


def read_env_file(file_path: Path) -> dict:
    """Read environment file into a dictionary.

    Args:
        file_path: Path to the environment file

    Returns:
        Dictionary of key=value pairs

    Raises:
        FileNotFoundError: If file doesn't exist
        PermissionError: If file cannot be read
        OSError: For other I/O errors
    """
    try:
        content = file_path.read_text()
    except FileNotFoundError:
        error_exit(f"{file_path} not found. Run 'make ensure-env-shared' first.",
                   EXIT_FILE_NOT_FOUND)
    except PermissionError:
        error_exit(f"Cannot read {file_path}. Check file permissions.",
                   EXIT_PERMISSION_ERROR)
    except OSError as e:
        error_exit(f"Failed to read {file_path}: {e}", EXIT_IO_ERROR)

    values = {}
    for line in content.splitlines():
        if "=" in line and not line.startswith("#"):
            key, value = line.split("=", 1)
            values[key] = value

    return values


def write_env_file(file_path: Path, entries: dict, header: str) -> None:
    """Write environment file with given entries.

    Args:
        file_path: Path to write
        entries: Dictionary of key=value pairs
        header: Header comment line

    Raises:
        PermissionError: If file cannot be written
        OSError: For other I/O errors
    """
    lines = [header]
    for key in sorted(entries.keys()):
        lines.append(f"{key}={entries[key]}")

    content = "\n".join(lines) + "\n"

    try:
        file_path.write_text(content)
    except PermissionError:
        error_exit(f"Cannot write {file_path}. Check file permissions.",
                   EXIT_PERMISSION_ERROR)
    except OSError as e:
        error_exit(f"Failed to write {file_path}: {e}", EXIT_IO_ERROR)


def main() -> None:
    """Main entry point."""
    ROOT = Path(__file__).resolve().parents[1]
    env_shared = ROOT / "env.shared"

    tier_files = [
        "env.tier-llm",
        "env.tier-agent",
        "env.tier-worker",
        "env.tier-media",
    ]

    # Read env.shared into a dict
    shared_values = read_env_file(env_shared)
    print(f"Read {len(shared_values)} values from env.shared")

    # Update each tier file with values from env.shared
    for tier_file in tier_files:
        tier_path = ROOT / tier_file

        if not tier_path.exists():
            print(f"Skipping {tier_file} (not found)")
            continue

        # Read existing tier file
        try:
            lines = tier_path.read_text().splitlines()
        except OSError as e:
            print(f"WARNING: Skipping {tier_file}: {e}", file=sys.stderr)
            continue

        updated = {}

        # Collect existing entries
        for line in lines:
            if line.startswith("#") or not line.strip():
                continue
            if "=" in line:
                key, value = line.split("=", 1)
                # Use value from env.shared if it exists and is not empty
                # otherwise use the existing value
                if key in shared_values and shared_values[key]:
                    updated[key] = shared_values[key]
                else:
                    updated[key] = value

        # Write back with header
        write_env_file(
            tier_path,
            updated,
            "# Auto-generated by pmoves.tools.secrets_sync. Do not edit."
        )
        print(f"{tier_file}: {len(updated)} entries")

    print("Tier environment files synchronized successfully.")


if __name__ == "__main__":
    main()
