#!/usr/bin/env python3
"""Merge env.shared values into tier env files."""

from __future__ import annotations

import argparse
from pathlib import Path


DEFAULT_TIERS = [
    "env.tier-data",
    "env.tier-supabase",
    "env.tier-api",
    "env.tier-llm",
    "env.tier-worker",
    "env.tier-media",
    "env.tier-agent",
    "env.tier-ui",
]


def parse_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Path to pmoves/ directory",
    )
    parser.add_argument(
        "--tier",
        action="append",
        default=[],
        help="Tier env filename (repeatable). Defaults to all env.tier-* files.",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    env_shared = root / "env.shared"
    if not env_shared.exists():
        raise FileNotFoundError(f"env.shared not found: {env_shared}")

    shared_values = parse_env(env_shared)
    print(f"Read {len(shared_values)} values from {env_shared}")

    tier_files = args.tier if args.tier else DEFAULT_TIERS
    for tier_file in tier_files:
        tier_path = root / tier_file
        if not tier_path.exists():
            print(f"Skipping {tier_file} (not found)")
            continue

        lines = tier_path.read_text(encoding="utf-8", errors="ignore").splitlines()
        updated: dict[str, str] = {}
        for line in lines:
            if line.startswith("#") or not line.strip() or "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            if key in shared_values and shared_values[key]:
                updated[key] = shared_values[key]
            else:
                updated[key] = value.strip()

        output = ["# Auto-generated by pmoves.tools.merge_shared_to_tiers. Do not edit."]
        for key in sorted(updated.keys()):
            output.append(f"{key}={updated[key]}")
        tier_path.write_text("\n".join(output) + "\n", encoding="utf-8")
        print(f"{tier_file}: {len(updated)} entries")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
