#!/usr/bin/env python3
# pmoves_launcher_generator.py
# ============================================================================
# PMOVES Registry-Driven Launcher Generator
#
# Single source of truth for the Windows-Aware launcher trio (`.sh` / `.ps1` /
# `.cmd`) and the install scripts that put them on PATH, generated FROM the
# registry (`pmoves/configs/cli_tools.yaml` :: `pmoves_wrappers` for the CLI
# list and `pmoves/config/agent_registry.yaml` for per-node identities).
#
# Why this exists:
#   claude-pmoves and crush-pmoves were hand-written; the rest of the
#   pmoves_wrapper roster (codex, kilo, kimi, hermes) had a `pmoves/scripts/`
#   bash wrapper but no Windows-aware `.cmd`/`.ps1` and no installer -- so
#   they could not be double-clicked from Windows Explorer or bare-named in a
#   PowerShell session.  Hand-writing five more would re-create the drift
#   that already shipped (the symlink-walk bug that test-launcher-root-
#   resolution.sh now pins: three launchers carrying the same block, two of
#   them fixed, one not).
#
# What it emits, under `deploy/provision/`:
#   <cli>-pmoves.sh  + .ps1  + .cmd                          (canonical launcher)
#   install-<cli>-pmoves-command.sh  + .ps1                  (rc/profile installer)
#   <cli>-<node>.sh + .ps1 + .cmd    [per-node pin]          (when registry has a multi-node identity)
#   launchers.manifest.json                                   (registry-driven inventory + sha256)
#
# What it does NOT do (out of scope):
#   - Touch the existing hand-written claude-pmoves.{sh,ps1,cmd} /
#     crush-pmoves.{sh,ps1,cmd}.  Those carry SDK-fixed FAIL-CLOSED MCP
#     roster logic (PR #2847 + #2809) that the simple template cannot
#     reproduce.  They are listed in the manifest as `managed_by: hand`.
#   - Touch the `pmoves/scripts/` bash wrappers.  That surface is a separate
#     concern (npm/PATH wrappers); this generator emits the Windows-aware
#     trio.
#
# SDK + doc provenance:
#   - Claude Code CLI:    `--mcp-config <file>` (project scope) per
#     https://docs.claude.com/en/api/agent-sdk/overview.  Hand-written
#     `claude-pmoves.sh` already implements this; the generator just mirrors
#     the same shell-and-PowerShell shape for the other CLIs.
#   - Wezterm `set-pane-environment-variables` is the canonical pattern for
#     binding env to a session surface; the per-node pin files are the
#     PMOVES equivalent (PMOVES_NODE_ID before the canonical launcher).
#   - Windows PATH shim via `%LOCALAPPDATA%\Microsoft\WindowsApps` mirrors
#     the existing `install-claude-pmoves-command.ps1` recipe (lines 88-101).
#
# Run:
#   python pmoves/tools/pmoves_launcher_generator.py --out deploy/provision
#   python pmoves/tools/pmoves_launcher_generator.py --check            # diff against checked-in
#   python pmoves/tools/pmoves_launcher_generator.py --dry-run --json   # see what would emit
# ============================================================================

from __future__ import annotations

import argparse
import dataclasses
import hashlib
import json
import os
import stat
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable

import yaml


# ----------------------------------------------------------------------------
# Constants
# ----------------------------------------------------------------------------

GENERATOR_VERSION = "1.0.0"
GENERATOR_HEADER_BASH = (
    "# AUTO-GENERATED by pmoves/tools/pmoves_launcher_generator.py v{ver}\n"
    "# Source of truth: pmoves/configs/cli_tools.yaml + pmoves/config/agent_registry.yaml\n"
    "# Regenerate:    python pmoves/tools/pmoves_launcher_generator.py --out deploy/provision\n"
    "# Drift check:   python pmoves/tools/pmoves_launcher_generator.py --check\n"
    "# DO NOT EDIT BY HAND -- your changes will be overwritten by the next regen.\n"
    "# If you need a per-CLI customisation, add it to launcher_overrides.yaml\n"
    "# (pmoves/configs/launcher_overrides.yaml), not to this file."
)
GENERATOR_HEADER_PWSH = (
    "# AUTO-GENERATED by pmoves/tools/pmoves_launcher_generator.py v{ver}\n"
    "# Source of truth: pmoves/configs/cli_tools.yaml + pmoves/config/agent_registry.yaml\n"
    "# Regenerate:    python pmoves/tools/pmoves_launcher_generator.py --out deploy/provision\n"
    "# Drift check:   python pmoves/tools/pmoves_launcher_generator.py --check\n"
    "# DO NOT EDIT BY HAND -- your changes will be overwritten by the next regen.\n"
    "# If you need a per-CLI customisation, add it to launcher_overrides.yaml\n"
    "# (pmoves/configs/launcher_overrides.yaml), not to this file."
)

# Default per-CLI blocklists (env vars that control the CLI SDK itself, not
# the MCP creds).  `claude` and `crush` carry these as hand-written and the
# generator only EMITS them for the new wrappers; the hand-written launchers
# stay authoritative on claude/crush (see "What it does NOT do" above).
DEFAULT_BLOCKLIST_BY_TOOL: dict[str, list[str]] = {
    "claude":  ["ANTHROPIC_API_KEY", "ANTHROPIC_AUTH_TOKEN", "ANTHROPIC_BASE_URL",
                "CLAUDECODE", "CLAUDE_CODE_*", "CLAUDE_SESSION_*"],
    "crush":   ["ANTHROPIC_API_KEY", "ANTHROPIC_AUTH_TOKEN", "ANTHROPIC_BASE_URL",
                "CRUSH_*", "OPENAI_API_KEY"],
    "codex":   ["OPENAI_API_KEY", "OPENAI_BASE_URL", "CODEX_*"],
    "kilo":    ["KILOCODE_API_KEY", "KILO_*", "OPENCODE_*"],
    "kimi":    ["KIMI_API_KEY", "MOONSHOT_API_KEY", "KIMI_*"],
    "hermes":  ["HERMES_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY", "HERMES_*"],
}

# Per-CLI binary name (the actual command exec'd at the end).  Defaults to
# the tool family name; override here when the binary differs (e.g. KiloCode
# ships as `kilo`, not `kilocode`).
BINARY_BY_TOOL: dict[str, str] = {
    "claude":  "claude",
    "crush":   "crush",
    "codex":   "codex",
    "kilo":    "kilo",
    "kimi":    "kimi",
    "hermes":  "hermes",
}

# Per-CLI signature aliases (the `signature:` field in agent_registry.yaml
# that an entry's `parent_tool` should match against).  Defaults to
# `[family]` (matches `claude`, `crush` etc.); the Suffix matcher (see
# `load_node_identities`) handles the `4090-claude` -> `claude` case, so
# this list is only for *additional* aliases like kilo <-> kilocode.
DEFAULT_SIGNATURE_ALIASES: dict[str, list[str]] = {
    "claude":  ["claude"],
    "crush":   ["crush"],
    "codex":   ["codex"],
    # `kilo` (wrapper family, drives opencode) is the same project as
    # `kilocode` (signature in agent_registry.yaml).  Both must match so
    # per-node identity discovery sees kilocode_glm and kiloclaw.
    "kilo":    ["kilo", "kilocode"],
    "kimi":    ["kimi"],
    "hermes":  ["hermes"],
}

# Name bridges: alias `Z_AI_API_KEY` -> `ZAI_API_KEY` (crush's upstream name).
# Each entry is a `(from_var, to_var)`; the bridge only fires when `to_var`
# is unset and `from_var` is set, so an explicit operator pin still wins.
DEFAULT_BRIDGES_BY_TOOL: dict[str, list[tuple[str, str]]] = {
    "crush":  [("Z_AI_API_KEY", "ZAI_API_KEY")],
    "kilo":   [("Z_AI_API_KEY", "ZAI_API_KEY")],
    "kimi":   [],
    "codex":  [],
    "hermes": [],
    "claude": [],
}


# ----------------------------------------------------------------------------
# Data model
# ----------------------------------------------------------------------------

@dataclass(frozen=True)
class CliTool:
    """One CLI from cli_tools.yaml :: pmoves_wrappers."""
    name: str               # wrapper name as registered (e.g. "kilo-pmoves",
                            # "claude-pmoves") -- already carries "-pmoves" suffix
    purpose: str            # human description from cli_tools.yaml
    binary: str             # actual executable (BINARY_BY_TOOL override)
    blocklist: list[str]    # env vars to NEVER source
    bridges: list[tuple[str, str]]  # (from, to) alias bridges
    signature_aliases: list[str]    # registry `signature` values this tool matches
    managed: str = "generator"  # "generator" (we emit) | "hand" (existing files stay)
    script_path: str | None = None  # pmoves/scripts/* path from cli_tools.yaml

    @property
    def family(self) -> str:
        """Bare tool family (claude / kilo / crush / ...) -- the part before -pmoves.

        Used as the registry `signature` lookup key and as the per-node pin
        file prefix: `claude-4090`, `kilo-5090`, etc.  Always strips the
        `-pmoves` suffix if present (cli_tools.yaml registers them as
        `claude-pmoves`, `kilo-pmoves`).
        """
        return self.name[:-len("-pmoves")] if self.name.endswith("-pmoves") else self.name

    @property
    def launcher_basename(self) -> str:
        """Full wrapper basename used for emit paths -- the cli_tools.yaml name as-is."""
        return self.name

    @property
    def install_basename(self) -> str:
        """Full install script basename (e.g. `install-kilo-pmoves-command.sh`)."""
        return f"install-{self.name}-command"


@dataclass(frozen=True)
class NodeIdentity:
    """One CLI agent identity from agent_registry.yaml."""
    agent_id: str           # registry key (e.g. "claude_4090")
    parent_tool: str        # tool family (e.g. "claude") -- matched by signature
    node_id: str            # PMOVES_NODE_ID to set (registry's node_affinity[0])
    signature: str          # signature from registry (== parent_tool usually)
    description: str        # first line of registry description

    @property
    def launcher_basename(self) -> str:
        """`<cli>-<node>` pin-file basename (e.g. "claude-4090", "kilo-knuckles")."""
        suffix = self.agent_id
        if suffix.startswith(self.parent_tool + "_"):
            suffix = suffix[len(self.parent_tool) + 1:]
        return f"{self.parent_tool}-pmoves-{suffix}"


@dataclass
class GeneratedFile:
    """A file the generator is about to emit."""
    relpath: str            # e.g. "deploy/provision/kilo-pmoves.sh"
    body: str               # full file content (with leading AUTO-GENERATED header)
    executable: bool = False
    managed_by: str = "generator"  # "generator" or "hand"


@dataclass
class Plan:
    """Full emission plan for a given registry snapshot."""
    files: list[GeneratedFile] = field(default_factory=list)
    tools: list[CliTool] = field(default_factory=list)
    identities: list[NodeIdentity] = field(default_factory=list)

    def by_relpath(self, relpath: str) -> GeneratedFile | None:
        for f in self.files:
            if f.relpath == relpath:
                return f
        return None

    def manifest_dict(self) -> dict[str, Any]:
        return {
            "generator_version": GENERATOR_VERSION,
            "tool_count": len(self.tools),
            "identity_count": len(self.identities),
            "files": [
                {
                    "relpath": f.relpath,
                    "sha256": hashlib.sha256(f.body.encode("utf-8")).hexdigest(),
                    "bytes": len(f.body.encode("utf-8")),
                    "executable": f.executable,
                    "managed_by": f.managed_by,
                }
                for f in self.files
            ],
        }


# ----------------------------------------------------------------------------
# Registry loaders
# ----------------------------------------------------------------------------

def _load_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def _family_of(wrapper_name: str) -> str:
    """Return the bare tool family from a wrapper name like `claude-pmoves` -> `claude`.

    Mirrors CliTool.family; duplicated here as a free function because the
    loader needs it BEFORE a CliTool exists.
    """
    return wrapper_name[:-len("-pmoves")] if wrapper_name.endswith("-pmoves") else wrapper_name


def load_cli_tools(registry_root: Path) -> list[CliTool]:
    """Read pmoves/configs/cli_tools.yaml :: pmoves_wrappers."""
    cli_yaml = _load_yaml(registry_root / "pmoves" / "configs" / "cli_tools.yaml")
    wrappers = cli_yaml.get("pmoves_wrappers", {}) or {}
    tools: list[CliTool] = []
    for name, entry in wrappers.items():
        if not isinstance(entry, dict):
            continue
        tool = CliTool(
            name=name,
            purpose=str(entry.get("purpose", "")).strip(),
            binary=BINARY_BY_TOOL.get(_family_of(name), _family_of(name)),
            blocklist=list(DEFAULT_BLOCKLIST_BY_TOOL.get(name, [])),
            bridges=list(DEFAULT_BRIDGES_BY_TOOL.get(name, [])),
            signature_aliases=list(DEFAULT_SIGNATURE_ALIASES.get(_family_of(name), [name])),
            managed="hand" if name in ("claude-pmoves", "crush-pmoves") else "generator",
            script_path=entry.get("script"),
        )
        tools.append(tool)
    return tools


def load_node_identities(registry_root: Path, tools: list[CliTool]) -> list[NodeIdentity]:
    """Read pmoves/config/agent_registry.yaml and find per-CLI identities.

    Match precedence (in order, first hit wins):
      1. `signature == any of CliTool.signature_aliases`
         (crush_glm52.signature="crush", kilocode_glm.signature="kilocode")
      2. `signature` ends with `-<family>` (the Claude per-node signing
         convention: 4090-claude, b850-claude bind to family `claude`)

    Plus a UI/agent surface check: no listening port (CLI session, not
    service).  Each match becomes a per-node pin file
    (`<cli>-<node>.{sh,ps1,cmd}`) that sets `PMOVES_NODE_ID=<node_affinity[0]>`
    and calls the canonical launcher.
    """
    agents = _load_yaml(registry_root / "pmoves" / "config" / "agent_registry.yaml")
    entries = (agents.get("agents") or {})
    # signature -> family lookup (exact match)
    sig_to_family: dict[str, str] = {}
    for t in tools:
        for alias in t.signature_aliases:
            sig_to_family[alias] = t.family

    def family_for_sig(sig_s: str) -> str | None:
        if sig_s in sig_to_family:
            return sig_to_family[sig_s]
        # Claude-style: `4090-claude` -> `claude`
        for t in tools:
            if sig_s.endswith("-" + t.family):
                return t.family
        return None

    out: list[NodeIdentity] = []
    for agent_id, entry in entries.items():
        if not isinstance(entry, dict):
            continue
        sig = entry.get("signature")
        if not sig:
            continue
        sig_s = str(sig)
        family = family_for_sig(sig_s)
        if not family:
            continue
        port = entry.get("port")
        if port is not None:
            continue   # it has a listening socket -> it's a service, not a CLI session
        affinity = (entry.get("topology") or {}).get("node_affinity") or []
        if not affinity:
            continue
        out.append(NodeIdentity(
            agent_id=agent_id,
            parent_tool=family,
            node_id=str(affinity[0]),
            signature=sig_s,
            description=str(entry.get("description") or "").splitlines()[0].strip(),
        ))
    return out


# ----------------------------------------------------------------------------
# Template: bash launcher (.sh)
# ----------------------------------------------------------------------------

def render_bash_launcher(tool: CliTool) -> str:
    """Generate a bash launcher that sources env.shared and execs the binary."""
    blocklist_re = _bash_blocklist_regex(tool.blocklist)
    bridges_block = _render_bridges_bash(tool.bridges)
    # AWK_INVOCATION: replace every single quote with the 4-char bash
    # idiom `'\''` (close single-quote, escaped quote, open new quote).
    # Built in Python so we never nest backslash escapes inside the f-string
    # template body (which breaks both Python f-string parsing and the
    # resulting bash syntax -- see PR conversation 2026-09-16).
    awk_sq_program = '{ gsub(/\\047/, "\\047\\\\\\047\\047"); print }'
    awk_invocation = f"awk '{awk_sq_program}'"
    header = GENERATOR_HEADER_BASH.format(ver=GENERATOR_VERSION)
    body = f"""{header}
# {tool.launcher_basename}.sh -- launch `{tool.binary}` with pmoves/env.shared loaded
# ===========================================================================
# Auto-generated wrapper for {tool.name}. Mirrors the hand-written
# claude-pmoves.sh / crush-pmoves.sh SHELL pattern (resolve repo root via
# symlink-walk, source env.shared, exec the binary) so every pmoves_wrapper
# has the same Windows + POSIX entry surface and the same env-loaded
# preconditions.  The hand-written launchers carry SDK-fixed FAIL-CLOSED
# MCP roster logic this template does not reproduce -- that is by design.
#
# Usage:
#   bash deploy/provision/{tool.launcher_basename}.sh        [args...]
#   install-{tool.name}-pmoves-command.sh && {tool.launcher_basename}         # rc function
#   {tool.launcher_basename}.cmd                              # Windows Explorer double-click
#
# Purpose: {tool.purpose}
#
# Override env.shared path with PMOVES_ENV_SHARED.
set -u

# --- REPO-ROOT RESOLUTION (mirror claude-pmoves.sh) -------------------------
# See test-launcher-root-resolution.sh for why this walk must stay byte-
# identical across every launcher that carries it: an installer symlink at
# ~/.local/bin/<name> would otherwise make ROOT=$HOME and env.shared miss.
SELF="${{BASH_SOURCE[0]:-$0}}"
while [ -L "$SELF" ]; do
  link_dir="$(CDPATH='' cd -P -- "$(dirname -- "$SELF")" && pwd)"
  SELF="$(readlink -- "$SELF")"
  case "$SELF" in /*) ;; *) SELF="$link_dir/$SELF" ;; esac
done
SELF_DIR="$(CDPATH='' cd -P -- "$(dirname -- "$SELF")" && pwd)"
if [ -n "${{PMOVES_LAUNCHER_ROOT:-}}" ]; then
  ROOT="$PMOVES_LAUNCHER_ROOT"
else
  ROOT="$(CDPATH='' cd -P -- "$SELF_DIR/../.." && pwd)" || ROOT=""
fi
if [ ! -f "${{ROOT:-/nonexistent}}/pmoves/Makefile" ]; then
  if [ -n "${{PMOVES_ENV_SHARED:-}}" ] && [ -f "$PMOVES_ENV_SHARED" ]; then
    echo "[{tool.launcher_basename}] WARN: repo root not found (${{ROOT:-<unresolved>}}); using PMOVES_ENV_SHARED." >&2
  else
    echo "[{tool.launcher_basename}] ERROR: no pmoves/Makefile under repo root: ${{ROOT:-<unresolved>}}" >&2
    echo "[{tool.launcher_basename}]        (resolved from: $SELF)" >&2
    exit 1
  fi
fi

# --- MAVIS SDK ENV STRIP ---------------------------------------------------
# The Mavis SDK's `env` block in `~/.claude/settings.json` injects
# ANTHROPIC_BASE_URL, ANTHROPIC_AUTH_TOKEN, ANTHROPIC_MODEL, MCP_TIMEOUT,
# API_TIMEOUT_MS, CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC, ... into every
# Claude Code session's process env.  That env block is inherited by the
# shell that runs this launcher, and would otherwise be inherited by the
# launched `{tool.binary}` -- overriding the operator's own CLI settings
# (their API endpoint, their model picker).
#
# The strip checks each Mavis SDK var against `{tool.binary}`'s NEEDS list
# (defined in pmoves/scripts/mavis_sdk_env.sh alongside this comment):
#   * keeps the ones `{tool.binary}` consumes
#   * preserves the others under PMOVES_MAVIS_SDK_<NAME> for inspection
#   * unsets the originals
#   * emits one WARN line summarizing what was caught
#
# Sourced AFTER repo-root resolution (helper file is repo-relative) and
# BEFORE env.shared loading (the env.shared reader below has a parallel
# blocklist for env.shared itself; the two layers cover the SHELL env and
# env.shared independently).
# ---------------------------------------------------------------------------
if [ -f "$ROOT/pmoves/scripts/mavis_sdk_env.sh" ]; then
  # shellcheck source=../../pmoves/scripts/mavis_sdk_env.sh
  . "$ROOT/pmoves/scripts/mavis_sdk_env.sh"
  mavis_sdk_strip_env_for "{tool.family}"
else
  echo "[{tool.launcher_basename}] WARN: mavis_sdk_env.sh not found at $ROOT/pmoves/scripts/ -- Mavis SDK env may bleed into the launched session." >&2
fi

# --- ENV.SHARED LOADING (mirror claude-pmoves.sh :: lines 72-127) -----------
# env.shared is Docker Compose env_file format: unquoted values + ALIAS lines
# like `SUPABASE_SERVICE_ROLE_KEY=${{SERVICE_ROLE_KEY}}`.  Two hazards:
#   1. We can't `source` it raw -- unquoted values break `. file`.
#   2. We must NOT export values verbatim -- that leaks the literal string
#      "${{SERVICE_ROLE_KEY}}" into MCP headers and starts them unauthorized.
# Build a sanitized assignment file (single-quote plain values; pass ${{...}}-
# bearing lines through for shell expansion), then source it auto-export.
ENVF="${{PMOVES_ENV_SHARED:-$ROOT/pmoves/env.shared}}"
if [ -f "$ENVF" ]; then
  blocklist='{blocklist_re}'
  set +H 2>/dev/null || true
  tmpf=$(mktemp)
  n=0
  while IFS= read -r line || [ -n "$line" ]; do
    line="${{line%$'\\r'}}"
    case "$line" in ''|\\#*) continue;; esac
    case "$line" in *=*) : ;; *) continue;; esac
    key=${{line%%=*}}
    val=${{line#*=}}
    key=$(printf '%s' "$key" | tr -d '[:space:]')
    [ -z "$key" ] && continue
    if [[ "$key" =~ $blocklist ]]; then continue; fi
    val="${{val#"${{val%%[![:space:]]*}}"}}"
    # Two-pass expansion: pass literal `${{...}}` lines through verbatim
    # so the shell expands them on `. "$tmpf"`.  Otherwise single-quote
    # so the literal value lands in the env (avoid the placeholder leak
    # Codex #1987 P2 caught).  Mirror pmoves/scripts/with-env.sh.
    #
    # Single-quote escape routes through awk octal (\\047) -- never nest
    # `\\''` literals (loses count in f-string backslash escapes; see
    # PR conversation 2026-09-16 + pmoves_launcher_generator_LEARNINGS.md).
    if printf '%s' "$val" | grep -qE '[$]{{'; then
      printf '%s=%s\\n' "$key" "$val" >> "$tmpf"
    else
      esc=$(printf '%s' "$val" | {awk_invocation})
      printf "%s='%s'\\n" "$key" "$esc" >> "$tmpf"
    fi
    n=$((n+1))
  done < "$ENVF"
  set -a; set +u
  . "$tmpf"
  set +a; set -u
  rm -f "$tmpf"
  set -H 2>/dev/null || true
  echo "[{tool.launcher_basename}] loaded $n vars from $ENVF" >&2
else
  echo "[{tool.launcher_basename}] WARN: $ENVF not found -- MCP creds may be missing." >&2
  echo "[{tool.launcher_basename}]       run: make -C pmoves ensure-env-shared" >&2
fi

# --- NAME BRIDGES (operator-facing alias to upstream SDK name) -------------
{bridges_block}

# --- LAUNCH ---------------------------------------------------------------
export PMOVES_LAUNCHER_SESSION="{tool.launcher_basename}.sh"
exec {tool.binary} "$@"
"""
    return body


def _bash_blocklist_regex(blocklist: list[str]) -> str:
    """Build the bash regex for the blocklist.

    We use `^` to anchor on the var name and `\\\\*` to convert `*` (CLAUDE_CODE_*)
    into `.*` for shell regex.  Same format as claude-pmoves.sh:74-78.
    """
    if not blocklist:
        return "^$NEVER_MATCH$"
    parts: list[str] = []
    for entry in blocklist:
        # Escape regex metacharacters EXCEPT `*`, which we translate.
        esc = ""
        for ch in entry:
            if ch == "*":
                esc += ".*"
            elif ch in r".^$+?()[]{}|\\":
                esc += "\\" + ch
            else:
                esc += ch
        parts.append(esc)
    body = "|".join(parts)
    return f"^({body})$"


def _render_bridges_bash(bridges: list[tuple[str, str]]) -> str:
    if not bridges:
        return "# (no name bridges for this CLI)"
    lines = ["# Mirror crush-pmoves.sh:133-136 -- alias bridge for upstream-vs-PMOVES env names.",
             "# Only set when the upstream var is unset, so an explicit operator pin still wins."]
    for from_v, to_v in bridges:
        lines.append(
            f'if [ -z "${{{to_v}:-}}" ] && [ -n "${{{from_v}:-}}" ]; then\n'
            f'  export {to_v}="${{{from_v}}}"\n'
            f'  echo "[{{launcher}}] {to_v} <- {from_v} (upstream/PMOVES name bridge)" >&2\n'
            f'fi'
        )
    return "\n".join(lines).replace("{launcher}", "${{0##*/}}")


# ----------------------------------------------------------------------------
# Template: PowerShell launcher (.ps1)
# ----------------------------------------------------------------------------

def render_powershell_launcher(tool: CliTool) -> str:
    """Generate the PowerShell twin of the bash launcher."""
    bridge_block = _render_bridges_powershell(tool.bridges)
    blocklist_entries = _powershell_blocklist_entries(tool.blocklist)
    header = GENERATOR_HEADER_PWSH.format(ver=GENERATOR_VERSION)
    return f"""{header}
# {tool.launcher_basename}.ps1 -- launch `{tool.binary}` with pmoves/env.shared loaded
# ===========================================================================
# Auto-generated PowerShell twin of {tool.launcher_basename}.sh. Same shell
# pattern as the hand-written claude-pmoves.ps1 / crush-pmoves.ps1:
#   1. Resolve repo root from $PSScriptRoot
#   2. Source env.shared via two-pass assign-then-expand
#   3. Apply per-CLI blocklist + name bridges
#   4. Hand off to the binary with any passed args
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File deploy\\provision\\{tool.launcher_basename}.ps1 [args]
#   .\\{tool.launcher_basename}.cmd                     # Windows Explorer double-click
#   install-{tool.name}-pmoves-command.ps1 ; {tool.launcher_basename}     # profile function
#
# Purpose: {tool.purpose}

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$envf = if ($env:PMOVES_ENV_SHARED) {{ $env:PMOVES_ENV_SHARED }} else {{ Join-Path $root 'pmoves\\env.shared' }}

if (Test-Path $envf) {{
    # Per-CLI blocklist (mirrors DEFAULT_BLOCKLIST_BY_TOOL in pmoves_launcher_generator.py).
    # These control the {tool.binary} SDK itself, not MCP creds -- sourcing them would
    # clobber session state or force API billing.
    $blocklist = @(
{blocklist_entries}
    ) -replace '\\*', '.*'

    # Mavis SDK env strip -- dot-source pmoves/scripts/mavis_sdk_env.ps1
    # (PowerShell twin of mavis_sdk_env.sh) and apply the per-CLI needs
    # check. The strip happens BEFORE env.shared is read, because the
    # SHELL env (parent process) and env.shared (PMOVES fleet creds) are
    # independent layers -- the blocklist above handles env.shared, this
    # strip handles SHELL vars that came in from the operator's parent
    # process (typically the Mavis `~/.claude/settings.json` env block).
    $mavis_helper = Join-Path $root 'pmoves\scripts\mavis_sdk_env.ps1'
    if (Test-Path $mavis_helper) {{
        . $mavis_helper
        Strip-MavisSdkEnvFor -CliName '{tool.family}'
    }} else {{
        Write-Warning "[{tool.launcher_basename}] mavis_sdk_env.ps1 not found at $mavis_helper -- Mavis SDK env may bleed into the launched session."
    }}

    # Pass 1: read KEY=VALUE verbatim into an ordered map, skipping blocklisted keys.
    $vars = [ordered]@{{}}
    foreach ($line in Get-Content -LiteralPath $envf) {{
        if ($line -match '^\\s*#') {{ continue }}
        if ($line -match '^\\s*$') {{ continue }}
        $eq = $line.IndexOf('=')
        if ($eq -lt 1) {{ continue }}
        $key = $line.Substring(0, $eq).Trim()
        $blocked = $false
        foreach ($pat in $blocklist) {{ if ($key -match "^$pat$") {{ $blocked = $true; break }} }}
        if ($blocked) {{ continue }}
        $val = ($line.Substring($eq + 1) -replace '\\r$', '')
        if ($key) {{ $vars[$key] = $val }}
    }}
    # Pass 2: expand ${{VAR}} and ${{VAR:-default}} against the map (bounded iteration).
    for ($pass = 0; $pass -lt 5; $pass++) {{
        $changed = $false
        foreach ($k in @($vars.Keys)) {{
            $curKey = $k
            $resolved = [regex]::Replace($vars[$k], '\\\\$\\\\{{([A-Za-z_][A-Za-z0-9_]*)(?::-([^}}]*))?\\\\}}', {{
                param($m)
                $name = $m.Groups[1].Value
                $repl = $null
                if ($name -ne $curKey) {{
                    if ($vars.Contains($name) -and $vars[$name] -ne '' -and $vars[$name] -notmatch '\\\\$\\\\{{') {{
                        $repl = $vars[$name]
                    }} else {{
                        $envv = [Environment]::GetEnvironmentVariable($name)
                        if ($envv) {{ $repl = $envv }}
                    }}
                }}
                if ($null -ne $repl) {{ $repl }}
                elseif ($m.Groups[2].Success) {{ $m.Groups[2].Value }}
                else {{ '' }}
            }})
            if ($resolved -ne $vars[$k]) {{ $vars[$k] = $resolved; $changed = $true }}
        }}
        if (-not $changed) {{ break }}
    }}
    $n = 0
    foreach ($k in $vars.Keys) {{ [Environment]::SetEnvironmentVariable($k, $vars[$k], 'Process'); $n++ }}
    Write-Host "[{tool.launcher_basename}] loaded $n vars from $envf"
    $script:launcherSession = "{tool.launcher_basename}.ps1 ($n vars)"
}} else {{
    Write-Warning "[{tool.launcher_basename}] $envf not found -- MCP creds may be missing."
    $script:launcherSession = "{tool.launcher_basename}.ps1 (env file NOT FOUND)"
}}

[Environment]::SetEnvironmentVariable('PMOVES_LAUNCHER_SESSION', $script:launcherSession, 'Process')

# --- NAME BRIDGES (mirror bash twin) ----------------------------------------
{bridge_block}

# --- LAUNCH ---------------------------------------------------------------
& {tool.binary} @args
"""


def _powershell_blocklist_entries(blocklist: list[str]) -> str:
    if not blocklist:
        return "        # (no blocklist entries -- this CLI sources every var from env.shared)"
    out: list[str] = []
    for entry in blocklist:
        # Quote each entry so PowerShell parses multi-word items correctly.
        out.append(f"        '{entry}',")
    return "\n".join(out)


def _render_bridges_powershell(bridges: list[tuple[str, str]]) -> str:
    if not bridges:
        return "# (no name bridges for this CLI)"
    lines = ["# Mirror crush-pmoves.ps1 -- alias bridge for upstream-vs-PMOVES env names."]
    for from_v, to_v in bridges:
        lines.append(
            f"if (-not $env:{to_v} -and $env:{from_v}) {{\n"
            f"    [Environment]::SetEnvironmentVariable('{to_v}', $env:{from_v}, 'Process')\n"
            f"    Write-Host \"[{tool_name_placeholder()}] {to_v} <- {from_v} (upstream/PMOVES name bridge)\"\n"
            f"}}"
        )
    return "\n".join(lines)


def tool_name_placeholder() -> str:  # tiny helper for clarity in templates
    return "{tool.launcher_basename}"


# ----------------------------------------------------------------------------
# Template: Windows cmd wrapper (.cmd)
# ----------------------------------------------------------------------------

def render_cmd_wrapper(tool: CliTool) -> str:
    """Generate the .cmd wrapper -- the file Windows Explorer double-clicks.

    Always delegates to the .ps1 with `-NoProfile -ExecutionPolicy Bypass`,
    which is the documented way to invoke a PowerShell script from a .cmd
    shim on Windows 10/11.  WinPS 5.1 (`powershell.exe`) is the default on
    most fleet nodes; PowerShell 7 (`pwsh.exe`) is preferred when present.
    See deploy/provision/claude-pmoves.cmd + crush-pmoves.cmd for the
    canonical one-liner this mirrors.
    """
    header = GENERATOR_HEADER_BASH.format(ver=GENERATOR_VERSION).replace("#", "REM")
    return f"""{header}
REM {tool.launcher_basename}.cmd -- double-click / run to launch `{tool.binary}`
REM with pmoves/env.shared loaded. Wraps the .ps1.
@echo off
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0{tool.launcher_basename}.ps1" %*
"""


# ----------------------------------------------------------------------------
# Template: install scripts
# ----------------------------------------------------------------------------

def render_install_bash(tool: CliTool, identities: list[NodeIdentity]) -> str:
    """Generate the bash install script (rc function + PATH symlink)."""
    pin_block = _render_install_bash_pins(tool, identities)
    pin_block_functions = _render_install_bash_pin_functions(tool, identities)
    header = GENERATOR_HEADER_BASH.format(ver=GENERATOR_VERSION)
    pin_label_csv = ", ".join(f"{tool.launcher_basename}-{_pin_label(i)}" for i in identities) if identities else ""
    pin_install_echo = ""
    if pin_label_csv:
        pin_install_echo = f'echo "Also installed: {pin_label_csv}"\n'
    return f"""{header}
# install-{tool.name}-pmoves-command.sh
# ---------------------------------------------------------------------------
# Makes `{tool.launcher_basename}` a bare command in bash/zsh on THIS node, so
# you can type `{tool.launcher_basename}` from any directory instead of the full
# launcher path.  Also installs any per-node pin functions the registry
# describes for the `{tool.name}` family.
#
# Usage:
#   bash deploy/provision/install-{tool.launcher_basename}.sh
#
# Per-node pin functions (set PMOVES_NODE_ID before calling the launcher):
{pin_block}
# ---------------------------------------------------------------------------
set -euo pipefail

script_dir="$(cd "$(dirname "${{BASH_SOURCE[0]:-$0}}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
launcher="$repo_root/deploy/provision/{tool.launcher_basename}.sh"
[ -f "$launcher" ] || {{ echo "launcher not found: $launcher" >&2; exit 1; }}

# Refuse linked worktrees (same guard as install-claude-pmoves-command.sh:30-42):
# a worktree .git is a FILE (gitdir pointer); the canonical checkout has a
# DIRECTORY.  Installing from a worktree points the command at a checkout
# that may be deleted.
if [ -e "$repo_root/.git" ] && [ ! -d "$repo_root/.git" ]; then
  if [ "${{1:-}}" != "--force" ]; then
    echo "REFUSING: $repo_root is a linked git worktree, not the canonical checkout." >&2
    echo "  pass --force to override." >&2
    exit 2
  fi
  echo "  --force given: installing from a worktree anyway." >&2
fi
echo "  resolved repo root: $repo_root"

begin="# >>> pmoves {tool.launcher_basename} >>>"
end="# <<< pmoves {tool.launcher_basename} <<<"

# Function body emitted into the user's rc file.  The per-node pin entries
# follow it (they each call the canonical function).
fn_body=$(cat <<EOF
$begin
# Auto-generated by install-{tool.launcher_basename}.sh.
# Purpose: {tool.purpose}
{tool.launcher_basename}() {{ "$launcher" "$@"; }}
{pin_block_functions}
$end
EOF
)

install_into() {{
  local rc="$1"
  touch "$rc"
  local tmp; tmp="$(mktemp)"
  awk -v b="$begin" -v e="$end" '
    $0==b {{skip=1}}
    skip!=1 {{print}}
    $0==e {{skip=0}}
  ' "$rc" > "$tmp" && mv "$tmp" "$rc"
  printf '\\n%s\\n' "$fn_body" >> "$rc"
  echo "  updated: $rc"
}}

# Resolve the login shell's rc first (zsh vs bash) so a fresh rc-less shell
# of the active shell still gets the function.
case "$(basename "${{SHELL:-bash}}")" in
  zsh) active_rc="$HOME/.zshrc" ;;
  *)   active_rc="$HOME/.bashrc" ;;
esac

installed=0
for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
  if [ -f "$rc" ]; then install_into "$rc"; installed=1; fi
done
if [ ! -f "$active_rc" ]; then install_into "$active_rc"; installed=1; fi

# PATH symlink (mirrors install-claude-pmoves-command.sh:88-96)
bindir="$HOME/.local/bin"
mkdir -p "$bindir"
ln -sf "$launcher" "$bindir/{tool.launcher_basename}"
echo "  path symlink: $bindir/{tool.launcher_basename}"
case ":${{PATH}}:" in
  *":$bindir:"*) : ;;
  *) echo "  NOTE: $bindir is not on PATH -- add it, or use the rc function above." ;;
esac

echo ""
echo "Installed '{tool.launcher_basename}' -> $launcher"
{pin_install_echo}echo "Run:  source ~/.bashrc   (or open a new shell)   then just type:  {tool.launcher_basename}"
"""


def _render_install_bash_pins(tool: CliTool, identities: list[NodeIdentity]) -> str:
    """Human-readable listing for the header docstring."""
    if not identities:
        return f"#   (none -- this CLI is not bound to per-node identities in agent_registry.yaml)"
    return "\n".join(f"#   {tool.launcher_basename}-{_pin_label(i)} (PMOVES_NODE_ID={i.node_id})"
                       for i in identities)


def _pin_label(identity: NodeIdentity) -> str:
    """The suffix for `<cli>-<node>` pin files.  Strip `_` to match the
    conventional naming on the deck (claude-4090, not claude-4090-claude).
    """
    suffix = identity.agent_id
    if suffix.startswith(identity.parent_tool + "_"):
        suffix = suffix[len(identity.parent_tool) + 1:]
    return suffix


def _render_install_bash_pin_functions(tool: CliTool, identities: list[NodeIdentity]) -> str:
    if not identities:
        return ""
    lines: list[str] = []
    for ident in identities:
        suffix = _pin_label(ident)
        # Each pin sets PMOVES_NODE_ID and calls the canonical launcher.
        lines.append(
            f"{tool.launcher_basename}-{suffix}() "
            f"{{ PMOVES_NODE_ID=\"{ident.node_id}\" \"${{PMOVES_LAUNCHER_ROOT:-}}\"; "
            f"PMOVES_NODE_ID=\"{ident.node_id}\" \"{tool.launcher_basename}\" \"$@\"; }}"
        )
    return "\n".join(lines)


def render_install_powershell(tool: CliTool, identities: list[NodeIdentity]) -> str:
    """Generate the PowerShell install script (profile function + PATH shim)."""
    pin_block = _render_install_powershell_pins(identities)
    pin_functions = _render_install_powershell_pin_functions(tool, identities)
    pin_aftermath = ""
    if identities:
        names = ", ".join(f"'{tool.launcher_basename}-{_pin_label(i)}'" for i in identities)
        pin_aftermath = f'Write-Host "Also installed: {names}"\n'
    header = GENERATOR_HEADER_PWSH.format(ver=GENERATOR_VERSION)
    return f"""{header}
# install-{tool.launcher_basename}.ps1
# ---------------------------------------------------------------------------
# Makes `{tool.launcher_basename}` a bare command in PowerShell on THIS node,
# so you can type `{tool.launcher_basename}` from any directory instead of the
# full launcher path.  Mirrors install-claude-pmoves-command.ps1 exactly.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File deploy\\provision\\install-{tool.launcher_basename}.ps1
#
# Per-node pin functions (set $env:PMOVES_NODE_ID before calling the launcher):
{pin_block}
# ---------------------------------------------------------------------------
param([switch]$Force)

$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\\..")).Path
$cmd = Join-Path $repoRoot "deploy\\provision\\{tool.launcher_basename}.cmd"
if (-not (Test-Path $cmd)) {{ throw "launcher not found: $cmd (is this the pmoves repo?)" }}

# Refuse linked worktrees (mirror install-claude-pmoves-command.ps1:32-51).
$gitPath = Join-Path $repoRoot ".git"
if ((Test-Path $gitPath) -and -not (Test-Path $gitPath -PathType Container)) {{
    Write-Host ""
    Write-Host "REFUSING: this is a linked git worktree, not the canonical checkout." -ForegroundColor Red
    if (-not $Force) {{ exit 2 }}
    Write-Host "  -Force given: installing from a worktree anyway." -ForegroundColor Yellow
}}
Write-Host "  resolved repo root: $repoRoot"

$begin = "# >>> pmoves {tool.launcher_basename} >>>"
$end   = "# <<< pmoves {tool.launcher_basename} <<<"
$block = @"
$begin
# Auto-generated by install-{tool.launcher_basename}.ps1.
# Purpose: {tool.purpose}
function {tool.launcher_basename} {{ & "$cmd" @args }}
{pin_functions}
$end
"@

$docs = [Environment]::GetFolderPath('MyDocuments')
$targets = @(
    (Join-Path $docs "WindowsPowerShell\\profile.ps1"),
    (Join-Path $docs "PowerShell\\profile.ps1")
) | Select-Object -Unique

foreach ($profilePath in $targets) {{
    $dir = Split-Path -Parent $profilePath
    if (-not (Test-Path $dir)) {{ New-Item -ItemType Directory -Force -Path $dir | Out-Null }}
    $content = ""
    if (Test-Path $profilePath) {{ $content = Get-Content -Raw -Path $profilePath -ErrorAction SilentlyContinue }}
    if ($null -eq $content) {{ $content = "" }}
    $pattern = [regex]::Escape($begin) + "[\\s\\S]*?" + [regex]::Escape($end)
    $content = [regex]::Replace($content, $pattern, "").TrimEnd()
    if ($content.Length -gt 0) {{ $content += "`r`n`r`n" }}
    $content += $block + "`r`n"
    Set-Content -Path $profilePath -Value $content -Encoding UTF8
    Write-Host "  profile: $profilePath"
}}

# PATH shim (mirrors install-claude-pmoves-command.ps1:88-101).
$shimDir = Join-Path $env:LOCALAPPDATA 'Microsoft\\WindowsApps'
if (Test-Path $shimDir) {{
    $shim = Join-Path $shimDir '{tool.launcher_basename}.cmd'
    $q = [char]34
    $lines = @('@echo off', ('call ' + $q + $cmd + $q + ' %*'))
    Set-Content -Path $shim -Value $lines -Encoding ASCII
    Write-Host "  path shim: $shim"
}} else {{
    Write-Warning "  $shimDir not present - PATH shim skipped (profile function still installed)."
}}

Write-Host ''
Write-Host "Installed '{tool.launcher_basename}' -> $cmd"
{pin_aftermath}
Write-Host 'Works in any NEW shell (PATH shim). In an existing session, open a new shell.'
"""


def _render_install_powershell_pins(identities: list[NodeIdentity]) -> str:
    if not identities:
        return "#   (none -- this CLI is not bound to per-node identities in agent_registry.yaml)"
    return "\n".join(f"#   {i.parent_tool}-pmoves-{_pin_label(i)} ($env:PMOVES_NODE_ID={i.node_id})"
                       for i in identities)


def _render_install_powershell_pin_functions(tool: CliTool,
                                              identities: list[NodeIdentity]) -> str:
    if not identities:
        return ""
    lines: list[str] = []
    for ident in identities:
        suffix = _pin_label(ident)
        lines.append(
            f"function {tool.launcher_basename}-{suffix} {{\n"
            f"    $env:PMOVES_NODE_ID = '{ident.node_id}'\n"
            f"    & {tool.launcher_basename} @args\n"
            f"    Remove-Item Env:PMOVES_NODE_ID -ErrorAction SilentlyContinue\n"
            f"}}"
        )
    return "\n".join(lines)


# ----------------------------------------------------------------------------
# Templates: per-node pin files
# ----------------------------------------------------------------------------

def render_pin_bash(tool: CliTool, ident: NodeIdentity) -> str:
    suffix = _pin_label(ident)
    header = GENERATOR_HEADER_BASH.format(ver=GENERATOR_VERSION)
    return f"""{header}
# {tool.launcher_basename}-{suffix}.sh -- per-node identity pin
# ===========================================================================
# Sets PMOVES_NODE_ID={ident.node_id} and execs {tool.launcher_basename}.sh so the
# session binds to the `{ident.agent_id}` identity from
# pmoves/config/agent_registry.yaml.
#
# Source of truth: agent_registry.yaml entry `{ident.agent_id}`
#   signature: {ident.signature}
#   node_affinity: [{ident.node_id}, ...]
#   description: {ident.description}
#
# Wezterm sets per-pane env via `set-pane-environment-variables`; this is
# the PMOVES equivalent for a CLI surface.  The identity pin is the LAST
# thing set before exec, so a parent env that already exports
# PMOVES_NODE_ID is overridden -- the registry is the canonical binding.
# ===========================================================================
set -u
export PMOVES_NODE_ID="{ident.node_id}"
exec "$(dirname "${{BASH_SOURCE[0]:-$0}}")/{tool.launcher_basename}.sh" "$@"
"""


def render_pin_powershell(tool: CliTool, ident: NodeIdentity) -> str:
    suffix = _pin_label(ident)
    header = GENERATOR_HEADER_PWSH.format(ver=GENERATOR_VERSION)
    return f"""{header}
# {tool.launcher_basename}-{suffix}.ps1 -- per-node identity pin
# ===========================================================================
# Sets $env:PMOVES_NODE_ID='{ident.node_id}' and calls {tool.launcher_basename}.ps1
# so the session binds to the `{ident.agent_id}` identity from
# pmoves/config/agent_registry.yaml.
#
# Source of truth: agent_registry.yaml entry `{ident.agent_id}`
#   signature: {ident.signature}
#   node_affinity: [{ident.node_id}, ...]
# ===========================================================================
$ErrorActionPreference = 'Stop'
$env:PMOVES_NODE_ID = '{ident.node_id}'
$ps1 = Join-Path (Split-Path -Parent $PSScriptRoot) '{tool.launcher_basename}.ps1'
& $ps1 @args
"""


def render_pin_cmd(tool: CliTool, ident: NodeIdentity) -> str:
    suffix = _pin_label(ident)
    header = GENERATOR_HEADER_BASH.format(ver=GENERATOR_VERSION).replace("#", "REM")
    return f"""{header}
REM {tool.launcher_basename}-{suffix}.cmd -- per-node identity pin (Windows wrapper).
REM Sets PMOVES_NODE_ID={ident.node_id} via the .ps1 then delegates to it.
@echo off
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0{tool.launcher_basename}-{suffix}.ps1" %*
"""


# ----------------------------------------------------------------------------
# Plan assembly
# ----------------------------------------------------------------------------

def build_plan(registry_root: Path, include_hand: bool = False) -> Plan:
    """Load the registries and produce the full emission plan.

    If `include_hand` is True, list the hand-written launchers in the
    manifest (managed_by=hand) so the drift check can verify the SDK-fixed
    hand files stay byte-stable across regen runs.  Default False keeps
    the manifest focused on generator output.
    """
    tools = load_cli_tools(registry_root)
    identities = load_node_identities(registry_root, tools)
    plan = Plan(tools=tools, identities=identities)

    for tool in tools:
        tool_idents = [i for i in identities if i.parent_tool == tool.family]
        is_hand = tool.managed == "hand"

        # --- install scripts -------------------------------------------------
        # ONLY emit when the launcher is generator-managed.  For hand-managed
        # tools (claude, crush), the install scripts are SDK-fixed and live
        # in the repo; the operator updates them by hand if they want
        # per-node pin registration.  Overwriting them silently would lose
        # the worktree-refusal guard, the PATH shim recipe, etc.
        if not is_hand:
            rel_ins_sh = f"deploy/provision/{tool.install_basename}.sh"
            rel_ins_ps1 = f"deploy/provision/{tool.install_basename}.ps1"
            body_ins_sh = render_install_bash(tool, tool_idents)
            body_ins_ps1 = render_install_powershell(tool, tool_idents)
            plan.files.extend([
                GeneratedFile(rel_ins_sh, body_ins_sh, executable=True,
                              managed_by="generator"),
                GeneratedFile(rel_ins_ps1, body_ins_ps1, executable=False,
                              managed_by="generator"),
            ])
        elif include_hand:
            # --include-hand: surface the install scripts in the manifest for
            # drift pinning, but emit them too (operator is explicitly asking
            # for the SDK-fixed hand files to be rewritten -- usually a no-no).
            rel_ins_sh = f"deploy/provision/{tool.install_basename}.sh"
            rel_ins_ps1 = f"deploy/provision/{tool.install_basename}.ps1"
            plan.files.extend([
                GeneratedFile(rel_ins_sh, render_install_bash(tool, tool_idents),
                              executable=True, managed_by="hand"),
                GeneratedFile(rel_ins_ps1, render_install_powershell(tool, tool_idents),
                              executable=False, managed_by="hand"),
            ])

        # --- canonical launcher trio (.sh/.ps1/.cmd) -------------------------
        # Hand-managed: emit ONLY with --include-hand (drift pinning).
        # Generator-managed: always emit.
        if not is_hand or include_hand:
            rel_sh = f"deploy/provision/{tool.launcher_basename}.sh"
            rel_ps1 = f"deploy/provision/{tool.launcher_basename}.ps1"
            rel_cmd = f"deploy/provision/{tool.launcher_basename}.cmd"
            body_sh = render_bash_launcher(tool)
            body_ps1 = render_powershell_launcher(tool)
            body_cmd = render_cmd_wrapper(tool)
            plan.files.extend([
                GeneratedFile(rel_sh, body_sh, executable=True,
                              managed_by="hand" if is_hand else "generator"),
                GeneratedFile(rel_ps1, body_ps1, executable=False,
                              managed_by="hand" if is_hand else "generator"),
                GeneratedFile(rel_cmd, body_cmd, executable=False,
                              managed_by="hand" if is_hand else "generator"),
            ])

        # --- per-node pin files ---------------------------------------------
        # ALWAYS emit for every multi-node identity, regardless of hand vs
        # generator status.  These are NEW callers of the canonical launcher
        # (which may be hand-written) -- they do not duplicate it.
        for ident in tool_idents:
            rel_pin_sh = f"deploy/provision/{ident.launcher_basename}.sh"
            rel_pin_ps1 = f"deploy/provision/{ident.launcher_basename}.ps1"
            rel_pin_cmd = f"deploy/provision/{ident.launcher_basename}.cmd"
            plan.files.extend([
                GeneratedFile(rel_pin_sh, render_pin_bash(tool, ident), executable=True),
                GeneratedFile(rel_pin_ps1, render_pin_powershell(tool, ident), executable=False),
                GeneratedFile(rel_pin_cmd, render_pin_cmd(tool, ident), executable=False),
            ])
    return plan


# ----------------------------------------------------------------------------
# Emitter
# ----------------------------------------------------------------------------

def emit(plan: Plan, out_root: Path, plan_root: Path | None = None) -> list[Path]:
    """Write every file in `plan` to `out_root`.  Returns the list of paths
    actually written.  Idempotent: re-running yields byte-identical output.
    """
    written: list[Path] = []
    base = plan_root if plan_root is not None else Path.cwd()
    # Line endings per repo policy (.gitattributes): ps1/bat/cmd are
    # eol=crlf (Windows scripts), everything else eol=lf. emit() must write
    # what the worktree will contain after checkout conversion, or the
    # byte-stability test compares CRLF (repo checkout) against LF (regen)
    # and fails on EVERY platform — the blob is LF in git, the attribute
    # converts at checkout, the generator must match the attribute.
    def _eol(relpath: str) -> str:
        return "\r\n" if relpath.endswith((".ps1", ".bat", ".cmd")) else "\n"
    for f in plan.files:
        target = out_root / f.relpath
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(f.body, encoding="utf-8", newline=_eol(f.relpath))
        if f.executable:
            mode = target.stat().st_mode
            target.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        written.append(target)
    # Always emit the manifest, even when `out_root == plan_root`, so
    # downstream drift-check consumers have a single anchor.
    manifest_target = out_root / "deploy" / "provision" / "launchers.manifest.json"
    manifest_target.parent.mkdir(parents=True, exist_ok=True)
    manifest_target.write_text(
        json.dumps(plan.manifest_dict(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8", newline="\n",
    )
    return written


def check(plan: Plan, repo_root: Path) -> tuple[int, list[str]]:
    """Compare `plan` against what's currently on disk.  Returns (count of
    mismatches, list of human-readable diff messages)."""
    diffs: list[str] = []
    for f in plan.files:
        on_disk = repo_root / f.relpath
        if not on_disk.exists():
            diffs.append(f"MISSING  {f.relpath}")
            continue
        disk_body = on_disk.read_text(encoding="utf-8")
        if disk_body != f.body:
            disk_hash = hashlib.sha256(disk_body.encode("utf-8")).hexdigest()
            gen_hash = hashlib.sha256(f.body.encode("utf-8")).hexdigest()
            diffs.append(f"DIFFER   {f.relpath}  disk={disk_hash[:12]} gen={gen_hash[:12]}")
    # Check the manifest too (it is itself generated)
    manifest_path = repo_root / "deploy" / "provision" / "launchers.manifest.json"
    expected_manifest = json.dumps(plan.manifest_dict(), indent=2, sort_keys=True) + "\n"
    if manifest_path.exists():
        disk_manifest = manifest_path.read_text(encoding="utf-8")
        if disk_manifest != expected_manifest:
            diffs.append(f"DIFFER   deploy/provision/launchers.manifest.json")
    else:
        diffs.append(f"MISSING  deploy/provision/launchers.manifest.json")
    return len(diffs), diffs


# ----------------------------------------------------------------------------
# CLI
# ----------------------------------------------------------------------------

def _parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="pmoves_launcher_generator",
        description="Registry-driven generator for deploy/provision/<cli>-pmoves.{sh,ps1,cmd} "
                    "+ install scripts + per-node pin files.",
    )
    p.add_argument("--registry-root", type=Path, default=Path.cwd(),
                   help="Repo root containing pmoves/configs and pmoves/config (default: cwd)")
    p.add_argument("--out", type=Path, default=None,
                   help="Output root for emitted files (default: registry-root)")
    p.add_argument("--check", action="store_true",
                   help="Diff against checked-in files; exit non-zero on drift")
    p.add_argument("--dry-run", action="store_true",
                   help="Print the emission plan without writing files")
    p.add_argument("--json", action="store_true",
                   help="Machine-readable output (combine with --dry-run)")
    p.add_argument("--include-hand", action="store_true",
                   help="Include hand-written launchers in the manifest (for drift pinning)")
    p.add_argument("--tool", action="append", default=[],
                   help="Restrict emission to one or more CLI tool names (repeatable)")
    return p


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    registry_root = args.registry_root.resolve()
    out_root = (args.out or registry_root).resolve()

    plan = build_plan(registry_root, include_hand=args.include_hand)

    if args.tool:
        wanted = set(args.tool)
        plan.files = [f for f in plan.files
                      if any(t for t in wanted if t in f.relpath)]
        plan.tools = [t for t in plan.tools if t.name in wanted]
        plan.identities = [i for i in plan.identities if i.parent_tool in wanted]

    if args.dry_run:
        if args.json:
            print(json.dumps(plan.manifest_dict(), indent=2, sort_keys=True))
        else:
            print(f"== plan: {len(plan.tools)} tools, {len(plan.identities)} identities, "
                  f"{len(plan.files)} files ==")
            for f in plan.files:
                kind = "exec" if f.executable else "    "
                print(f"  {kind} {f.relpath}  ({len(f.body)} bytes)")
        return 0

    if args.check:
        n, diffs = check(plan, registry_root)
        if diffs:
            for d in diffs:
                print(d)
            print(f"\n{n} drift(s) detected -- run without --check to regenerate.")
            return 1
        print(f"All {len(plan.files)} generator files match the checked-in copies.")
        return 0

    written = emit(plan, out_root, plan_root=registry_root)
    print(f"Emitted {len(written)} files under {out_root}/")
    for f in written:
        print(f"  {f.relative_to(out_root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
