"""Funnel-side guard for self-generated secrets.

Some secrets are **generated by the stack**, not supplied by an operator. If the
secrets pipe treats them as operator-owned it reports them missing (or emits a
placeholder), which is wrong: there is no human value to funnel.

This guard runs between ``decode_secret_map`` and ``build_outputs`` in
``secrets_sync``. It fills the values the pipe can derive deterministically so
they project into the tier env files without any operator input, and it names
the ones that are generated elsewhere so callers can skip them in
"operator-missing" reporting.

Two classes of self-generated secret:

* **Derivable now** — the Supabase ``anon`` / ``service_role`` API keys are
  HS256 JWTs over ``JWT_SECRET``. We recreate them byte-for-byte with the same
  header/claims as ``scripts/supabase/generate-keys.sh`` (the canonical
  generator), so an operator only ever sets ``JWT_SECRET``.
* **Generated elsewhere** — ``POSTGRES_PASSWORD`` is minted at db-init
  (``scripts/supabase/db-passwd.sh``) and must match the running database, so we
  do **not** fabricate it here (a funnel-invented value would desync the DB). It
  is only *recognized* as self-generated so it is not flagged as an operator gap.

Design: additive and idempotent — an operator-supplied value is never
overwritten; missing ``JWT_SECRET`` is a no-op (nothing to derive).
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
from typing import Dict, Mapping

# Canonical Supabase JWT claims — MUST match scripts/supabase/generate-keys.sh.
_JWT_ISS = "supabase-local"
_JWT_IAT = 1641769200   # fixed timestamp for reproducibility (generate-keys.sh)
_JWT_EXP = 1799535600   # far-future expiry (generate-keys.sh)

# Canonical label -> role, plus the short aliases the pipe also carries.
_SUPABASE_JWT_KEYS: dict[str, str] = {
    "SUPABASE_ANON_KEY": "anon",
    "ANON_KEY": "anon",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY": "anon",
    "SUPABASE_SERVICE_ROLE_KEY": "service_role",
    "SERVICE_ROLE_KEY": "service_role",
}

# Self-generated but NOT derivable in the funnel (minted at db-init, must match
# the running database). Recognized so it is not reported as an operator gap.
_GENERATED_ELSEWHERE: frozenset[str] = frozenset({"POSTGRES_PASSWORD"})

# Everything the funnel considers self-generated (for operator-missing reports).
SELF_GENERATED: frozenset[str] = frozenset(_SUPABASE_JWT_KEYS) | _GENERATED_ELSEWHERE


def _b64url(raw: bytes) -> str:
    """URL-safe base64 without padding — the JWT wire format."""
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")


def derive_supabase_jwt(
    secret: str,
    role: str,
    *,
    iat: int = _JWT_IAT,
    exp: int = _JWT_EXP,
    iss: str = _JWT_ISS,
) -> str:
    """Derive a Supabase HS256 JWT for ``role`` from ``JWT_SECRET``.

    Byte-for-byte compatible with ``generate-keys.sh``'s ``generate_jwt_token``:
    compact JSON (no spaces), claim order ``role, iss, iat, exp``, HS256.
    """
    header = json.dumps({"alg": "HS256", "typ": "JWT"}, separators=(",", ":"))
    payload = json.dumps(
        {"role": role, "iss": iss, "iat": iat, "exp": exp},
        separators=(",", ":"),
    )
    signing_input = f"{_b64url(header.encode())}.{_b64url(payload.encode())}"
    signature = hmac.new(
        secret.encode(), signing_input.encode(), hashlib.sha256
    ).digest()
    return f"{signing_input}.{_b64url(signature)}"


def fill_self_generated(secrets: Mapping[str, str]) -> Dict[str, str]:
    """Return a copy of ``secrets`` with derivable self-generated keys filled.

    Derives the Supabase ``anon``/``service_role`` keys from ``JWT_SECRET`` for
    any of their labels that are absent (or set to an empty/sentinel value).
    Operator-supplied values are preserved. A missing ``JWT_SECRET`` is a no-op.
    """
    out: Dict[str, str] = dict(secrets)
    jwt_secret = (out.get("JWT_SECRET") or out.get("SUPABASE_JWT_SECRET") or "").strip()
    if not jwt_secret:
        return out

    for label, role in _SUPABASE_JWT_KEYS.items():
        if (out.get(label) or "").strip():
            continue  # never overwrite an operator/DB-supplied value
        out[label] = derive_supabase_jwt(jwt_secret, role)
    return out
