#!/usr/bin/env python3
"""Sweep for SILENT exception handlers around imports — the shape behind finding #7.

Why this exists
---------------
`docs/audit/INSTRUMENT_TRUST_AUDIT_2026-08-15.md` reports a funnel — 157 -> 60 -> 6 -> 4
— and calls the first number the actual finding: a raw count of "broad `except` around
an import" would have been a fleet-wide alarm and would have been WRONG, because
`torch` / `faiss` / `rich` / `psutil` guards are correct. That funnel was produced by a
script written in the moment and thrown away, so the audit's load-bearing number could
not be regenerated by anyone reading it. This file is that script, made durable.

An audit whose central number cannot be reproduced is folklore with line numbers.

What it does and does not decide
--------------------------------
Stages 1-3 are MECHANICAL and reproducible:

    1. `try:` containing an import, with a broad (`Exception`/`BaseException`) or bare
       handler.
    2. ...of those, handlers that are SILENT: no raise, no log, no warn, no print, no
       write to stderr, no explicit degraded-state flag assignment.
    3. ...of those, handlers whose body is exactly `pass` / `...`.

Stage 4 — "in a path that reports outward as authoritative" — is a HUMAN JUDGEMENT and
is deliberately NOT automated. The tool prints stage-3 sites for classification rather
than pretending to classify them. That boundary is the whole point of the audit: the
antipattern is not "a broad `except` on an import", it is *a silent handler in a path
that reports outward*, and only a reader can tell whether a caller can see the
degradation.

Why AST and not grep
--------------------
A text grep cannot see a handler's shape. It cannot tell `except Exception: pass` from
`except Exception: logger.exception(...)`, nor an import inside a `try` from one merely
near it. Running this as a grep is how 157 becomes a false alarm.

Counterexamples the sweep is expected to CLEAR (both survive stage 1 honestly and are
filtered at stage 2, and both are cited in the audit):

    services/hf-mcp-server/main.py  — falls back to the static catalog and stamps
                                      `"source": "catalog"`; the consumer sees which.
    tools/chit_security.py          — crypto import failure sets `_CRYPTO_OK = False`,
                                      an explicit degraded flag.

If either starts appearing at stage 2, the tool is wrong, not the code.

Usage
-----
    python pmoves/tools/silent_handler_sweep.py               # funnel + stage-3 sites
    python pmoves/tools/silent_handler_sweep.py --json        # machine-readable
    python pmoves/tools/silent_handler_sweep.py --stage 2     # list stage-2 sites too
    python pmoves/tools/silent_handler_sweep.py --path pmoves/services
    python pmoves/tools/silent_handler_sweep.py --legacy      # reproduce the 08-15 column
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
import warnings
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, List

_REPO_ROOT = Path(__file__).resolve().parents[2]

# Swept trees. The audit swept exactly these two; keep the default identical so the
# published numbers stay comparable across runs.
DEFAULT_PATHS = ("pmoves/tools", "pmoves/services")

EXCLUDE_PARTS = (
    "venv",
    ".venv",
    "node_modules",
    ".git",
    "__pycache__",
    "site-packages",
    ".claude",
)

# A call makes a handler AUDIBLE when its CALLEE NAME reads as reporting or exiting.
# Matched on the callee identifier only — `logger.exception`, `print_error`,
# `error_msg`, `sys.exit`, `sys.stderr.write` — never on the whole handler.
#
# That distinction is the point. The original throwaway sweep decided silence by
# substring-scanning `ast.dump(handler).lower()` for "log"/"print"/"warn"/"stderr"/
# "exit", which is a text grep wearing an AST costume: any identifier ANYWHERE in the
# handler that merely CONTAINS one of those (a local named `catalog`, `dialog`,
# `logic`, `exit_code`) reads as a report. In a sweep whose headline is that a text
# grep cannot see a handler's shape, the sweep itself was a text grep.
# Standard logging methods, matched EXACTLY. `info` and `debug` have to be here rather
# than in the regex below: as substrings they would swallow `get_info`, `stream_info`,
# `debug_path` and hand back the same false-audible the substring rule produces.
_LOG_METHODS = {
    "debug",
    "info",
    "warning",
    "warn",
    "error",
    "exception",
    "critical",
    "fatal",
    "log",
}

# Custom reporters that are not logging methods — `print_error`, `error_msg`,
# `_notify_error`, `sys.exit`, `sys.stderr.write`. Substring here is acceptable because
# it is applied to the CALLEE IDENTIFIER only, never to the handler body.
_AUDIBLE_RE = re.compile(
    r"log|print|warn|error|fail|abort|notify|report|echo|die|exit|write",
    re.IGNORECASE,
)

# Acquiring a logger is not reporting with one. `_logger = logging.getLogger(...)` in
# a handler tells nobody anything, and the substring rule above called it audible —
# the one disagreement where the original predicate was wrong and this one is right.
_NOT_AUDIBLE = {"getlogger", "get_logger"}


def _is_audible_call(node: ast.Call) -> bool:
    func = node.func
    if isinstance(func, ast.Attribute):
        name = func.attr
    elif isinstance(func, ast.Name):
        name = func.id
    else:
        return False
    lowered = name.lower()
    if lowered in _NOT_AUDIBLE:
        return False
    if lowered in _LOG_METHODS:
        return True
    return bool(_AUDIBLE_RE.search(name))


@dataclass
class Site:
    """One `try:`-with-import whose handler is broad or bare."""

    path: str
    lineno: int          # line of the `try:`
    handler_lineno: int  # line of the `except`
    handler: str         # rendered handler type, e.g. "except Exception"
    imports: List[str] = field(default_factory=list)
    silent: bool = False
    pass_only: bool = False

    def as_dict(self) -> dict:
        return {
            "path": self.path,
            "lineno": self.lineno,
            "handler_lineno": self.handler_lineno,
            "handler": self.handler,
            "imports": self.imports,
            "silent": self.silent,
            "pass_only": self.pass_only,
        }


def _is_broad(handler: ast.ExceptHandler) -> bool:
    """Bare `except:`, or one naming Exception/BaseException (alone or in a tuple)."""
    if handler.type is None:
        return True
    names = (
        handler.type.elts if isinstance(handler.type, ast.Tuple) else [handler.type]
    )
    for node in names:
        if isinstance(node, ast.Name) and node.id in ("Exception", "BaseException"):
            return True
        # `except builtins.Exception:` — rare, but cheap to accept.
        if isinstance(node, ast.Attribute) and node.attr in (
            "Exception",
            "BaseException",
        ):
            return True
    return False


def _render_handler(handler: ast.ExceptHandler) -> str:
    if handler.type is None:
        return "except:"
    try:
        return f"except {ast.unparse(handler.type)}"
    except Exception:  # pragma: no cover — unparse exists on 3.9+, guard anyway
        return "except <unrenderable>"


def _imports_in(node: ast.Try) -> List[str]:
    """Import statements anywhere in the `try` body (not the handlers/else/finally)."""
    names: List[str] = []
    for stmt in node.body:
        for sub in ast.walk(stmt):
            if isinstance(sub, ast.Import):
                names.extend(a.name for a in sub.names)
            elif isinstance(sub, ast.ImportFrom):
                mod = sub.module or ""
                names.extend(f"{mod}.{a.name}" if mod else a.name for a in sub.names)
    return names


def _is_silent(handler: ast.ExceptHandler) -> bool:
    """Silent = the audit's own stage-2 definition: no log, no raise, no warn.

    Deliberately NOT counted as audible, though the first draft of this file counted
    both and got 7 where the settled predicate gets 69:

      * `Assign` — `_CRYPTO_OK = False` records the failure somewhere a caller can
        read it, which is why `chit_security.py` is a counterexample. But it is
        genuinely silent AT THE MOMENT OF FAILURE, so it belongs in stage 2 and gets
        cleared at stage 3 (its handler is not `pass`). Treating it as audible here
        collapses the funnel and hides the very shape being counted.
      * `Return` — `except Exception: return _FALLBACK` is finding #7 exactly. A
        predicate that calls that "audible" would have excluded the finding that
        motivated the sweep.

    Both exclusions are the same error in miniature: widening "audible" until the
    alarming number goes away.
    """
    for sub in ast.walk(handler):
        if isinstance(sub, ast.Raise):
            return False
        if isinstance(sub, ast.Call) and _is_audible_call(sub):
            return False
    return True


# --------------------------------------------------------------------------------
# Legacy predicate — the original throwaway sweep, preserved verbatim in behaviour.
#
# The audit's middle column (63 silent / 2 pass-only on 2026-08-17) came from re-running
# the original script after recovering it from a scratch directory. Documenting that
# number while leaving the predicate un-runnable would repeat, one level down, the exact
# defect being corrected: a published figure a reader cannot regenerate. `--legacy`
# reproduces it.
#
# It is kept for reconciliation only. It is wrong in two directions and both are
# load-bearing history: it decides silence by substring-scanning `ast.dump(handler)`,
# and it only sees imports that are DIRECT children of the `try` body.
# --------------------------------------------------------------------------------

_LEGACY_KEYS = ("log", "print", "warn", "stderr", "exit")


def _legacy_is_broad(handler: ast.ExceptHandler) -> bool:
    """Original: bare, or a bare `Name`. No tuple support, no `Attribute` support."""
    return handler.type is None or (
        isinstance(handler.type, ast.Name)
        and handler.type.id in ("Exception", "BaseException")
    )


def _legacy_is_silent(handler: ast.ExceptHandler) -> bool:
    """Original: a substring scan of the whole dumped handler. See the note above."""
    if any(isinstance(n, ast.Raise) for n in ast.walk(handler)):
        return False
    low = ast.dump(handler).lower()
    return not any(k in low for k in _LEGACY_KEYS)


def _legacy_has_import(node: ast.Try) -> bool:
    """Original: import must be a DIRECT child of the try body, never nested."""
    return any(isinstance(s, (ast.Import, ast.ImportFrom)) for s in node.body)


def _is_pass_only(handler: ast.ExceptHandler) -> bool:
    return all(
        isinstance(stmt, ast.Pass)
        or (
            isinstance(stmt, ast.Expr)
            and isinstance(stmt.value, ast.Constant)
            and stmt.value.value is Ellipsis
        )
        for stmt in handler.body
    )


def iter_python_files(paths: Iterable[str]) -> List[Path]:
    found: List[Path] = []
    for rel in paths:
        base = _REPO_ROOT / rel
        if not base.exists():
            print(f"[warn] {rel} does not exist — skipped", file=sys.stderr)
            continue
        for p in base.rglob("*.py"):
            relp = p.relative_to(_REPO_ROOT)
            if any(part in EXCLUDE_PARTS for part in relp.parts):
                continue
            found.append(p)
    return sorted(found)


def sweep(paths: Iterable[str], legacy: bool = False) -> List[Site]:
    has_import = _legacy_has_import if legacy else None
    is_broad = _legacy_is_broad if legacy else _is_broad
    is_silent = _legacy_is_silent if legacy else _is_silent

    sites: List[Site] = []
    unparsed = 0
    for path in iter_python_files(paths):
        try:
            # Swept files raise SyntaxWarning for their own bad escapes ("\p", "\S").
            # Those warnings print as "<unknown>:4:" and read as defects in THIS
            # tool, so they are suppressed rather than left to misattribute.
            with warnings.catch_warnings():
                warnings.simplefilter("ignore", SyntaxWarning)
                tree = ast.parse(path.read_text(encoding="utf-8", errors="replace"))
        except SyntaxError:
            # A file this tool cannot parse is a file it cannot vouch for. Count it
            # rather than letting it vanish into a clean-looking total.
            unparsed += 1
            continue
        # .as_posix(), not str(): on Windows str() yields backslashes, so every
        # emitted path — and anything derived from it, including a baseline or a
        # cross-referenced report — differs by platform for the same file. Forward
        # slashes are what the rest of this repo's tooling records.
        rel = path.relative_to(_REPO_ROOT).as_posix()
        for node in ast.walk(tree):
            if not isinstance(node, ast.Try):
                continue
            if has_import is not None and not has_import(node):
                continue
            imports = _imports_in(node)
            if not imports:
                continue
            for handler in node.handlers:
                if not is_broad(handler):
                    continue
                sites.append(
                    Site(
                        path=rel,
                        lineno=node.lineno,
                        handler_lineno=handler.lineno,
                        handler=_render_handler(handler),
                        imports=imports,
                        silent=is_silent(handler),
                        pass_only=_is_pass_only(handler),
                    )
                )
    if unparsed:
        print(f"[warn] {unparsed} file(s) failed to parse and were skipped", file=sys.stderr)
    return sites


def main() -> int:
    ap = argparse.ArgumentParser(description=(__doc__ or "").split("\n")[0])
    ap.add_argument("--json", action="store_true", help="machine-readable output")
    ap.add_argument(
        "--stage",
        type=int,
        choices=(1, 2, 3),
        default=3,
        help="list sites at this stage (default 3)",
    )
    ap.add_argument(
        "--path",
        action="append",
        dest="paths",
        help=f"tree to sweep, repeatable (default: {', '.join(DEFAULT_PATHS)})",
    )
    ap.add_argument(
        "--legacy",
        action="store_true",
        help="use the original 2026-08-15 predicate (reconciliation only — it is wrong "
        "in two known directions; see the note above _legacy_is_silent)",
    )
    args = ap.parse_args()

    paths = args.paths or list(DEFAULT_PATHS)
    stage1 = sweep(paths, legacy=args.legacy)
    stage2 = [s for s in stage1 if s.silent]
    stage3 = [s for s in stage2 if s.pass_only]
    listing = {1: stage1, 2: stage2, 3: stage3}[args.stage]

    if args.json:
        print(
            json.dumps(
                {
                    "swept": paths,
                    "funnel": {
                        "try_import_broad_except": len(stage1),
                        "silent": len(stage2),
                        "pass_only": len(stage3),
                    },
                    # Stage 4 is a human call. Emitting a number here would be the
                    # exact error the audit documents.
                    "reports_outward": None,
                    "stage": args.stage,
                    "sites": [s.as_dict() for s in listing],
                },
                indent=2,
            )
        )
        return 0

    print(f"Swept: {', '.join(paths)}")
    print()
    print(f"{'Filter':<58} {'Hits':>5}")
    print("-" * 64)
    print(f"{'try: containing an import, broad or bare except':<58} {len(stage1):>5}")
    print(f"{'  ...of those, handlers that are SILENT':<58} {len(stage2):>5}")
    print(f"{'  ...of those, handlers that are fully pass':<58} {len(stage3):>5}")
    print(f"{'  ...of those, in a path that REPORTS OUTWARD':<58} {'human':>5}")
    print()
    print(f"Stage {args.stage} sites ({len(listing)}):")
    for s in listing:
        mods = ", ".join(s.imports[:3]) + ("…" if len(s.imports) > 3 else "")
        print(f"  {s.path}:{s.handler_lineno}  {s.handler}  [{mods}]")
    if args.stage == 3:
        print()
        print(
            "Stage 4 is not automated. For each site above, ask: can the CALLER see\n"
            "the degradation? If the function returns a complete-looking result built\n"
            "from nothing, it belongs in the audit. If the feature visibly degrades,\n"
            "it does not."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
