#!/usr/bin/env python3
"""Validate-composes ratchet.

No-network, <100ms scan of every `pmoves/docker-compose*.yml` file.
Fails (exit 1) on any of the operator-trust patterns below; the fix is
either convert to long form, drop the entry, or justify it in a
follow-up PR. The ratchet only goes DOWN over time — a fix that
re-introduces a straggler is caught immediately, not after the next
incidents-of-silence audit.

Patterns enforced (per PMOVES Mavis housekeeping batch 2026-08-03 +
the straggler sweep in PR #2415):

  1. env_file short-form `.env.local` — REQUIRED by default in
     docker-compose; hard-fails bring-up on nodes without the file.
     Fix: long-form `- path: .env.local / required: false`.
  2. env_file short-form with `env.shared` — same class of issue
     if a node doesn't have that file. Fix: long-form + required: false
     if it should be optional, or fix the bring-up to always create it.
  3. images without digest — fleet policy is digest-pinned for any
     image that runs in production. `latest`, semver tags, and
     non-digested refs all surface here so the operator sees the gap
     before the next "why is prod on a moving tag" incident.

This script reads a static set of YAML files in the repo. No GitHub
API, no fork-registry access, no token privilege. Runs in <100ms on
the full ~50-file overlay set.

Usage:
    python3 pmoves/tools/validate_composes.py
    python3 pmoves/tools/validate_composes.py --json
    python3 pmoves/tools/validate_composes.py --check-images
    python3 pmoves/tools/validate_composes.py --strict-env-shared

By default only env_file patterns are checked (the env.local
straggler shape from PR #2415). Pass --check-images to also flag
images without digest pinning — that's a fleet-policy ratchet, not
a "merged before the issue was addressed" ratchet, and produces a
lot of false-positive noise on overlays that haven't been migrated
yet.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
COMPOSE_GLOB = "docker-compose*.yml"
COMPOSE_DIR = REPO_ROOT / "pmoves"

# The set of overlays that `make -C pmoves compose-split` regenerates
# from the main docker-compose.yml. These are the only ones we can
# auto-regen, so changes to them get caught by `make compose-split`
# before they land. The ratchet still scans them, but a finding here
# is "make compose-split will overwrite this" — operators can either
# edit the main file (preferred) or accept the regen.
GENERATED_OVERLAYS = frozenset({
    "docker-compose.core.yml",
    "docker-compose.agents.yml",
    "docker-compose.media.yml",
    "docker-compose.ui.yml",
    "docker-compose.workers.yml",
    "docker-compose.apps.yml",
    "docker-compose.juicefs.yml",
})

# Hand-maintained overlays that are NOT regenerated by compose-split.
# The stragglers in PR #2415 lived in this set; the ratchet is
# specifically designed to catch the next one.
HAND_MAINTAINED_OVERLAYS = frozenset({
    "docker-compose.agentgym.yml",
    "docker-compose.gpu-image.yml",
    "docker-compose.n8n.postgres.yml",
    "docker-compose.alertmanager.yml",
    "docker-compose.amd-voice.yml",
    "docker-compose.archon.submodule.yml",
    "docker-compose.arm64.override.yml",
    "docker-compose.base.yml",
    "docker-compose.cache.yml",
    "docker-compose.chit-tour.yml",
    "docker-compose.comfyui.yml",
    "docker-compose.darkxside-sidecar.yml",
    "docker-compose.elder-melchor.yml",
    "docker-compose.external.yml",
    "docker-compose.gpu-4090.yml",
    "docker-compose.gpu.yml",
    "docker-compose.hardened.yml",
    "docker-compose.integrations.images.yml",
    "docker-compose.agents.images.yml",
    "docker-compose.agents.integrations.yml",
    "docker-compose.jellyfin-ai.yml",
    "docker-compose.jellyfin.hosts.yml",
    "docker-compose.jetson-edge.override.yml",
    "docker-compose.juicefs-mount.yml",
    "docker-compose.laptop-4090.override.yml",
    "docker-compose.n8n.yml",
    "docker-compose.open-notebook.yml",
    "docker-compose.persona.yml",
    "docker-compose.remote.yml",
    "docker-compose.rustdesk.yml",
    "docker-compose.spark-sidecar.yml",
    "docker-compose.sso.yml",
    "docker-compose.tailscale.yml",
    "docker-compose.tracing.yml",
    "docker-compose.traefik.yml",
    "docker-compose.ultimate-tts-studio.yml",
    "docker-compose.voice.yml",
    "docker-compose.vps.override.yml",
    "docker-compose.yt-cookies.yml",
    "docker-compose.yt-egress.yml",
    "docker-compose.yt-media.yml",
    "docker-compose.z890.override.yml",
    "docker-compose.z890.yml",
    "docker-compose.yml",  # the main file
})

# Pin-digest regex (the canonical sha256:64hex form for a digest).
DIGEST_RE = re.compile(r"@sha256:[0-9a-f]{64}\b")


def _scan_env_file(
    file: Path,
    service: str,
    env_file,
) -> list[dict]:
    """Return problems for one service's env_file value."""
    if env_file is None:
        return []
    problems: list[dict] = []
    if isinstance(env_file, str):
        # Single-string form `env_file: foo`: docker-compose treats
        # this as REQUIRED. Fine in most cases; flagged only for
        # `.env.local` (always opt-in).
        if env_file == ".env.local":
            problems.append({
                "file": str(file.relative_to(REPO_ROOT)),
                "service": service,
                "kind": "env-local-shortform",
                "detail": (
                    "env_file: '.env.local' is REQUIRED by default. "
                    "Use long-form `path: .env.local / required: false` "
                    "so bring-up doesn't hard-fail on nodes without the file."
                ),
            })
        return problems
    if not isinstance(env_file, list):
        return []
    for entry in env_file:
        if entry == ".env.local":
            problems.append({
                "file": str(file.relative_to(REPO_ROOT)),
                "service": service,
                "kind": "env-local-shortform",
                "detail": (
                    "short-form `.env.local` in env_file list is REQUIRED by "
                    "default. Use long-form `path: .env.local / required: false`."
                ),
            })
        elif isinstance(entry, dict) and entry.get("path") == ".env.local":
            # long-form present; OK if not required
            if entry.get("required", True):
                problems.append({
                    "file": str(file.relative_to(REPO_ROOT)),
                    "service": service,
                    "kind": "env-local-longform-required",
                    "detail": (
                        "long-form .env.local is marked required=True; this is "
                        "the same problem as the short form. Set required=False."
                    ),
                })
        elif entry == "env.shared":
            # env.shared is provided by the bootstrap script on every
            # node; a REQUIRED listing here is a no-op. Flag only if
            # --strict-env-shared is passed.
            pass
    return problems


def _scan_image(
    file: Path,
    service: str,
    image,
) -> list[dict]:
    """Return problems for a service's image field (digest pinning)."""
    if not isinstance(image, str):
        return []
    if image.startswith("${") and ":-" in image:
        # `${VAR:-default}` form — flag the default value, not the
        # env-var reference.
        default = image.split(":-", 1)[1].rstrip("}")
        target = default
    else:
        target = image
    if "@sha256:" in target:
        return []  # already digest-pinned
    # Allow build: context (not a registry ref) and platform-only
    # refs that are obviously local.
    if target.startswith("./") or target.startswith("/"):
        return []
    # Bare service names without a tag (e.g. `postgres`) — not
    # pinned to a digest, but also not a moving tag. Tag-less refs
    # default to `:latest` in compose, so they ARE moving. Flag.
    if ":" not in target.split("/")[-1]:
        return [{
            "file": str(file.relative_to(REPO_ROOT)),
            "service": service,
            "kind": "image-no-tag",
            "detail": f"image '{image}' has no tag; defaults to :latest.",
        }]
    tag = target.split(":")[-1].split("@")[0]
    if tag in ("latest",) or re.match(r"^\d+(\.\d+){0,2}$", tag):
        return [{
            "file": str(file.relative_to(REPO_ROOT)),
            "service": service,
            "kind": "image-no-digest",
            "detail": (
                f"image '{image}' uses moving tag '{tag}'. "
                "Pin to @sha256:... for production."
            ),
        }]
    return []


def _yaml_safe_load_with_compose_tags(text: str):
    """yaml.safe_load that tolerates PMOVES Compose custom tags.

    PMOVES uses `!override` and `!reset` (Docker Compose 2.24+
    replace-don't-append semantics). PyYAML's SafeLoader raises on
    these tags, so the ratchet has to register the same handlers
    that `pmoves/tests/conftest.py` registers before parsing. The
    handlers reconstruct the underlying value, so the parsed
    structure matches the post-merge intent and downstream
    `env_file` / `image` extraction works.
    """
    import yaml

    def _compose_override_tag(loader, node):
        if isinstance(node, yaml.SequenceNode):
            return loader.construct_sequence(node)
        if isinstance(node, yaml.MappingNode):
            return loader.construct_mapping(node)
        return loader.construct_scalar(node)

    for tag in ("!override", "!reset"):
        yaml.SafeLoader.add_constructor(tag, _compose_override_tag)
    return yaml.safe_load(text)


def _scan_file(file: Path) -> list[dict]:
    """Scan one compose YAML for problems."""
    try:
        import yaml  # noqa: F401
    except ImportError:
        print("PyYAML required: pip install pyyaml", file=sys.stderr)
        sys.exit(2)
    with file.open(encoding="utf-8") as fh:
        data = _yaml_safe_load_with_compose_tags(fh)
    if not isinstance(data, dict):
        return []
    services = data.get("services") or {}
    if not isinstance(services, dict):
        return []
    problems: list[dict] = []
    for svc_name, svc in services.items():
        if not isinstance(svc, dict):
            continue
        # env_file may live at the service level, or on a `<<: *anchor`
        # merge target — we only scan the literal block here. (Most
        # overlays keep env_file inline; the anchor pattern would need
        # a separate pass that's out of scope for this ratchet.)
        problems.extend(_scan_env_file(file, svc_name, svc.get("env_file")))
        problems.extend(_scan_image(file, svc_name, svc.get("image")))
    return problems


def _all_compose_files() -> list[Path]:
    if not COMPOSE_DIR.exists():
        return []
    return sorted(COMPOSE_DIR.glob(COMPOSE_GLOB))


def _scan_one_file(path: Path, check_images: bool) -> list[dict]:
    """Scan a single file and filter image problems by check_images."""
    out: list[dict] = []
    for p in _scan_file(path):
        if p["kind"].startswith("image-") and not check_images:
            continue
        out.append(p)
    return out


def _summary(problems: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for p in problems:
        counts[p["kind"]] = counts.get(p["kind"], 0) + 1
    return counts


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--strict-env-shared",
        action="store_true",
        help="also flag short-form `env.shared` listings (default: skip; env.shared is provided by bootstrap)",
    )
    parser.add_argument(
        "--check-images",
        action="store_true",
        help="also flag images without digest pinning (off by default; produces a lot of noise on pre-migration overlays)",
    )
    parser.add_argument(
        "--file",
        type=Path,
        help="scan a single file instead of the whole pmoves/ tree (test-only path; for CI use the default glob)",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="emit JSON instead of human-readable text",
    )
    args = parser.parse_args()

    if args.file:
        if not args.file.exists():
            print(f"file not found: {args.file}", file=sys.stderr)
            return 2
        files = [args.file]
    else:
        files = _all_compose_files()
    if not files:
        print(f"no compose files found under {COMPOSE_DIR}", file=sys.stderr)
        return 2

    problems: list[dict] = []
    for f in files:
        problems.extend(_scan_one_file(f, args.check_images))

    if args.json:
        print(json.dumps({
            "files_scanned": [str(f.relative_to(REPO_ROOT)) for f in files],
            "files_total": len(files),
            "problems": problems,
            "summary": _summary(problems),
        }, indent=2))
    else:
        print(f"validate-composes: scanned {len(files)} compose files")
        if not problems:
            print("  (clean — no stragglers)")
        else:
            counts = _summary(problems)
            print(f"  {len(problems)} problem(s):")
            for kind, n in sorted(counts.items()):
                print(f"    {kind}: {n}")
            print()
            for p in problems:
                print(f"  [{p['kind']}] {p['file']} :: {p['service']}")
                print(f"      {p['detail']}")

    return 0 if not problems else 1


if __name__ == "__main__":
    sys.exit(main())
